"""GENERATED by tools/gen_test_aggregates.py -- do not edit.

Aggregates the 3 test files of `tests_gpu/fft/` into one compiled
binary, so 3 compiler invocations become one. Run it with
`mojo -I . -I tests_gpu/fft` (see tools/run_test_aggregates.sh).

Regenerate with `pixi run tests-gen`; CI fails if this file is out of date
with the tree.
"""

from std.testing import TestSuite
from test_fftn_gpu import (
    test_fftn_and_ifftn_on_the_device as test_fftn_gpu__test_fftn_and_ifftn_on_the_device,
)
from test_fftn_gpu import (
    test_rfftn_and_irfftn_on_the_device as test_fftn_gpu__test_rfftn_and_irfftn_on_the_device,
)
from test_fftn_gpu import (
    test_irfft2_on_the_device as test_fftn_gpu__test_irfft2_on_the_device,
)
from test_norm_hfft_gpu import (
    test_norms_on_the_device_match_the_host as test_norm_hfft_gpu__test_norms_on_the_device_match_the_host,
)
from test_norm_hfft_gpu import (
    test_hfft_round_trip_on_the_device as test_norm_hfft_gpu__test_hfft_round_trip_on_the_device,
)
from test_trign_gpu import (
    test_dctn_on_the_device_matches_the_host as test_trign_gpu__test_dctn_on_the_device_matches_the_host,
)
from test_trign_gpu import (
    test_dstn_round_trip_on_the_device as test_trign_gpu__test_dstn_round_trip_on_the_device,
)


def main() raises:
    var suite = TestSuite()
    # tests_gpu/fft/test_fftn_gpu.mojo
    suite.test[test_fftn_gpu__test_fftn_and_ifftn_on_the_device]()
    suite.test[test_fftn_gpu__test_rfftn_and_irfftn_on_the_device]()
    suite.test[test_fftn_gpu__test_irfft2_on_the_device]()
    # tests_gpu/fft/test_norm_hfft_gpu.mojo
    suite.test[test_norm_hfft_gpu__test_norms_on_the_device_match_the_host]()
    suite.test[test_norm_hfft_gpu__test_hfft_round_trip_on_the_device]()
    # tests_gpu/fft/test_trign_gpu.mojo
    suite.test[test_trign_gpu__test_dctn_on_the_device_matches_the_host]()
    suite.test[test_trign_gpu__test_dstn_round_trip_on_the_device]()
    suite^.run()
