"""GENERATED by tools/gen_test_aggregates.py -- do not edit.

Aggregates the 3 test files of `tests_gpu/linalg/` into one compiled
binary, so 3 compiler invocations become one. Run it with
`mojo -I . -I tests_gpu/linalg` (see tools/run_test_aggregates.sh).

Regenerate with `pixi run tests-gen`; CI fails if this file is out of date
with the tree.
"""

from std.testing import TestSuite
from test_array_kernels_gpu import (
    test_array_tier_runs_inside_a_device_kernel as test_array_kernels_gpu__test_array_tier_runs_inside_a_device_kernel,
)
from test_generalized_eigh_gpu import (
    test_generalized_eigh_on_the_device_matches_the_host as test_generalized_eigh_gpu__test_generalized_eigh_on_the_device_matches_the_host,
)
from test_linalg_gpu import (
    test_matmul_on_the_device_matches_the_host as test_linalg_gpu__test_matmul_on_the_device_matches_the_host,
)
from test_linalg_gpu import (
    test_cholesky_on_the_device_matches_the_host as test_linalg_gpu__test_cholesky_on_the_device_matches_the_host,
)
from test_linalg_gpu import (
    test_solve_on_the_device_matches_the_host as test_linalg_gpu__test_solve_on_the_device_matches_the_host,
)
from test_linalg_gpu import (
    test_the_extremal_norms_on_the_device_match_the_host as test_linalg_gpu__test_the_extremal_norms_on_the_device_match_the_host,
)
from test_linalg_gpu import (
    test_rq_on_the_device_matches_the_host as test_linalg_gpu__test_rq_on_the_device_matches_the_host,
)
from test_linalg_gpu import (
    test_transposed_triangular_solves_on_the_device_match_the_host as test_linalg_gpu__test_transposed_triangular_solves_on_the_device_match_the_host,
)


def main() raises:
    var suite = TestSuite()
    # tests_gpu/linalg/test_array_kernels_gpu.mojo
    suite.test[
        test_array_kernels_gpu__test_array_tier_runs_inside_a_device_kernel
    ]()
    # tests_gpu/linalg/test_generalized_eigh_gpu.mojo
    suite.test[
        test_generalized_eigh_gpu__test_generalized_eigh_on_the_device_matches_the_host
    ]()
    # tests_gpu/linalg/test_linalg_gpu.mojo
    suite.test[test_linalg_gpu__test_matmul_on_the_device_matches_the_host]()
    suite.test[test_linalg_gpu__test_cholesky_on_the_device_matches_the_host]()
    suite.test[test_linalg_gpu__test_solve_on_the_device_matches_the_host]()
    suite.test[
        test_linalg_gpu__test_the_extremal_norms_on_the_device_match_the_host
    ]()
    suite.test[test_linalg_gpu__test_rq_on_the_device_matches_the_host]()
    suite.test[
        test_linalg_gpu__test_transposed_triangular_solves_on_the_device_match_the_host
    ]()
    suite^.run()
