"""GENERATED by tools/gen_test_aggregates.py -- do not edit.

Aggregates the 1 test files of `tests_gpu/core/` into one compiled
binary, so 1 compiler invocations become one. Run it with
`mojo -I . -I tests_gpu/core` (see tools/run_test_aggregates.sh).

Regenerate with `pixi run tests-gen`; CI fails if this file is out of date
with the tree.
"""

from std.testing import TestSuite
from test_surface_gpu import (
    test_exp_on_the_device_matches_the_host as test_surface_gpu__test_exp_on_the_device_matches_the_host,
)
from test_surface_gpu import (
    test_add_on_the_device_matches_the_host as test_surface_gpu__test_add_on_the_device_matches_the_host,
)
from test_surface_gpu import (
    test_sum_and_argmax_on_the_device_match_the_host as test_surface_gpu__test_sum_and_argmax_on_the_device_match_the_host,
)


def main() raises:
    var suite = TestSuite()
    # tests_gpu/core/test_surface_gpu.mojo
    suite.test[test_surface_gpu__test_exp_on_the_device_matches_the_host]()
    suite.test[test_surface_gpu__test_add_on_the_device_matches_the_host]()
    suite.test[
        test_surface_gpu__test_sum_and_argmax_on_the_device_match_the_host
    ]()
    suite^.run()
