"""GENERATED by tools/gen_test_aggregates.py -- do not edit.

Aggregates the 17 test files of `tests_gpu/stats/` into one compiled
binary, so 17 compiler invocations become one. Run it with
`mojo -I . -I tests_gpu/stats` (see tools/run_test_aggregates.sh).

Regenerate with `pixi run tests-gen`; CI fails if this file is out of date
with the tree.
"""

from std.testing import TestSuite
from test_correlation_gpu import (
    test_pearsonr_on_the_device_matches_the_host as test_correlation_gpu__test_pearsonr_on_the_device_matches_the_host,
)
from test_correlation_gpu import (
    test_linregress_on_the_device_matches_the_host as test_correlation_gpu__test_linregress_on_the_device_matches_the_host,
)
from test_descriptive_gpu import (
    test_the_moment_statistics_on_the_device_match_the_host as test_descriptive_gpu__test_the_moment_statistics_on_the_device_match_the_host,
)
from test_descriptive_gpu import (
    test_the_means_and_entropies_on_the_device_match_the_host as test_descriptive_gpu__test_the_means_and_entropies_on_the_device_match_the_host,
)
from test_extreme_infinities_gpu import (
    test_whole_tensor_extremes_on_the_device as test_extreme_infinities_gpu__test_whole_tensor_extremes_on_the_device,
)
from test_extreme_infinities_gpu import (
    test_axis_extremes_on_the_device as test_extreme_infinities_gpu__test_axis_extremes_on_the_device,
)
from test_histograms_gpu import (
    test_the_one_dimensional_histograms_on_the_device as test_histograms_gpu__test_the_one_dimensional_histograms_on_the_device,
)
from test_histograms_gpu import (
    test_the_multi_dimensional_histograms_on_the_device as test_histograms_gpu__test_the_multi_dimensional_histograms_on_the_device,
)
from test_histograms_gpu import (
    test_bincount_and_digitize_on_the_device as test_histograms_gpu__test_bincount_and_digitize_on_the_device,
)
from test_hypothesis_gpu import (
    test_t_tests_on_the_device_match_the_host as test_hypothesis_gpu__test_t_tests_on_the_device_match_the_host,
)
from test_hypothesis_gpu import (
    test_chisquare_and_anova_on_the_device_match_the_host as test_hypothesis_gpu__test_chisquare_and_anova_on_the_device_match_the_host,
)
from test_keepdims_gpu import (
    test_keepdims_on_the_device_matches_the_host as test_keepdims_gpu__test_keepdims_on_the_device_matches_the_host,
)
from test_kendall_gpu import (
    test_kendalltau_on_the_device_matches_the_host as test_kendall_gpu__test_kendalltau_on_the_device_matches_the_host,
)
from test_moments_gpu import (
    test_ptp_average_and_moment_on_the_device as test_moments_gpu__test_ptp_average_and_moment_on_the_device,
)
from test_moments_gpu import (
    test_zscore_on_the_device as test_moments_gpu__test_zscore_on_the_device,
)
from test_nan_gpu import (
    test_select_on_the_device_matches_the_host as test_nan_gpu__test_select_on_the_device_matches_the_host,
)
from test_nan_gpu import (
    test_the_nan_reductions_on_the_device_match_the_host as test_nan_gpu__test_the_nan_reductions_on_the_device_match_the_host,
)
from test_nan_gpu import (
    test_the_broadcasting_select_on_the_device as test_nan_gpu__test_the_broadcasting_select_on_the_device,
)
from test_nanarg_gpu import (
    test_nanarg_on_the_device_matches_the_host as test_nanarg_gpu__test_nanarg_on_the_device_matches_the_host,
)
from test_nanarg_gpu import (
    test_nanarg_all_infinite_on_the_device as test_nanarg_gpu__test_nanarg_all_infinite_on_the_device,
)
from test_order_axis_gpu import (
    test_axis_median_on_the_device_matches_the_host as test_order_axis_gpu__test_axis_median_on_the_device_matches_the_host,
)
from test_order_axis_gpu import (
    test_mode_on_the_device_matches_the_host as test_order_axis_gpu__test_mode_on_the_device_matches_the_host,
)
from test_quantiles_gpu import (
    test_every_method_matches_the_host as test_quantiles_gpu__test_every_method_matches_the_host,
)
from test_quantiles_gpu import (
    test_median_iqr_and_percentiles_match_the_host as test_quantiles_gpu__test_median_iqr_and_percentiles_match_the_host,
)
from test_quantiles_gpu import (
    test_vector_quantiles_match_the_host as test_quantiles_gpu__test_vector_quantiles_match_the_host,
)
from test_quantiles_gpu import (
    test_nan_propagates_on_the_device as test_quantiles_gpu__test_nan_propagates_on_the_device,
)
from test_random_draws_gpu import (
    test_samplers_on_the_device_have_the_right_moments as test_random_draws_gpu__test_samplers_on_the_device_have_the_right_moments,
)
from test_rank_tests_gpu import (
    test_rank_tests_on_the_device_match_the_host as test_rank_tests_gpu__test_rank_tests_on_the_device_match_the_host,
)
from test_ranks_gpu import (
    test_rankdata_on_the_device_matches_the_host as test_ranks_gpu__test_rankdata_on_the_device_matches_the_host,
)
from test_ranks_gpu import (
    test_spearmanr_on_the_device_matches_the_host as test_ranks_gpu__test_spearmanr_on_the_device_matches_the_host,
)
from test_reductions_gpu import (
    test_argmax_along_every_axis_on_the_device as test_reductions_gpu__test_argmax_along_every_axis_on_the_device,
)
from test_reductions_gpu import (
    test_argmin_along_every_axis_on_the_device as test_reductions_gpu__test_argmin_along_every_axis_on_the_device,
)
from test_scan_gpu import (
    test_flat_scans_on_the_device as test_scan_gpu__test_flat_scans_on_the_device,
)
from test_scan_gpu import (
    test_axis_scans_on_the_device as test_scan_gpu__test_axis_scans_on_the_device,
)
from test_scan_gpu import (
    test_cumulative_trapezoid_on_the_device as test_scan_gpu__test_cumulative_trapezoid_on_the_device,
)


def main() raises:
    var suite = TestSuite()
    # tests_gpu/stats/test_correlation_gpu.mojo
    suite.test[
        test_correlation_gpu__test_pearsonr_on_the_device_matches_the_host
    ]()
    suite.test[
        test_correlation_gpu__test_linregress_on_the_device_matches_the_host
    ]()
    # tests_gpu/stats/test_descriptive_gpu.mojo
    suite.test[
        test_descriptive_gpu__test_the_moment_statistics_on_the_device_match_the_host
    ]()
    suite.test[
        test_descriptive_gpu__test_the_means_and_entropies_on_the_device_match_the_host
    ]()
    # tests_gpu/stats/test_extreme_infinities_gpu.mojo
    suite.test[
        test_extreme_infinities_gpu__test_whole_tensor_extremes_on_the_device
    ]()
    suite.test[test_extreme_infinities_gpu__test_axis_extremes_on_the_device]()
    # tests_gpu/stats/test_histograms_gpu.mojo
    suite.test[
        test_histograms_gpu__test_the_one_dimensional_histograms_on_the_device
    ]()
    suite.test[
        test_histograms_gpu__test_the_multi_dimensional_histograms_on_the_device
    ]()
    suite.test[test_histograms_gpu__test_bincount_and_digitize_on_the_device]()
    # tests_gpu/stats/test_hypothesis_gpu.mojo
    suite.test[test_hypothesis_gpu__test_t_tests_on_the_device_match_the_host]()
    suite.test[
        test_hypothesis_gpu__test_chisquare_and_anova_on_the_device_match_the_host
    ]()
    # tests_gpu/stats/test_keepdims_gpu.mojo
    suite.test[
        test_keepdims_gpu__test_keepdims_on_the_device_matches_the_host
    ]()
    # tests_gpu/stats/test_kendall_gpu.mojo
    suite.test[
        test_kendall_gpu__test_kendalltau_on_the_device_matches_the_host
    ]()
    # tests_gpu/stats/test_moments_gpu.mojo
    suite.test[test_moments_gpu__test_ptp_average_and_moment_on_the_device]()
    suite.test[test_moments_gpu__test_zscore_on_the_device]()
    # tests_gpu/stats/test_nan_gpu.mojo
    suite.test[test_nan_gpu__test_select_on_the_device_matches_the_host]()
    suite.test[
        test_nan_gpu__test_the_nan_reductions_on_the_device_match_the_host
    ]()
    suite.test[test_nan_gpu__test_the_broadcasting_select_on_the_device]()
    # tests_gpu/stats/test_nanarg_gpu.mojo
    suite.test[test_nanarg_gpu__test_nanarg_on_the_device_matches_the_host]()
    suite.test[test_nanarg_gpu__test_nanarg_all_infinite_on_the_device]()
    # tests_gpu/stats/test_order_axis_gpu.mojo
    suite.test[
        test_order_axis_gpu__test_axis_median_on_the_device_matches_the_host
    ]()
    suite.test[test_order_axis_gpu__test_mode_on_the_device_matches_the_host]()
    # tests_gpu/stats/test_quantiles_gpu.mojo
    suite.test[test_quantiles_gpu__test_every_method_matches_the_host]()
    suite.test[
        test_quantiles_gpu__test_median_iqr_and_percentiles_match_the_host
    ]()
    suite.test[test_quantiles_gpu__test_vector_quantiles_match_the_host]()
    suite.test[test_quantiles_gpu__test_nan_propagates_on_the_device]()
    # tests_gpu/stats/test_random_draws_gpu.mojo
    suite.test[
        test_random_draws_gpu__test_samplers_on_the_device_have_the_right_moments
    ]()
    # tests_gpu/stats/test_rank_tests_gpu.mojo
    suite.test[
        test_rank_tests_gpu__test_rank_tests_on_the_device_match_the_host
    ]()
    # tests_gpu/stats/test_ranks_gpu.mojo
    suite.test[test_ranks_gpu__test_rankdata_on_the_device_matches_the_host]()
    suite.test[test_ranks_gpu__test_spearmanr_on_the_device_matches_the_host]()
    # tests_gpu/stats/test_reductions_gpu.mojo
    suite.test[
        test_reductions_gpu__test_argmax_along_every_axis_on_the_device
    ]()
    suite.test[
        test_reductions_gpu__test_argmin_along_every_axis_on_the_device
    ]()
    # tests_gpu/stats/test_scan_gpu.mojo
    suite.test[test_scan_gpu__test_flat_scans_on_the_device]()
    suite.test[test_scan_gpu__test_axis_scans_on_the_device]()
    suite.test[test_scan_gpu__test_cumulative_trapezoid_on_the_device]()
    suite^.run()
