"""GENERATED by tools/gen_test_aggregates.py -- do not edit.

Aggregates the 9 test files of `tests_gpu/core/` into one compiled
binary, so 9 compiler invocations become one. Run it with
`mojo -I . -I tests_gpu/core` (see tools/run_test_aggregates.sh).

Regenerate with `pixi run tests-gen`; CI fails if this file is out of date
with the tree.
"""

from std.testing import TestSuite
from test_construct_gpu import (
    test_the_diag_family_on_the_device_matches_the_host as test_construct_gpu__test_the_diag_family_on_the_device_matches_the_host,
)
from test_construct_gpu import (
    test_vander_on_the_device_matches_the_host as test_construct_gpu__test_vander_on_the_device_matches_the_host,
)
from test_construct_gpu import (
    test_meshgrid_on_the_device_matches_the_host as test_construct_gpu__test_meshgrid_on_the_device_matches_the_host,
)
from test_construct_gpu import (
    test_broadcast_to_on_the_device_matches_the_host as test_construct_gpu__test_broadcast_to_on_the_device_matches_the_host,
)
from test_counts_gpu import (
    test_count_nonzero_on_the_device_matches_the_host as test_counts_gpu__test_count_nonzero_on_the_device_matches_the_host,
)
from test_counts_gpu import (
    test_nan_counts_and_negative_zero_does_not as test_counts_gpu__test_nan_counts_and_negative_zero_does_not,
)
from test_counts_gpu import (
    test_all_and_any_of_a_device_mask as test_counts_gpu__test_all_and_any_of_a_device_mask,
)
from test_factories_gpu import (
    test_eye_identity_and_tri_fill_on_the_device as test_factories_gpu__test_eye_identity_and_tri_fill_on_the_device,
)
from test_factories_gpu import (
    test_the_ranges_fill_on_the_device as test_factories_gpu__test_the_ranges_fill_on_the_device,
)
from test_join_split_gpu import (
    test_concatenate_on_the_device_matches_the_host as test_join_split_gpu__test_concatenate_on_the_device_matches_the_host,
)
from test_join_split_gpu import (
    test_stack_on_the_device_matches_the_host as test_join_split_gpu__test_stack_on_the_device_matches_the_host,
)
from test_join_split_gpu import (
    test_split_and_array_split_on_the_device_match_the_host as test_join_split_gpu__test_split_and_array_split_on_the_device_match_the_host,
)
from test_join_split_gpu import (
    test_slice_on_the_device_matches_the_host as test_join_split_gpu__test_slice_on_the_device_matches_the_host,
)
from test_join_split_gpu import (
    test_the_fixed_shape_joins_on_the_device_match_the_host as test_join_split_gpu__test_the_fixed_shape_joins_on_the_device_match_the_host,
)
from test_join_split_gpu import (
    test_the_fixed_shape_and_run_time_splits_on_the_device as test_join_split_gpu__test_the_fixed_shape_and_run_time_splits_on_the_device,
)
from test_operators_gpu import (
    test_the_binary_operators_stay_on_the_device as test_operators_gpu__test_the_binary_operators_stay_on_the_device,
)
from test_operators_gpu import (
    test_the_scalar_and_unary_operators_stay_on_the_device as test_operators_gpu__test_the_scalar_and_unary_operators_stay_on_the_device,
)
from test_reorder_gpu import (
    test_roll_on_the_device_matches_the_host as test_reorder_gpu__test_roll_on_the_device_matches_the_host,
)
from test_reorder_gpu import (
    test_flip_on_the_device_matches_the_host as test_reorder_gpu__test_flip_on_the_device_matches_the_host,
)
from test_reorder_gpu import (
    test_repeat_on_the_device_matches_the_host as test_reorder_gpu__test_repeat_on_the_device_matches_the_host,
)
from test_reorder_gpu import (
    test_tile_on_the_device_matches_the_host as test_reorder_gpu__test_tile_on_the_device_matches_the_host,
)
from test_reorder_gpu import (
    test_rot90_on_the_device_matches_the_host as test_reorder_gpu__test_rot90_on_the_device_matches_the_host,
)
from test_shape_gpu import (
    test_reshape_and_ravel_stay_on_the_device as test_shape_gpu__test_reshape_and_ravel_stay_on_the_device,
)
from test_shape_gpu import (
    test_squeeze_expand_dims_and_atleast_stay_on_the_device as test_shape_gpu__test_squeeze_expand_dims_and_atleast_stay_on_the_device,
)
from test_shape_gpu import (
    test_copy_stays_on_the_device_and_does_not_alias as test_shape_gpu__test_copy_stays_on_the_device_and_does_not_alias,
)
from test_shape_gpu import (
    test_reshape_dyn_refuses_a_wrong_count_on_the_device as test_shape_gpu__test_reshape_dyn_refuses_a_wrong_count_on_the_device,
)
from test_sort_gpu import (
    test_argsort_and_sort_on_the_device_match_the_host as test_sort_gpu__test_argsort_and_sort_on_the_device_match_the_host,
)
from test_sort_gpu import (
    test_partition_argpartition_and_take_on_the_device as test_sort_gpu__test_partition_argpartition_and_take_on_the_device,
)
from test_sort_gpu import (
    test_take_on_the_device_refuses_an_out_of_range_index as test_sort_gpu__test_take_on_the_device_refuses_an_out_of_range_index,
)
from test_sort_gpu import (
    test_ties_and_nan_sort_exactly_as_on_the_host as test_sort_gpu__test_ties_and_nan_sort_exactly_as_on_the_host,
)
from test_surface_gpu import (
    test_exp_on_the_device_matches_the_host as test_surface_gpu__test_exp_on_the_device_matches_the_host,
)
from test_surface_gpu import (
    test_add_on_the_device_matches_the_host as test_surface_gpu__test_add_on_the_device_matches_the_host,
)
from test_surface_gpu import (
    test_sum_and_argmax_on_the_device_match_the_host as test_surface_gpu__test_sum_and_argmax_on_the_device_match_the_host,
)


def main() raises:
    var suite = TestSuite()
    # tests_gpu/core/test_construct_gpu.mojo
    suite.test[
        test_construct_gpu__test_the_diag_family_on_the_device_matches_the_host
    ]()
    suite.test[test_construct_gpu__test_vander_on_the_device_matches_the_host]()
    suite.test[
        test_construct_gpu__test_meshgrid_on_the_device_matches_the_host
    ]()
    suite.test[
        test_construct_gpu__test_broadcast_to_on_the_device_matches_the_host
    ]()
    # tests_gpu/core/test_counts_gpu.mojo
    suite.test[
        test_counts_gpu__test_count_nonzero_on_the_device_matches_the_host
    ]()
    suite.test[test_counts_gpu__test_nan_counts_and_negative_zero_does_not]()
    suite.test[test_counts_gpu__test_all_and_any_of_a_device_mask]()
    # tests_gpu/core/test_factories_gpu.mojo
    suite.test[
        test_factories_gpu__test_eye_identity_and_tri_fill_on_the_device
    ]()
    suite.test[test_factories_gpu__test_the_ranges_fill_on_the_device]()
    # tests_gpu/core/test_join_split_gpu.mojo
    suite.test[
        test_join_split_gpu__test_concatenate_on_the_device_matches_the_host
    ]()
    suite.test[test_join_split_gpu__test_stack_on_the_device_matches_the_host]()
    suite.test[
        test_join_split_gpu__test_split_and_array_split_on_the_device_match_the_host
    ]()
    suite.test[test_join_split_gpu__test_slice_on_the_device_matches_the_host]()
    suite.test[
        test_join_split_gpu__test_the_fixed_shape_joins_on_the_device_match_the_host
    ]()
    suite.test[
        test_join_split_gpu__test_the_fixed_shape_and_run_time_splits_on_the_device
    ]()
    # tests_gpu/core/test_operators_gpu.mojo
    suite.test[
        test_operators_gpu__test_the_binary_operators_stay_on_the_device
    ]()
    suite.test[
        test_operators_gpu__test_the_scalar_and_unary_operators_stay_on_the_device
    ]()
    # tests_gpu/core/test_reorder_gpu.mojo
    suite.test[test_reorder_gpu__test_roll_on_the_device_matches_the_host]()
    suite.test[test_reorder_gpu__test_flip_on_the_device_matches_the_host]()
    suite.test[test_reorder_gpu__test_repeat_on_the_device_matches_the_host]()
    suite.test[test_reorder_gpu__test_tile_on_the_device_matches_the_host]()
    suite.test[test_reorder_gpu__test_rot90_on_the_device_matches_the_host]()
    # tests_gpu/core/test_shape_gpu.mojo
    suite.test[test_shape_gpu__test_reshape_and_ravel_stay_on_the_device]()
    suite.test[
        test_shape_gpu__test_squeeze_expand_dims_and_atleast_stay_on_the_device
    ]()
    suite.test[
        test_shape_gpu__test_copy_stays_on_the_device_and_does_not_alias
    ]()
    suite.test[
        test_shape_gpu__test_reshape_dyn_refuses_a_wrong_count_on_the_device
    ]()
    # tests_gpu/core/test_sort_gpu.mojo
    suite.test[
        test_sort_gpu__test_argsort_and_sort_on_the_device_match_the_host
    ]()
    suite.test[
        test_sort_gpu__test_partition_argpartition_and_take_on_the_device
    ]()
    suite.test[
        test_sort_gpu__test_take_on_the_device_refuses_an_out_of_range_index
    ]()
    suite.test[test_sort_gpu__test_ties_and_nan_sort_exactly_as_on_the_host]()
    # tests_gpu/core/test_surface_gpu.mojo
    suite.test[test_surface_gpu__test_exp_on_the_device_matches_the_host]()
    suite.test[test_surface_gpu__test_add_on_the_device_matches_the_host]()
    suite.test[
        test_surface_gpu__test_sum_and_argmax_on_the_device_match_the_host
    ]()
    suite^.run()
