"""GENERATED by tools/gen_test_aggregates.py -- do not edit.

Aggregates the 1 test files of `tests_gpu/cluster/` into one compiled
binary, so 1 compiler invocations become one. Run it with
`mojo -I . -I tests_gpu/cluster` (see tools/run_test_aggregates.sh).

Regenerate with `pixi run tests-gen`; CI fails if this file is out of date
with the tree.
"""

from std.testing import TestSuite
from test_cluster_gpu import (
    test_cluster_on_the_device_matches_the_host as test_cluster_gpu__test_cluster_on_the_device_matches_the_host,
)


def main() raises:
    var suite = TestSuite()
    # tests_gpu/cluster/test_cluster_gpu.mojo
    suite.test[test_cluster_gpu__test_cluster_on_the_device_matches_the_host]()
    suite^.run()
