"""GENERATED by tools/gen_test_aggregates.py -- do not edit.

Aggregates the 1 test files of `tests_gpu/linalg/` into one compiled
binary, so 1 compiler invocations become one. Run it with
`mojo -I . -I tests_gpu/linalg` (see tools/run_test_aggregates.sh).

Regenerate with `pixi run tests-gen`; CI fails if this file is out of date
with the tree.
"""

from std.testing import TestSuite
from test_linalg_gpu import (
    test_matmul_on_the_device_matches_the_host as test_linalg_gpu__test_matmul_on_the_device_matches_the_host,
)
from test_linalg_gpu import (
    test_cholesky_on_the_device_matches_the_host as test_linalg_gpu__test_cholesky_on_the_device_matches_the_host,
)
from test_linalg_gpu import (
    test_solve_on_the_device_matches_the_host as test_linalg_gpu__test_solve_on_the_device_matches_the_host,
)


def main() raises:
    var suite = TestSuite()
    # tests_gpu/linalg/test_linalg_gpu.mojo
    suite.test[test_linalg_gpu__test_matmul_on_the_device_matches_the_host]()
    suite.test[test_linalg_gpu__test_cholesky_on_the_device_matches_the_host]()
    suite.test[test_linalg_gpu__test_solve_on_the_device_matches_the_host]()
    suite^.run()
