"""GENERATED by tools/gen_test_aggregates.py -- do not edit.

Aggregates the 3 test files of `tests_gpu/linalg/` into one compiled
binary, so 3 compiler invocations become one. Run it with
`mojo -I . -I tests_gpu/linalg` (see tools/run_test_aggregates.sh).

Regenerate with `pixi run tests-gen`; CI fails if this file is out of date
with the tree.
"""

from std.testing import TestSuite
from test_banded_gpu import (
    test_tridiagonal_solve_banded_on_the_device_matches_the_host as test_banded_gpu__test_tridiagonal_solve_banded_on_the_device_matches_the_host,
)
from test_banded_gpu import (
    test_symmetric_tridiagonal_solveh_banded_on_the_device as test_banded_gpu__test_symmetric_tridiagonal_solveh_banded_on_the_device,
)
from test_linalg_gpu import (
    test_matmul_on_the_device_matches_the_host as test_linalg_gpu__test_matmul_on_the_device_matches_the_host,
)
from test_linalg_gpu import (
    test_cholesky_on_the_device_matches_the_host as test_linalg_gpu__test_cholesky_on_the_device_matches_the_host,
)
from test_linalg_gpu import (
    test_solve_on_the_device_matches_the_host as test_linalg_gpu__test_solve_on_the_device_matches_the_host,
)
from test_linalg_gpu import (
    test_the_extremal_norms_on_the_device_match_the_host as test_linalg_gpu__test_the_extremal_norms_on_the_device_match_the_host,
)
from test_linalg_gpu import (
    test_rq_on_the_device_matches_the_host as test_linalg_gpu__test_rq_on_the_device_matches_the_host,
)
from test_spectral_gpu import (
    test_eigvalsh_on_the_device_matches_the_host as test_spectral_gpu__test_eigvalsh_on_the_device_matches_the_host,
)
from test_spectral_gpu import (
    test_eigh_on_the_device_reconstructs_its_matrix as test_spectral_gpu__test_eigh_on_the_device_reconstructs_its_matrix,
)
from test_spectral_gpu import (
    test_svd_on_the_device_reconstructs_its_matrix as test_spectral_gpu__test_svd_on_the_device_reconstructs_its_matrix,
)
from test_spectral_gpu import (
    test_schur_on_the_device_reconstructs_its_matrix as test_spectral_gpu__test_schur_on_the_device_reconstructs_its_matrix,
)
from test_spectral_gpu import (
    test_eigvals_on_the_device_matches_the_host as test_spectral_gpu__test_eigvals_on_the_device_matches_the_host,
)
from test_spectral_gpu import (
    test_the_svd_dependents_on_the_device_match_the_host as test_spectral_gpu__test_the_svd_dependents_on_the_device_match_the_host,
)
from test_spectral_gpu import (
    test_the_matrix_functions_on_the_device_match_the_host as test_spectral_gpu__test_the_matrix_functions_on_the_device_match_the_host,
)
from test_spectral_gpu import (
    test_roots_on_the_device_finds_the_host_roots as test_spectral_gpu__test_roots_on_the_device_finds_the_host_roots,
)
from test_spectral_gpu import (
    test_null_space_on_the_device_is_a_null_space as test_spectral_gpu__test_null_space_on_the_device_is_a_null_space,
)


def main() raises:
    var suite = TestSuite()
    # tests_gpu/linalg/test_banded_gpu.mojo
    suite.test[
        test_banded_gpu__test_tridiagonal_solve_banded_on_the_device_matches_the_host
    ]()
    suite.test[
        test_banded_gpu__test_symmetric_tridiagonal_solveh_banded_on_the_device
    ]()
    # tests_gpu/linalg/test_linalg_gpu.mojo
    suite.test[test_linalg_gpu__test_matmul_on_the_device_matches_the_host]()
    suite.test[test_linalg_gpu__test_cholesky_on_the_device_matches_the_host]()
    suite.test[test_linalg_gpu__test_solve_on_the_device_matches_the_host]()
    suite.test[
        test_linalg_gpu__test_the_extremal_norms_on_the_device_match_the_host
    ]()
    suite.test[test_linalg_gpu__test_rq_on_the_device_matches_the_host]()
    # tests_gpu/linalg/test_spectral_gpu.mojo
    suite.test[
        test_spectral_gpu__test_eigvalsh_on_the_device_matches_the_host
    ]()
    suite.test[
        test_spectral_gpu__test_eigh_on_the_device_reconstructs_its_matrix
    ]()
    suite.test[
        test_spectral_gpu__test_svd_on_the_device_reconstructs_its_matrix
    ]()
    suite.test[
        test_spectral_gpu__test_schur_on_the_device_reconstructs_its_matrix
    ]()
    suite.test[test_spectral_gpu__test_eigvals_on_the_device_matches_the_host]()
    suite.test[
        test_spectral_gpu__test_the_svd_dependents_on_the_device_match_the_host
    ]()
    suite.test[
        test_spectral_gpu__test_the_matrix_functions_on_the_device_match_the_host
    ]()
    suite.test[
        test_spectral_gpu__test_roots_on_the_device_finds_the_host_roots
    ]()
    suite.test[
        test_spectral_gpu__test_null_space_on_the_device_is_a_null_space
    ]()
    suite^.run()
