"""GENERATED by tools/gen_test_aggregates.py -- do not edit.

Aggregates the 4 test files of `tests_gpu/interpolate/` into one compiled
binary, so 4 compiler invocations become one. Run it with
`mojo -I . -I tests_gpu/interpolate` (see tools/run_test_aggregates.sh).

Regenerate with `pixi run tests-gen`; CI fails if this file is out of date
with the tree.
"""

from std.testing import TestSuite
from test_bspline_gpu import (
    test_bspline_on_the_device_matches_the_host as test_bspline_gpu__test_bspline_on_the_device_matches_the_host,
)
from test_interpn_gpu import (
    test_interpn_on_the_device_matches_the_host as test_interpn_gpu__test_interpn_on_the_device_matches_the_host,
)
from test_poly_gpu import (
    test_polyder_on_the_device_matches_the_host as test_poly_gpu__test_polyder_on_the_device_matches_the_host,
)
from test_poly_gpu import (
    test_polyint_on_the_device_matches_the_host as test_poly_gpu__test_polyint_on_the_device_matches_the_host,
)
from test_splines_gpu import (
    test_cubic_spline_builds_on_the_device as test_splines_gpu__test_cubic_spline_builds_on_the_device,
)
from test_splines_gpu import (
    test_small_cubic_splines_build_from_device_knots as test_splines_gpu__test_small_cubic_splines_build_from_device_knots,
)
from test_splines_gpu import (
    test_pchip_builds_on_the_device as test_splines_gpu__test_pchip_builds_on_the_device,
)
from test_splines_gpu import (
    test_akima_builds_on_the_device as test_splines_gpu__test_akima_builds_on_the_device,
)
from test_splines_gpu import (
    test_hermite_builds_on_the_device as test_splines_gpu__test_hermite_builds_on_the_device,
)


def main() raises:
    var suite = TestSuite()
    # tests_gpu/interpolate/test_bspline_gpu.mojo
    suite.test[test_bspline_gpu__test_bspline_on_the_device_matches_the_host]()
    # tests_gpu/interpolate/test_interpn_gpu.mojo
    suite.test[test_interpn_gpu__test_interpn_on_the_device_matches_the_host]()
    # tests_gpu/interpolate/test_poly_gpu.mojo
    suite.test[test_poly_gpu__test_polyder_on_the_device_matches_the_host]()
    suite.test[test_poly_gpu__test_polyint_on_the_device_matches_the_host]()
    # tests_gpu/interpolate/test_splines_gpu.mojo
    suite.test[test_splines_gpu__test_cubic_spline_builds_on_the_device]()
    suite.test[
        test_splines_gpu__test_small_cubic_splines_build_from_device_knots
    ]()
    suite.test[test_splines_gpu__test_pchip_builds_on_the_device]()
    suite.test[test_splines_gpu__test_akima_builds_on_the_device]()
    suite.test[test_splines_gpu__test_hermite_builds_on_the_device]()
    suite^.run()
