"""GENERATED by tools/gen_test_aggregates.py -- do not edit.

Aggregates the 2 test files of `tests_gpu/optimize/` into one compiled
binary, so 2 compiler invocations become one. Run it with
`mojo -I . -I tests_gpu/optimize` (see tools/run_test_aggregates.sh).

Regenerate with `pixi run tests-gen`; CI fails if this file is out of date
with the tree.
"""

from std.testing import TestSuite
from test_array_drivers_gpu import (
    test_array_drivers_run_inside_a_device_kernel as test_array_drivers_gpu__test_array_drivers_run_inside_a_device_kernel,
)
from test_fits_gpu import (
    test_least_squares_on_the_device as test_fits_gpu__test_least_squares_on_the_device,
)
from test_fits_gpu import (
    test_curve_fit_on_the_device_recovers_the_parameters as test_fits_gpu__test_curve_fit_on_the_device_recovers_the_parameters,
)


def main() raises:
    var suite = TestSuite()
    # tests_gpu/optimize/test_array_drivers_gpu.mojo
    suite.test[
        test_array_drivers_gpu__test_array_drivers_run_inside_a_device_kernel
    ]()
    # tests_gpu/optimize/test_fits_gpu.mojo
    suite.test[test_fits_gpu__test_least_squares_on_the_device]()
    suite.test[
        test_fits_gpu__test_curve_fit_on_the_device_recovers_the_parameters
    ]()
    suite^.run()
