"""GENERATED by tools/gen_test_aggregates.py -- do not edit.

Aggregates the 1 test files of `tests_gpu/spatial/` into one compiled
binary, so 1 compiler invocations become one. Run it with
`mojo -I . -I tests_gpu/spatial` (see tools/run_test_aggregates.sh).

Regenerate with `pixi run tests-gen`; CI fails if this file is out of date
with the tree.
"""

from std.testing import TestSuite
from test_distance_gpu import (
    test_distances_on_the_device_match_the_host as test_distance_gpu__test_distances_on_the_device_match_the_host,
)


def main() raises:
    var suite = TestSuite()
    # tests_gpu/spatial/test_distance_gpu.mojo
    suite.test[test_distance_gpu__test_distances_on_the_device_match_the_host]()
    suite^.run()
