"""GENERATED by tools/gen_test_aggregates.py -- do not edit.

Aggregates the 2 test files of `tests_gpu/core/` into one compiled
binary, so 2 compiler invocations become one. Run it with
`mojo -I . -I tests_gpu/core` (see tools/run_test_aggregates.sh).

Regenerate with `pixi run tests-gen`; CI fails if this file is out of date
with the tree.
"""

from std.testing import TestSuite
from test_shape_gpu import (
    test_reshape_and_ravel_stay_on_the_device as test_shape_gpu__test_reshape_and_ravel_stay_on_the_device,
)
from test_shape_gpu import (
    test_squeeze_expand_dims_and_atleast_stay_on_the_device as test_shape_gpu__test_squeeze_expand_dims_and_atleast_stay_on_the_device,
)
from test_shape_gpu import (
    test_copy_stays_on_the_device_and_does_not_alias as test_shape_gpu__test_copy_stays_on_the_device_and_does_not_alias,
)
from test_shape_gpu import (
    test_reshape_dyn_refuses_a_wrong_count_on_the_device as test_shape_gpu__test_reshape_dyn_refuses_a_wrong_count_on_the_device,
)
from test_surface_gpu import (
    test_exp_on_the_device_matches_the_host as test_surface_gpu__test_exp_on_the_device_matches_the_host,
)
from test_surface_gpu import (
    test_add_on_the_device_matches_the_host as test_surface_gpu__test_add_on_the_device_matches_the_host,
)
from test_surface_gpu import (
    test_sum_and_argmax_on_the_device_match_the_host as test_surface_gpu__test_sum_and_argmax_on_the_device_match_the_host,
)


def main() raises:
    var suite = TestSuite()
    # tests_gpu/core/test_shape_gpu.mojo
    suite.test[test_shape_gpu__test_reshape_and_ravel_stay_on_the_device]()
    suite.test[
        test_shape_gpu__test_squeeze_expand_dims_and_atleast_stay_on_the_device
    ]()
    suite.test[
        test_shape_gpu__test_copy_stays_on_the_device_and_does_not_alias
    ]()
    suite.test[
        test_shape_gpu__test_reshape_dyn_refuses_a_wrong_count_on_the_device
    ]()
    # tests_gpu/core/test_surface_gpu.mojo
    suite.test[test_surface_gpu__test_exp_on_the_device_matches_the_host]()
    suite.test[test_surface_gpu__test_add_on_the_device_matches_the_host]()
    suite.test[
        test_surface_gpu__test_sum_and_argmax_on_the_device_match_the_host
    ]()
    suite^.run()
