"""GENERATED by tools/gen_test_aggregates.py -- do not edit.

Aggregates the 7 test files of `tests_gpu/special/` into one compiled
binary, so 7 compiler invocations become one. Run it with
`mojo -I . -I tests_gpu/special` (see tools/run_test_aggregates.sh).

Regenerate with `pixi run tests-gen`; CI fails if this file is out of date
with the tree.
"""

from std.testing import TestSuite
from test_elliptic_incomplete_gpu import (
    test_incomplete_elliptic_on_the_device_matches_the_host as test_elliptic_incomplete_gpu__test_incomplete_elliptic_on_the_device_matches_the_host,
)
from test_gamma_gpu import (
    test_gamma_at_the_integers_on_the_device as test_gamma_gpu__test_gamma_at_the_integers_on_the_device,
)
from test_incomplete_inverse_gpu import (
    test_inverses_on_the_device_match_the_host as test_incomplete_inverse_gpu__test_inverses_on_the_device_match_the_host,
)
from test_normal_gpu import (
    test_normal_family_on_the_device_matches_the_host as test_normal_gpu__test_normal_family_on_the_device_matches_the_host,
)
from test_polygamma_gpu import (
    test_polygamma_on_the_device_matches_the_host as test_polygamma_gpu__test_polygamma_on_the_device_matches_the_host,
)
from test_softmax_gpu import (
    test_softmax_on_the_device_matches_the_host as test_softmax_gpu__test_softmax_on_the_device_matches_the_host,
)
from test_wofz_gpu import (
    test_wofz_on_the_device_matches_the_host as test_wofz_gpu__test_wofz_on_the_device_matches_the_host,
)


def main() raises:
    var suite = TestSuite()
    # tests_gpu/special/test_elliptic_incomplete_gpu.mojo
    suite.test[
        test_elliptic_incomplete_gpu__test_incomplete_elliptic_on_the_device_matches_the_host
    ]()
    # tests_gpu/special/test_gamma_gpu.mojo
    suite.test[test_gamma_gpu__test_gamma_at_the_integers_on_the_device]()
    # tests_gpu/special/test_incomplete_inverse_gpu.mojo
    suite.test[
        test_incomplete_inverse_gpu__test_inverses_on_the_device_match_the_host
    ]()
    # tests_gpu/special/test_normal_gpu.mojo
    suite.test[
        test_normal_gpu__test_normal_family_on_the_device_matches_the_host
    ]()
    # tests_gpu/special/test_polygamma_gpu.mojo
    suite.test[
        test_polygamma_gpu__test_polygamma_on_the_device_matches_the_host
    ]()
    # tests_gpu/special/test_softmax_gpu.mojo
    suite.test[test_softmax_gpu__test_softmax_on_the_device_matches_the_host]()
    # tests_gpu/special/test_wofz_gpu.mojo
    suite.test[test_wofz_gpu__test_wofz_on_the_device_matches_the_host]()
    suite^.run()
