"""GENERATED by tools/gen_test_aggregates.py -- do not edit.

Aggregates the 2 test files of `tests_gpu/linalg/` into one compiled
binary, so 2 compiler invocations become one. Run it with
`mojo -I . -I tests_gpu/linalg` (see tools/run_test_aggregates.sh).

Regenerate with `pixi run tests-gen`; CI fails if this file is out of date
with the tree.
"""

from std.testing import TestSuite
from test_ldl_gpu import (
    test_ldl_on_the_device_matches_the_host as test_ldl_gpu__test_ldl_on_the_device_matches_the_host,
)
from test_solvers_gpu import (
    test_solvers_on_the_device_match_the_host as test_solvers_gpu__test_solvers_on_the_device_match_the_host,
)
from test_solvers_gpu import (
    test_care_on_the_device_matches_the_host as test_solvers_gpu__test_care_on_the_device_matches_the_host,
)


def main() raises:
    var suite = TestSuite()
    # tests_gpu/linalg/test_ldl_gpu.mojo
    suite.test[test_ldl_gpu__test_ldl_on_the_device_matches_the_host]()
    # tests_gpu/linalg/test_solvers_gpu.mojo
    suite.test[test_solvers_gpu__test_solvers_on_the_device_match_the_host]()
    suite.test[test_solvers_gpu__test_care_on_the_device_matches_the_host]()
    suite^.run()
