"""GENERATED by tools/gen_test_aggregates.py -- do not edit.

Aggregates the 1 test files of `tests_gpu/ndimage/` into one compiled
binary, so 1 compiler invocations become one. Run it with
`mojo -I . -I tests_gpu/ndimage` (see tools/run_test_aggregates.sh).

Regenerate with `pixi run tests-gen`; CI fails if this file is out of date
with the tree.
"""

from std.testing import TestSuite
from test_filters_gpu import (
    test_filters_on_the_device_match_the_host as test_filters_gpu__test_filters_on_the_device_match_the_host,
)


def main() raises:
    var suite = TestSuite()
    # tests_gpu/ndimage/test_filters_gpu.mojo
    suite.test[test_filters_gpu__test_filters_on_the_device_match_the_host]()
    suite^.run()
