"""GENERATED by tools/gen_test_aggregates.py -- do not edit.

Aggregates the 10 test files of `tests_gpu/signal/` into one compiled
binary, so 10 compiler invocations become one. Run it with
`mojo -I . -I tests_gpu/signal` (see tools/run_test_aggregates.sh).

Regenerate with `pixi run tests-gen`; CI fails if this file is out of date
with the tree.
"""

from std.testing import TestSuite
from test_filters_gpu import (
    test_lfilter_on_the_device_matches_the_host as test_filters_gpu__test_lfilter_on_the_device_matches_the_host,
)
from test_filters_gpu import (
    test_filtfilt_on_the_device_matches_the_host as test_filters_gpu__test_filtfilt_on_the_device_matches_the_host,
)
from test_filters_gpu import (
    test_sosfilt_and_decimate_on_the_device_match_the_host as test_filters_gpu__test_sosfilt_and_decimate_on_the_device_match_the_host,
)
from test_group_delay_gpu import (
    test_group_delay_on_the_device_matches_the_host as test_group_delay_gpu__test_group_delay_on_the_device_matches_the_host,
)
from test_lfilter_zi_gpu import (
    test_lfilter_with_zi_on_the_device_matches_the_host as test_lfilter_zi_gpu__test_lfilter_with_zi_on_the_device_matches_the_host,
)
from test_more_windows_gpu import (
    test_window_fills_on_the_device_match_the_host as test_more_windows_gpu__test_window_fills_on_the_device_match_the_host,
)
from test_peaks_gpu import (
    test_find_peaks_on_the_device_matches_the_host as test_peaks_gpu__test_find_peaks_on_the_device_matches_the_host,
)
from test_peaks_gpu import (
    test_peak_prominences_on_the_device_matches_the_host as test_peaks_gpu__test_peak_prominences_on_the_device_matches_the_host,
)
from test_sos_gpu import (
    test_sosfiltfilt_on_the_device_matches_the_host as test_sos_gpu__test_sosfiltfilt_on_the_device_matches_the_host,
)
from test_sos_gpu import (
    test_sosfreqz_on_the_device_matches_the_host as test_sos_gpu__test_sosfreqz_on_the_device_matches_the_host,
)
from test_spectral_tails_gpu import (
    test_resample_down_and_up_on_the_device as test_spectral_tails_gpu__test_resample_down_and_up_on_the_device,
)
from test_spectral_tails_gpu import (
    test_hilbert_on_the_device as test_spectral_tails_gpu__test_hilbert_on_the_device,
)
from test_spectral_tails_gpu import (
    test_solve_circulant_on_the_device as test_spectral_tails_gpu__test_solve_circulant_on_the_device,
)
from test_spectral_tails_gpu import (
    test_istft_round_trips_on_the_device as test_spectral_tails_gpu__test_istft_round_trips_on_the_device,
)
from test_spectral_tails_gpu import (
    test_savgol_interp_on_the_device as test_spectral_tails_gpu__test_savgol_interp_on_the_device,
)
from test_upfirdn_gpu import (
    test_upfirdn_and_resample_poly_on_the_device as test_upfirdn_gpu__test_upfirdn_and_resample_poly_on_the_device,
)
from test_waveforms_gpu import (
    test_waveforms_on_the_device_match_the_host as test_waveforms_gpu__test_waveforms_on_the_device_match_the_host,
)
from test_windows_gpu import (
    test_windows_fill_on_the_device as test_windows_gpu__test_windows_fill_on_the_device,
)
from test_windows_gpu import (
    test_frequency_grids_fill_on_the_device as test_windows_gpu__test_frequency_grids_fill_on_the_device,
)


def main() raises:
    var suite = TestSuite()
    # tests_gpu/signal/test_filters_gpu.mojo
    suite.test[test_filters_gpu__test_lfilter_on_the_device_matches_the_host]()
    suite.test[test_filters_gpu__test_filtfilt_on_the_device_matches_the_host]()
    suite.test[
        test_filters_gpu__test_sosfilt_and_decimate_on_the_device_match_the_host
    ]()
    # tests_gpu/signal/test_group_delay_gpu.mojo
    suite.test[
        test_group_delay_gpu__test_group_delay_on_the_device_matches_the_host
    ]()
    # tests_gpu/signal/test_lfilter_zi_gpu.mojo
    suite.test[
        test_lfilter_zi_gpu__test_lfilter_with_zi_on_the_device_matches_the_host
    ]()
    # tests_gpu/signal/test_more_windows_gpu.mojo
    suite.test[
        test_more_windows_gpu__test_window_fills_on_the_device_match_the_host
    ]()
    # tests_gpu/signal/test_peaks_gpu.mojo
    suite.test[test_peaks_gpu__test_find_peaks_on_the_device_matches_the_host]()
    suite.test[
        test_peaks_gpu__test_peak_prominences_on_the_device_matches_the_host
    ]()
    # tests_gpu/signal/test_sos_gpu.mojo
    suite.test[test_sos_gpu__test_sosfiltfilt_on_the_device_matches_the_host]()
    suite.test[test_sos_gpu__test_sosfreqz_on_the_device_matches_the_host]()
    # tests_gpu/signal/test_spectral_tails_gpu.mojo
    suite.test[
        test_spectral_tails_gpu__test_resample_down_and_up_on_the_device
    ]()
    suite.test[test_spectral_tails_gpu__test_hilbert_on_the_device]()
    suite.test[test_spectral_tails_gpu__test_solve_circulant_on_the_device]()
    suite.test[test_spectral_tails_gpu__test_istft_round_trips_on_the_device]()
    suite.test[test_spectral_tails_gpu__test_savgol_interp_on_the_device]()
    # tests_gpu/signal/test_upfirdn_gpu.mojo
    suite.test[test_upfirdn_gpu__test_upfirdn_and_resample_poly_on_the_device]()
    # tests_gpu/signal/test_waveforms_gpu.mojo
    suite.test[
        test_waveforms_gpu__test_waveforms_on_the_device_match_the_host
    ]()
    # tests_gpu/signal/test_windows_gpu.mojo
    suite.test[test_windows_gpu__test_windows_fill_on_the_device]()
    suite.test[test_windows_gpu__test_frequency_grids_fill_on_the_device]()
    suite^.run()
