"""GENERATED by tools/gen_test_aggregates.py -- do not edit.

Aggregates the 4 test files of `tests_gpu/optimize/` into one compiled
binary, so 4 compiler invocations become one. Run it with
`mojo -I . -I tests_gpu/optimize` (see tools/run_test_aggregates.sh).

Regenerate with `pixi run tests-gen`; CI fails if this file is out of date
with the tree.
"""

from std.testing import TestSuite
from test_array_drivers_gpu import (
    test_array_drivers_run_inside_a_device_kernel as test_array_drivers_gpu__test_array_drivers_run_inside_a_device_kernel,
)
from test_fits_gpu import (
    test_least_squares_on_the_device as test_fits_gpu__test_least_squares_on_the_device,
)
from test_fits_gpu import (
    test_curve_fit_on_the_device_recovers_the_parameters as test_fits_gpu__test_curve_fit_on_the_device_recovers_the_parameters,
)
from test_linprog_gpu import (
    test_linprog_gpu_matches_host as test_linprog_gpu__test_linprog_gpu_matches_host,
)
from test_linprog_gpu import (
    test_milp_gpu_knapsack as test_linprog_gpu__test_milp_gpu_knapsack,
)
from test_slsqp_gpu import (
    test_hs071_on_device as test_slsqp_gpu__test_hs071_on_device,
)


def main() raises:
    var suite = TestSuite()
    # tests_gpu/optimize/test_array_drivers_gpu.mojo
    suite.test[
        test_array_drivers_gpu__test_array_drivers_run_inside_a_device_kernel
    ]()
    # tests_gpu/optimize/test_fits_gpu.mojo
    suite.test[test_fits_gpu__test_least_squares_on_the_device]()
    suite.test[
        test_fits_gpu__test_curve_fit_on_the_device_recovers_the_parameters
    ]()
    # tests_gpu/optimize/test_linprog_gpu.mojo
    suite.test[test_linprog_gpu__test_linprog_gpu_matches_host]()
    suite.test[test_linprog_gpu__test_milp_gpu_knapsack]()
    # tests_gpu/optimize/test_slsqp_gpu.mojo
    suite.test[test_slsqp_gpu__test_hs071_on_device]()
    suite^.run()
