"""GENERATED by tools/gen_test_aggregates.py -- do not edit.

Aggregates the 3 test files of `tests_gpu/linalg/` into one compiled
binary, so 3 compiler invocations become one. Run it with
`mojo -I . -I tests_gpu/linalg` (see tools/run_test_aggregates.sh).

Regenerate with `pixi run tests-gen`; CI fails if this file is out of date
with the tree.
"""

from std.testing import TestSuite
from test_dynamic_lu_gpu import (
    test_dynamic_solve_gpu_matches_host as test_dynamic_lu_gpu__test_dynamic_solve_gpu_matches_host,
)
from test_dynamic_lu_gpu import (
    test_dynamic_cholesky_gpu_matches_host as test_dynamic_lu_gpu__test_dynamic_cholesky_gpu_matches_host,
)
from test_dynamic_lu_gpu import (
    test_dynamic_lstsq_gpu_matches_host as test_dynamic_lu_gpu__test_dynamic_lstsq_gpu_matches_host,
)
from test_lu_plu_gpu import (
    test_lu_on_the_device_matches_the_host as test_lu_plu_gpu__test_lu_on_the_device_matches_the_host,
)
from test_multishift_gpu import (
    test_schur_gpu_reconstructs as test_multishift_gpu__test_schur_gpu_reconstructs,
)
from test_multishift_gpu import (
    test_eigvals_gpu_matches_host as test_multishift_gpu__test_eigvals_gpu_matches_host,
)


def main() raises:
    var suite = TestSuite()
    # tests_gpu/linalg/test_dynamic_lu_gpu.mojo
    suite.test[test_dynamic_lu_gpu__test_dynamic_solve_gpu_matches_host]()
    suite.test[test_dynamic_lu_gpu__test_dynamic_cholesky_gpu_matches_host]()
    suite.test[test_dynamic_lu_gpu__test_dynamic_lstsq_gpu_matches_host]()
    # tests_gpu/linalg/test_lu_plu_gpu.mojo
    suite.test[test_lu_plu_gpu__test_lu_on_the_device_matches_the_host]()
    # tests_gpu/linalg/test_multishift_gpu.mojo
    suite.test[test_multishift_gpu__test_schur_gpu_reconstructs]()
    suite.test[test_multishift_gpu__test_eigvals_gpu_matches_host]()
    suite^.run()
