"""GENERATED by tools/gen_test_aggregates.py -- do not edit.

Aggregates the 3 test files of `tests_gpu/integrate/` into one compiled
binary, so 3 compiler invocations become one. Run it with
`mojo -I . -I tests_gpu/integrate` (see tools/run_test_aggregates.sh).

Regenerate with `pixi run tests-gen`; CI fails if this file is out of date
with the tree.
"""

from std.testing import TestSuite
from test_cumulative_simpson_romb_gpu import (
    test_on_the_device_matches_the_host as test_cumulative_simpson_romb_gpu__test_on_the_device_matches_the_host,
)
from test_ivp_gpu import (
    test_solve_ivp_on_the_device as test_ivp_gpu__test_solve_ivp_on_the_device,
)
from test_sampled_gpu import (
    test_odd_count_on_the_device as test_sampled_gpu__test_odd_count_on_the_device,
)
from test_sampled_gpu import (
    test_even_count_on_the_device as test_sampled_gpu__test_even_count_on_the_device,
)


def main() raises:
    var suite = TestSuite()
    # tests_gpu/integrate/test_cumulative_simpson_romb_gpu.mojo
    suite.test[
        test_cumulative_simpson_romb_gpu__test_on_the_device_matches_the_host
    ]()
    # tests_gpu/integrate/test_ivp_gpu.mojo
    suite.test[test_ivp_gpu__test_solve_ivp_on_the_device]()
    # tests_gpu/integrate/test_sampled_gpu.mojo
    suite.test[test_sampled_gpu__test_odd_count_on_the_device]()
    suite.test[test_sampled_gpu__test_even_count_on_the_device]()
    suite^.run()
