"""GENERATED by tools/gen_test_aggregates.py -- do not edit.

Aggregates the 4 test files of `tests_gpu/stats/` into one compiled
binary, so 4 compiler invocations become one. Run it with
`mojo -I . -I tests_gpu/stats` (see tools/run_test_aggregates.sh).

Regenerate with `pixi run tests-gen`; CI fails if this file is out of date
with the tree.
"""

from std.testing import TestSuite
from test_descriptive_gpu import (
    test_the_moment_statistics_on_the_device_match_the_host as test_descriptive_gpu__test_the_moment_statistics_on_the_device_match_the_host,
)
from test_descriptive_gpu import (
    test_the_means_and_entropies_on_the_device_match_the_host as test_descriptive_gpu__test_the_means_and_entropies_on_the_device_match_the_host,
)
from test_moments_gpu import (
    test_ptp_average_and_moment_on_the_device as test_moments_gpu__test_ptp_average_and_moment_on_the_device,
)
from test_moments_gpu import (
    test_zscore_on_the_device as test_moments_gpu__test_zscore_on_the_device,
)
from test_nan_gpu import (
    test_select_on_the_device_matches_the_host as test_nan_gpu__test_select_on_the_device_matches_the_host,
)
from test_nan_gpu import (
    test_the_nan_reductions_on_the_device_match_the_host as test_nan_gpu__test_the_nan_reductions_on_the_device_match_the_host,
)
from test_nan_gpu import (
    test_the_broadcasting_select_on_the_device as test_nan_gpu__test_the_broadcasting_select_on_the_device,
)
from test_reductions_gpu import (
    test_argmax_along_every_axis_on_the_device as test_reductions_gpu__test_argmax_along_every_axis_on_the_device,
)
from test_reductions_gpu import (
    test_argmin_along_every_axis_on_the_device as test_reductions_gpu__test_argmin_along_every_axis_on_the_device,
)


def main() raises:
    var suite = TestSuite()
    # tests_gpu/stats/test_descriptive_gpu.mojo
    suite.test[
        test_descriptive_gpu__test_the_moment_statistics_on_the_device_match_the_host
    ]()
    suite.test[
        test_descriptive_gpu__test_the_means_and_entropies_on_the_device_match_the_host
    ]()
    # tests_gpu/stats/test_moments_gpu.mojo
    suite.test[test_moments_gpu__test_ptp_average_and_moment_on_the_device]()
    suite.test[test_moments_gpu__test_zscore_on_the_device]()
    # tests_gpu/stats/test_nan_gpu.mojo
    suite.test[test_nan_gpu__test_select_on_the_device_matches_the_host]()
    suite.test[
        test_nan_gpu__test_the_nan_reductions_on_the_device_match_the_host
    ]()
    suite.test[test_nan_gpu__test_the_broadcasting_select_on_the_device]()
    # tests_gpu/stats/test_reductions_gpu.mojo
    suite.test[
        test_reductions_gpu__test_argmax_along_every_axis_on_the_device
    ]()
    suite.test[
        test_reductions_gpu__test_argmin_along_every_axis_on_the_device
    ]()
    suite^.run()
