"""GENERATED by tools/gen_test_aggregates.py -- do not edit.

Aggregates the 1 test files of `tests_gpu/signal/` into one compiled
binary, so 1 compiler invocations become one. Run it with
`mojo -I . -I tests_gpu/signal` (see tools/run_test_aggregates.sh).

Regenerate with `pixi run tests-gen`; CI fails if this file is out of date
with the tree.
"""

from std.testing import TestSuite
from test_peaks_gpu import (
    test_find_peaks_on_the_device_matches_the_host as test_peaks_gpu__test_find_peaks_on_the_device_matches_the_host,
)
from test_peaks_gpu import (
    test_peak_prominences_on_the_device_matches_the_host as test_peaks_gpu__test_peak_prominences_on_the_device_matches_the_host,
)


def main() raises:
    var suite = TestSuite()
    # tests_gpu/signal/test_peaks_gpu.mojo
    suite.test[test_peaks_gpu__test_find_peaks_on_the_device_matches_the_host]()
    suite.test[
        test_peaks_gpu__test_peak_prominences_on_the_device_matches_the_host
    ]()
    suite^.run()
