"""GENERATED by tools/gen_test_aggregates.py -- do not edit.

Aggregates the 3 test files of `tests_gpu/linalg/` into one compiled
binary, so 3 compiler invocations become one. Run it with
`mojo -I . -I tests_gpu/linalg` (see tools/run_test_aggregates.sh).

Regenerate with `pixi run tests-gen`; CI fails if this file is out of date
with the tree.
"""

from std.testing import TestSuite
from test_banded_gpu import (
    test_tridiagonal_solve_banded_on_the_device_matches_the_host as test_banded_gpu__test_tridiagonal_solve_banded_on_the_device_matches_the_host,
)
from test_banded_gpu import (
    test_symmetric_tridiagonal_solveh_banded_on_the_device as test_banded_gpu__test_symmetric_tridiagonal_solveh_banded_on_the_device,
)
from test_dynamic_eigen_gpu import (
    test_dynamic_eigh_gpu_matches_host as test_dynamic_eigen_gpu__test_dynamic_eigh_gpu_matches_host,
)
from test_dynamic_eigen_gpu import (
    test_dynamic_svd_gpu_matches_host as test_dynamic_eigen_gpu__test_dynamic_svd_gpu_matches_host,
)
from test_dynamic_eigen_gpu import (
    test_dynamic_schur_gpu_matches_host as test_dynamic_eigen_gpu__test_dynamic_schur_gpu_matches_host,
)
from test_twostage_gpu import (
    test_eigvalsh_two_stage_gpu as test_twostage_gpu__test_eigvalsh_two_stage_gpu,
)
from test_twostage_gpu import (
    test_svdvals_two_stage_gpu as test_twostage_gpu__test_svdvals_two_stage_gpu,
)


def main() raises:
    var suite = TestSuite()
    # tests_gpu/linalg/test_banded_gpu.mojo
    suite.test[
        test_banded_gpu__test_tridiagonal_solve_banded_on_the_device_matches_the_host
    ]()
    suite.test[
        test_banded_gpu__test_symmetric_tridiagonal_solveh_banded_on_the_device
    ]()
    # tests_gpu/linalg/test_dynamic_eigen_gpu.mojo
    suite.test[test_dynamic_eigen_gpu__test_dynamic_eigh_gpu_matches_host]()
    suite.test[test_dynamic_eigen_gpu__test_dynamic_svd_gpu_matches_host]()
    suite.test[test_dynamic_eigen_gpu__test_dynamic_schur_gpu_matches_host]()
    # tests_gpu/linalg/test_twostage_gpu.mojo
    suite.test[test_twostage_gpu__test_eigvalsh_two_stage_gpu]()
    suite.test[test_twostage_gpu__test_svdvals_two_stage_gpu]()
    suite^.run()
