"""GENERATED by tools/gen_test_aggregates.py -- do not edit.

Aggregates the 1 test files of `tests_gpu/stats/` into one compiled
binary, so 1 compiler invocations become one. Run it with
`mojo -I . -I tests_gpu/stats` (see tools/run_test_aggregates.sh).

Regenerate with `pixi run tests-gen`; CI fails if this file is out of date
with the tree.
"""

from std.testing import TestSuite
from test_reductions_gpu import (
    test_argmax_along_every_axis_on_the_device as test_reductions_gpu__test_argmax_along_every_axis_on_the_device,
)
from test_reductions_gpu import (
    test_argmin_along_every_axis_on_the_device as test_reductions_gpu__test_argmin_along_every_axis_on_the_device,
)


def main() raises:
    var suite = TestSuite()
    # tests_gpu/stats/test_reductions_gpu.mojo
    suite.test[
        test_reductions_gpu__test_argmax_along_every_axis_on_the_device
    ]()
    suite.test[
        test_reductions_gpu__test_argmin_along_every_axis_on_the_device
    ]()
    suite^.run()
