"""GENERATED by tools/gen_test_aggregates.py -- do not edit.

Aggregates the 13 test files of `tests/linalg/` into one compiled
binary, so 13 compiler invocations become one. Run it with
`mojo -I . -I tests/linalg` (see tools/run_test_aggregates.sh).

Regenerate with `pixi run tests-gen`; CI fails if this file is out of date
with the tree.
"""

from std.testing import TestSuite
from test_banded import (
    test_solve_banded_matches_the_dense_solve as test_banded__test_solve_banded_matches_the_dense_solve,
)
from test_banded import (
    test_solve_banded_at_bandwidth_one_agrees_with_tridiagonal_solve as test_banded__test_solve_banded_at_bandwidth_one_agrees_with_tridiagonal_solve,
)
from test_banded import (
    test_solve_banded_pivots as test_banded__test_solve_banded_pivots,
)
from test_banded import (
    test_a_singular_band_raises as test_banded__test_a_singular_band_raises,
)
from test_banded import (
    test_solveh_banded_matches_solve_banded as test_banded__test_solveh_banded_matches_solve_banded,
)
from test_banded import (
    test_the_lower_and_upper_forms_agree as test_banded__test_the_lower_and_upper_forms_agree,
)
from test_banded import (
    test_cholesky_banded_then_cho_solve_banded_is_solveh_banded as test_banded__test_cholesky_banded_then_cho_solve_banded_is_solveh_banded,
)
from test_banded import (
    test_an_indefinite_matrix_raises as test_banded__test_an_indefinite_matrix_raises,
)
from test_banded import (
    test_solve_toeplitz_matches_the_dense_solve as test_banded__test_solve_toeplitz_matches_the_dense_solve,
)
from test_banded import (
    test_solve_toeplitz_on_a_symmetric_system as test_banded__test_solve_toeplitz_on_a_symmetric_system,
)
from test_banded import (
    test_a_zero_leading_entry_raises as test_banded__test_a_zero_leading_entry_raises,
)
from test_banded import (
    test_solve_circulant_matches_the_dense_solve as test_banded__test_solve_circulant_matches_the_dense_solve,
)
from test_banded import (
    test_solve_circulant_at_a_non_power_of_two_matches_scipy as test_banded__test_solve_circulant_at_a_non_power_of_two_matches_scipy,
)
from test_banded import (
    test_solve_circulant_residual_is_zero as test_banded__test_solve_circulant_residual_is_zero,
)
from test_banded import (
    test_a_singular_circulant_raises as test_banded__test_a_singular_circulant_raises,
)
from test_linalg import (
    test_cholesky_reproduces_the_matrix as test_linalg__test_cholesky_reproduces_the_matrix,
)
from test_linalg import (
    test_cholesky_upper_triangle_is_zero as test_linalg__test_cholesky_upper_triangle_is_zero,
)
from test_linalg import (
    test_cholesky_solve_matches_the_general_solve as test_linalg__test_cholesky_solve_matches_the_general_solve,
)
from test_linalg import (
    test_solve_reproduces_the_right_hand_side as test_linalg__test_solve_reproduces_the_right_hand_side,
)
from test_linalg import (
    test_solve_matches_a_known_answer as test_linalg__test_solve_matches_a_known_answer,
)
from test_linalg import (
    test_lu_factors_reproduce_the_matrix as test_linalg__test_lu_factors_reproduce_the_matrix,
)
from test_linalg import (
    test_inverse_produces_the_identity as test_linalg__test_inverse_produces_the_identity,
)
from test_linalg import (
    test_determinant_matches_the_cofactor_expansion as test_linalg__test_determinant_matches_the_cofactor_expansion,
)
from test_linalg import (
    test_determinant_is_multiplicative as test_linalg__test_determinant_is_multiplicative,
)
from test_linalg import (
    test_unpivoted_lu_fails_on_a_zero_pivot as test_linalg__test_unpivoted_lu_fails_on_a_zero_pivot,
)
from test_linalg import (
    test_slogdet_cholesky_matches_the_determinant as test_linalg__test_slogdet_cholesky_matches_the_determinant,
)
from test_linalg import (
    test_substitutions_invert_their_triangular_systems as test_linalg__test_substitutions_invert_their_triangular_systems,
)
from test_linalg import (
    test_unit_diagonal_substitution_ignores_the_stored_diagonal as test_linalg__test_unit_diagonal_substitution_ignores_the_stored_diagonal,
)
from test_linalg import (
    test_tridiagonal_solve_matches_a_dense_solve as test_linalg__test_tridiagonal_solve_matches_a_dense_solve,
)
from test_linalg import (
    test_tridiagonal_solve_on_the_spline_system as test_linalg__test_tridiagonal_solve_on_the_spline_system,
)
from test_linalg import (
    test_determinant_is_differentiable as test_linalg__test_determinant_is_differentiable,
)
from test_linalg import (
    test_cholesky_log_det_is_differentiable as test_linalg__test_cholesky_log_det_is_differentiable,
)
from test_linalg import (
    test_solve_is_differentiable as test_linalg__test_solve_is_differentiable,
)
from test_linalg import (
    test_compensated_cholesky_beats_plain_at_the_same_dtype as test_linalg__test_compensated_cholesky_beats_plain_at_the_same_dtype,
)
from test_linalg import (
    test_simd_lanes_factor_independent_matrices as test_linalg__test_simd_lanes_factor_independent_matrices,
)
from test_linalg import (
    test_trace_sums_the_diagonal as test_linalg__test_trace_sums_the_diagonal,
)
from test_linalg import (
    test_frobenius_norm_matches_the_entrywise_definition as test_linalg__test_frobenius_norm_matches_the_entrywise_definition,
)
from test_linalg import (
    test_norm_1_is_the_largest_absolute_column_sum as test_linalg__test_norm_1_is_the_largest_absolute_column_sum,
)
from test_linalg import (
    test_norm_inf_is_the_largest_absolute_row_sum as test_linalg__test_norm_inf_is_the_largest_absolute_row_sum,
)
from test_linalg import (
    test_norm_inf_of_a_symmetric_matrix_equals_its_norm_1 as test_linalg__test_norm_inf_of_a_symmetric_matrix_equals_its_norm_1,
)
from test_linalg import (
    test_qr_reconstructs_the_original_matrix as test_linalg__test_qr_reconstructs_the_original_matrix,
)
from test_linalg import (
    test_qr_r_is_upper_triangular as test_linalg__test_qr_r_is_upper_triangular,
)
from test_linalg import (
    test_qr_q_is_orthogonal as test_linalg__test_qr_q_is_orthogonal,
)
from test_linalg import (
    test_qr_of_a_symmetric_positive_definite_matrix_reconstructs_it as test_linalg__test_qr_of_a_symmetric_positive_definite_matrix_reconstructs_it,
)
from test_linalg import (
    test_qr_differentiates_through_at_dual as test_linalg__test_qr_differentiates_through_at_dual,
)
from test_linalg import (
    test_dot_is_the_inner_product as test_linalg__test_dot_is_the_inner_product,
)
from test_linalg import (
    test_nrm2_is_the_euclidean_length as test_linalg__test_nrm2_is_the_euclidean_length,
)
from test_linalg import (
    test_nrm2_squared_equals_dot_with_itself as test_linalg__test_nrm2_squared_equals_dot_with_itself,
)
from test_linalg import (
    test_outer_product_has_rank_one_structure as test_linalg__test_outer_product_has_rank_one_structure,
)
from test_linalg import (
    test_compensated_dot_beats_plain_on_a_long_cancelling_sum as test_linalg__test_compensated_dot_beats_plain_on_a_long_cancelling_sum,
)
from test_linalg import (
    test_eigh_eigenvalues_sum_to_the_trace as test_linalg__test_eigh_eigenvalues_sum_to_the_trace,
)
from test_linalg import (
    test_eigh_satisfies_the_eigenvalue_equation as test_linalg__test_eigh_satisfies_the_eigenvalue_equation,
)
from test_linalg import (
    test_eigh_eigenvectors_are_orthonormal as test_linalg__test_eigh_eigenvectors_are_orthonormal,
)
from test_linalg import (
    test_eigh_of_a_diagonal_matrix_returns_its_diagonal as test_linalg__test_eigh_of_a_diagonal_matrix_returns_its_diagonal,
)
from test_linalg import (
    test_eigh_of_the_identity_is_all_ones as test_linalg__test_eigh_of_the_identity_is_all_ones,
)
from test_linalg import (
    test_eigh_positive_definite_matrix_has_positive_eigenvalues as test_linalg__test_eigh_positive_definite_matrix_has_positive_eigenvalues,
)
from test_linalg import (
    test_svd_reconstructs_the_matrix as test_linalg__test_svd_reconstructs_the_matrix,
)
from test_linalg import (
    test_svd_singular_values_are_non_negative as test_linalg__test_svd_singular_values_are_non_negative,
)
from test_linalg import (
    test_svd_left_factor_is_orthonormal as test_linalg__test_svd_left_factor_is_orthonormal,
)
from test_linalg import (
    test_svd_right_factor_is_orthonormal as test_linalg__test_svd_right_factor_is_orthonormal,
)
from test_linalg import (
    test_svd_of_a_symmetric_matrix_matches_its_eigenvalue_magnitudes as test_linalg__test_svd_of_a_symmetric_matrix_matches_its_eigenvalue_magnitudes,
)
from test_linalg import (
    test_svd_of_a_singular_matrix_reports_a_zero_singular_value as test_linalg__test_svd_of_a_singular_matrix_reports_a_zero_singular_value,
)
from test_linalg import (
    test_pinv_of_an_invertible_matrix_is_its_inverse as test_linalg__test_pinv_of_an_invertible_matrix_is_its_inverse,
)
from test_linalg import (
    test_pinv_agrees_with_inverse_on_a_well_conditioned_matrix as test_linalg__test_pinv_agrees_with_inverse_on_a_well_conditioned_matrix,
)
from test_linalg import (
    test_pinv_of_a_singular_matrix_stays_finite as test_linalg__test_pinv_of_a_singular_matrix_stays_finite,
)
from test_linalg import (
    test_pinv_satisfies_the_moore_penrose_identity as test_linalg__test_pinv_satisfies_the_moore_penrose_identity,
)
from test_linalg import (
    test_cond_of_the_identity_is_one as test_linalg__test_cond_of_the_identity_is_one,
)
from test_linalg import (
    test_cond_is_the_ratio_of_extreme_singular_values as test_linalg__test_cond_is_the_ratio_of_extreme_singular_values,
)
from test_linalg import (
    test_cond_of_a_scaled_identity_is_still_one as test_linalg__test_cond_of_a_scaled_identity_is_still_one,
)
from test_linalg import (
    test_eigh_is_differentiable_at_dual as test_linalg__test_eigh_is_differentiable_at_dual,
)
from test_linalg import (
    test_eigh_derivative_survives_float32 as test_linalg__test_eigh_derivative_survives_float32,
)
from test_linalg import (
    test_eigh_float32_derivative_sums_to_the_trace as test_linalg__test_eigh_float32_derivative_sums_to_the_trace,
)
from test_linalg import (
    test_lstsq_recovers_an_exactly_fitting_line as test_linalg__test_lstsq_recovers_an_exactly_fitting_line,
)
from test_linalg import (
    test_lstsq_residual_is_orthogonal_to_the_columns as test_linalg__test_lstsq_residual_is_orthogonal_to_the_columns,
)
from test_linalg import (
    test_lstsq_at_a_square_system_is_the_solve as test_linalg__test_lstsq_at_a_square_system_is_the_solve,
)
from test_linalg import (
    test_lstsq_differentiates_through_the_fit as test_linalg__test_lstsq_differentiates_through_the_fit,
)
from test_linalg import (
    test_pivoting_factors_the_matrix_the_unpivoted_lu_cannot_start_on as test_linalg__test_pivoting_factors_the_matrix_the_unpivoted_lu_cannot_start_on,
)
from test_linalg import (
    test_a_pivoted_solve_reproduces_its_right_hand_side as test_linalg__test_a_pivoted_solve_reproduces_its_right_hand_side,
)
from test_linalg import (
    test_one_factorization_serves_several_right_hand_sides as test_linalg__test_one_factorization_serves_several_right_hand_sides,
)
from test_linalg import (
    test_the_permuted_matrix_is_the_product_of_its_factors as test_linalg__test_the_permuted_matrix_is_the_product_of_its_factors,
)
from test_linalg import (
    test_pivoting_beats_the_unpivoted_route_on_a_small_pivot as test_linalg__test_pivoting_beats_the_unpivoted_route_on_a_small_pivot,
)
from test_linalg import (
    test_eigvals_of_a_triangular_matrix_are_its_diagonal as test_linalg__test_eigvals_of_a_triangular_matrix_are_its_diagonal,
)
from test_linalg import (
    test_eigvals_of_a_quarter_turn_are_the_imaginary_units as test_linalg__test_eigvals_of_a_quarter_turn_are_the_imaginary_units,
)
from test_linalg import (
    test_eigvals_sum_to_the_trace_and_multiply_to_the_determinant as test_linalg__test_eigvals_sum_to_the_trace_and_multiply_to_the_determinant,
)
from test_linalg import (
    test_eigvals_agrees_with_eigh_on_a_symmetric_matrix as test_linalg__test_eigvals_agrees_with_eigh_on_a_symmetric_matrix,
)
from test_linalg import (
    test_eigvals_recovers_a_mixed_real_and_complex_spectrum as test_linalg__test_eigvals_recovers_a_mixed_real_and_complex_spectrum,
)
from test_linalg import (
    test_asum_and_axpy_agree_with_their_definitions as test_linalg__test_asum_and_axpy_agree_with_their_definitions,
)
from test_linalg import (
    test_hessenberg_is_zero_below_the_subdiagonal_and_keeps_the_spectrum as test_linalg__test_hessenberg_is_zero_below_the_subdiagonal_and_keeps_the_spectrum,
)
from test_linalg import (
    test_hessenberg_of_a_symmetric_matrix_is_tridiagonal as test_linalg__test_hessenberg_of_a_symmetric_matrix_is_tridiagonal,
)
from test_matfuncs import (
    test_expm_of_a_diagonal_matrix as test_matfuncs__test_expm_of_a_diagonal_matrix,
)
from test_matfuncs import (
    test_expm_of_zero_is_the_identity as test_matfuncs__test_expm_of_zero_is_the_identity,
)
from test_matfuncs import (
    test_expm_of_a_nilpotent_matrix_is_a_finite_sum as test_matfuncs__test_expm_of_a_nilpotent_matrix_is_a_finite_sum,
)
from test_matfuncs import (
    test_expm_of_the_rotation_generator_is_a_rotation as test_matfuncs__test_expm_of_the_rotation_generator_is_a_rotation,
)
from test_matfuncs import (
    test_expm_a_times_expm_minus_a_is_the_identity as test_matfuncs__test_expm_a_times_expm_minus_a_is_the_identity,
)
from test_matfuncs import (
    test_expm_scales_for_a_large_norm as test_matfuncs__test_expm_scales_for_a_large_norm,
)
from test_matfuncs import (
    test_array_expm_agrees_with_the_tensor_tier as test_matfuncs__test_array_expm_agrees_with_the_tensor_tier,
)
from test_matfuncs import (
    test_array_expm_of_the_rotation_generator as test_matfuncs__test_array_expm_of_the_rotation_generator,
)
from test_matfuncs import (
    test_expm_differentiates_at_dual as test_matfuncs__test_expm_differentiates_at_dual,
)
from test_matfuncs import (
    test_sqrtm_squares_back_to_the_matrix as test_matfuncs__test_sqrtm_squares_back_to_the_matrix,
)
from test_matfuncs import (
    test_sqrtm_of_a_diagonal_matrix as test_matfuncs__test_sqrtm_of_a_diagonal_matrix,
)
from test_norms_and_rank import (
    test_vector_two_norm_is_exactly_nrm2 as test_norms_and_rank__test_vector_two_norm_is_exactly_nrm2,
)
from test_norms_and_rank import (
    test_vector_two_norm_value as test_norms_and_rank__test_vector_two_norm_value,
)
from test_norms_and_rank import (
    test_vector_two_norm_is_the_default as test_norms_and_rank__test_vector_two_norm_is_the_default,
)
from test_norms_and_rank import (
    test_vector_one_norm as test_norms_and_rank__test_vector_one_norm,
)
from test_norms_and_rank import (
    test_vector_infinity_norms as test_norms_and_rank__test_vector_infinity_norms,
)
from test_norms_and_rank import (
    test_the_matrix_overload_still_resolves as test_norms_and_rank__test_the_matrix_overload_still_resolves,
)
from test_norms_and_rank import (
    test_eigvalsh_is_eigh_without_the_vectors as test_norms_and_rank__test_eigvalsh_is_eigh_without_the_vectors,
)
from test_norms_and_rank import (
    test_svdvals_is_svd_without_the_vectors as test_norms_and_rank__test_svdvals_is_svd_without_the_vectors,
)
from test_norms_and_rank import (
    test_eigenvalues_sum_to_the_trace as test_norms_and_rank__test_eigenvalues_sum_to_the_trace,
)
from test_norms_and_rank import (
    test_matrix_rank_of_a_full_rank_matrix as test_norms_and_rank__test_matrix_rank_of_a_full_rank_matrix,
)
from test_norms_and_rank import (
    test_matrix_rank_of_a_rank_deficient_matrix as test_norms_and_rank__test_matrix_rank_of_a_rank_deficient_matrix,
)
from test_norms_and_rank import (
    test_matrix_rank_counts_per_lane as test_norms_and_rank__test_matrix_rank_counts_per_lane,
)
from test_panel import (
    test_potrf_diag_factors_the_whole_block as test_panel__test_potrf_diag_factors_the_whole_block,
)
from test_panel import (
    test_potrf_diag_leaves_the_upper_triangle_alone as test_panel__test_potrf_diag_leaves_the_upper_triangle_alone,
)
from test_panel import (
    test_potrf_diag_factors_an_offset_block as test_panel__test_potrf_diag_factors_an_offset_block,
)
from test_panel import (
    test_potrf_diag_flags_a_matrix_that_is_not_positive_definite as test_panel__test_potrf_diag_flags_a_matrix_that_is_not_positive_definite,
)
from test_panel import (
    test_trsm_right_lower_t_solves_against_the_diagonal_block as test_panel__test_trsm_right_lower_t_solves_against_the_diagonal_block,
)
from test_panel import (
    test_trsm_left_lower_unit_solves_the_block_row as test_panel__test_trsm_left_lower_unit_solves_the_block_row,
)
from test_panel import (
    test_getrf_panel_gives_lu_of_the_columns_it_factored as test_panel__test_getrf_panel_gives_lu_of_the_columns_it_factored,
)
from test_panel import (
    test_getrf_panel_picks_the_largest_pivot as test_panel__test_getrf_panel_picks_the_largest_pivot,
)
from test_panel import (
    test_pack_block_copies_a_strided_block_densely as test_panel__test_pack_block_copies_a_strided_block_densely,
)
from test_panel import (
    test_pack_block_copies_a_width_the_simd_lanes_do_not_divide as test_panel__test_pack_block_copies_a_width_the_simd_lanes_do_not_divide,
)
from test_panel import (
    test_pack_block_transposed_copies_a_ragged_width as test_panel__test_pack_block_transposed_copies_a_ragged_width,
)
from test_panel import (
    test_getrf2_agrees_with_the_single_block_panel_at_every_base as test_panel__test_getrf2_agrees_with_the_single_block_panel_at_every_base,
)
from test_products import (
    test_inner_equals_matmul_against_an_explicit_transpose as test_products__test_inner_equals_matmul_against_an_explicit_transpose,
)
from test_products import (
    test_inner_is_the_gram_matrix_of_the_rows as test_products__test_inner_is_the_gram_matrix_of_the_rows,
)
from test_products import (
    test_array_inner_agrees_with_the_tensor_tier as test_products__test_array_inner_agrees_with_the_tensor_tier,
)
from test_products import (
    test_kron_matches_a_hand_written_loop as test_products__test_kron_matches_a_hand_written_loop,
)
from test_products import (
    test_kron_with_the_identity_tiles_the_other_operand as test_products__test_kron_with_the_identity_tiles_the_other_operand,
)
from test_products import (
    test_array_kron_agrees_with_the_tensor_tier as test_products__test_array_kron_agrees_with_the_tensor_tier,
)
from test_products import (
    test_matrix_power_three_equals_two_matmuls as test_products__test_matrix_power_three_equals_two_matmuls,
)
from test_products import (
    test_matrix_power_zero_is_the_identity as test_products__test_matrix_power_zero_is_the_identity,
)
from test_products import (
    test_matrix_power_one_is_the_matrix as test_products__test_matrix_power_one_is_the_matrix,
)
from test_products import (
    test_an_even_power_exercises_the_squaring_path as test_products__test_an_even_power_exercises_the_squaring_path,
)
from test_products import (
    test_array_matrix_power_agrees_with_the_tensor_tier as test_products__test_array_matrix_power_agrees_with_the_tensor_tier,
)
from test_slogdet import (
    test_slogdet_reproduces_det as test_slogdet__test_slogdet_reproduces_det,
)
from test_slogdet import (
    test_slogdet_reports_the_sign_separately as test_slogdet__test_slogdet_reports_the_sign_separately,
)
from test_slogdet import (
    test_a_singular_matrix_gives_sign_zero_and_minus_infinity as test_slogdet__test_a_singular_matrix_gives_sign_zero_and_minus_infinity,
)
from test_slogdet import (
    test_slogdet_survives_where_det_overflows as test_slogdet__test_slogdet_survives_where_det_overflows,
)
from test_slogdet import (
    test_the_two_tiers_agree as test_slogdet__test_the_two_tiers_agree,
)
from test_slogdet import (
    test_the_array_tier_reports_a_singular_matrix_too as test_slogdet__test_the_array_tier_reports_a_singular_matrix_too,
)
from test_slogdet import (
    test_the_factor_can_be_reused_for_both as test_slogdet__test_the_factor_can_be_reused_for_both,
)
from test_special_matrices import (
    test_toeplitz_two_argument_form as test_special_matrices__test_toeplitz_two_argument_form,
)
from test_special_matrices import (
    test_toeplitz_symmetric_form as test_special_matrices__test_toeplitz_symmetric_form,
)
from test_special_matrices import (
    test_the_symmetric_form_equals_the_two_argument_one as test_special_matrices__test_the_symmetric_form_equals_the_two_argument_one,
)
from test_special_matrices import (
    test_hankel_is_constant_along_antidiagonals as test_special_matrices__test_hankel_is_constant_along_antidiagonals,
)
from test_special_matrices import (
    test_circulant_rotates_each_column as test_special_matrices__test_circulant_rotates_each_column,
)
from test_special_matrices import (
    test_a_symmetric_circulant_is_its_own_toeplitz as test_special_matrices__test_a_symmetric_circulant_is_its_own_toeplitz,
)
from test_special_matrices import (
    test_companion_eigenvalues_are_the_polynomial_roots as test_special_matrices__test_companion_eigenvalues_are_the_polynomial_roots,
)
from test_special_matrices import (
    test_companion_has_the_documented_shape as test_special_matrices__test_companion_has_the_documented_shape,
)
from test_special_matrices import (
    test_hilbert_entries as test_special_matrices__test_hilbert_entries,
)
from test_special_matrices import (
    test_hilbert_is_symmetric as test_special_matrices__test_hilbert_is_symmetric,
)
from test_special_matrices import (
    test_block_diag_places_the_blocks_and_zeros_the_rest as test_special_matrices__test_block_diag_places_the_blocks_and_zeros_the_rest,
)
from test_special_matrices import (
    test_khatri_rao_is_kron_column_by_column as test_special_matrices__test_khatri_rao_is_kron_column_by_column,
)
from test_special_matrices import (
    test_convolution_matrix_times_a_vector_is_a_convolution as test_special_matrices__test_convolution_matrix_times_a_vector_is_a_convolution,
)
from test_special_matrices import (
    test_pascal_symmetric_lower_and_upper as test_special_matrices__test_pascal_symmetric_lower_and_upper,
)
from test_special_matrices import (
    test_invpascal_is_the_inverse_in_every_kind as test_special_matrices__test_invpascal_is_the_inverse_in_every_kind,
)
from test_special_matrices import (
    test_hadamard_matches_sylvesters_construction_and_is_orthogonal as test_special_matrices__test_hadamard_matches_sylvesters_construction_and_is_orthogonal,
)
from test_special_matrices import (
    test_helmert_rows_are_orthonormal_contrasts as test_special_matrices__test_helmert_rows_are_orthonormal_contrasts,
)
from test_special_matrices import (
    test_fiedler_is_the_absolute_difference_table as test_special_matrices__test_fiedler_is_the_absolute_difference_table,
)
from test_special_matrices import (
    test_fiedler_companion_has_the_polynomial_roots_as_eigenvalues as test_special_matrices__test_fiedler_companion_has_the_polynomial_roots_as_eigenvalues,
)
from test_special_matrices import (
    test_leslie_places_fecundities_and_survivals as test_special_matrices__test_leslie_places_fecundities_and_survivals,
)
from test_tensor_eigen import (
    test_sytrd_leaves_q_transpose_a_q_tridiagonal as test_tensor_eigen__test_sytrd_leaves_q_transpose_a_q_tridiagonal,
)
from test_tensor_eigen import (
    test_sytrd_reports_the_band_it_produced as test_tensor_eigen__test_sytrd_reports_the_band_it_produced,
)
from test_tensor_eigen import (
    test_sytrd_is_a_similarity_so_q_t_q_transpose_reconstructs as test_tensor_eigen__test_sytrd_is_a_similarity_so_q_t_q_transpose_reconstructs,
)
from test_tensor_eigen import (
    test_sytrd_q_is_orthogonal as test_tensor_eigen__test_sytrd_q_is_orthogonal,
)
from test_tensor_eigen import (
    test_sytrd_q_matches_the_unblocked_accumulation as test_tensor_eigen__test_sytrd_q_matches_the_unblocked_accumulation,
)
from test_tensor_eigen import (
    test_sytrd_q_at_a_ragged_panel_width as test_tensor_eigen__test_sytrd_q_at_a_ragged_panel_width,
)
from test_tensor_eigen import (
    test_sytrd_blocking_does_not_change_the_answer as test_tensor_eigen__test_sytrd_blocking_does_not_change_the_answer,
)
from test_tensor_eigen import (
    test_sytrd_at_a_ragged_reduction_panel as test_tensor_eigen__test_sytrd_at_a_ragged_reduction_panel,
)
from test_tensor_eigen import (
    test_sytrd_preserves_the_trace as test_tensor_eigen__test_sytrd_preserves_the_trace,
)
from test_tensor_eigen import (
    test_sytrd_leaves_an_already_tridiagonal_matrix_alone as test_tensor_eigen__test_sytrd_leaves_an_already_tridiagonal_matrix_alone,
)
from test_tensor_eigen import (
    test_sytrd_at_the_sizes_with_nothing_to_do as test_tensor_eigen__test_sytrd_at_the_sizes_with_nothing_to_do,
)
from test_tensor_eigen import (
    test_eigvalsh_of_a_diagonal_matrix_is_its_diagonal_ascending as test_tensor_eigen__test_eigvalsh_of_a_diagonal_matrix_is_its_diagonal_ascending,
)
from test_tensor_eigen import (
    test_eigvalsh_matches_the_known_spectrum_of_hilbert_four as test_tensor_eigen__test_eigvalsh_matches_the_known_spectrum_of_hilbert_four,
)
from test_tensor_eigen import (
    test_eigvalsh_agrees_with_the_array_tier_as_a_multiset as test_tensor_eigen__test_eigvalsh_agrees_with_the_array_tier_as_a_multiset,
)
from test_tensor_eigen import (
    test_eigvalsh_sums_to_the_trace_and_multiplies_to_the_determinant as test_tensor_eigen__test_eigvalsh_sums_to_the_trace_and_multiplies_to_the_determinant,
)
from test_tensor_eigen import (
    test_eigvalsh_handles_a_matrix_with_repeated_eigenvalues as test_tensor_eigen__test_eigvalsh_handles_a_matrix_with_repeated_eigenvalues,
)
from test_tensor_eigen import (
    test_eigh_satisfies_the_eigenvalue_equation_for_every_pair as test_tensor_eigen__test_eigh_satisfies_the_eigenvalue_equation_for_every_pair,
)
from test_tensor_eigen import (
    test_eigh_eigenvectors_are_orthonormal as test_tensor_eigen__test_eigh_eigenvectors_are_orthonormal,
)
from test_tensor_eigen import (
    test_eigh_reconstructs_a_from_its_factors as test_tensor_eigen__test_eigh_reconstructs_a_from_its_factors,
)
from test_tensor_eigen import (
    test_eigh_values_are_ascending_and_equal_eigvalsh as test_tensor_eigen__test_eigh_values_are_ascending_and_equal_eigvalsh,
)
from test_tensor_eigen import (
    test_eigh_of_a_diagonal_matrix_returns_permuted_identity_vectors as test_tensor_eigen__test_eigh_of_a_diagonal_matrix_returns_permuted_identity_vectors,
)
from test_tensor_eigen import (
    test_eigh_blocking_does_not_change_the_answer as test_tensor_eigen__test_eigh_blocking_does_not_change_the_answer,
)
from test_tensor_eigen import (
    test_eigh_ragged_window_sizes as test_tensor_eigen__test_eigh_ragged_window_sizes,
)
from test_tensor_eigen import (
    test_eigh_at_n_one_and_two as test_tensor_eigen__test_eigh_at_n_one_and_two,
)
from test_tensor_eigen import (
    test_gebrd_leaves_q_transpose_a_p_upper_bidiagonal as test_tensor_eigen__test_gebrd_leaves_q_transpose_a_p_upper_bidiagonal,
)
from test_tensor_eigen import (
    test_gebrd_q_and_p_are_orthogonal as test_tensor_eigen__test_gebrd_q_and_p_are_orthogonal,
)
from test_tensor_eigen import (
    test_bidiagonal_q_and_p_match_the_unblocked_walk as test_tensor_eigen__test_bidiagonal_q_and_p_match_the_unblocked_walk,
)
from test_tensor_eigen import (
    test_gebrd_blocking_does_not_change_the_answer as test_tensor_eigen__test_gebrd_blocking_does_not_change_the_answer,
)
from test_tensor_eigen import (
    test_gebrd_at_a_ragged_panel as test_tensor_eigen__test_gebrd_at_a_ragged_panel,
)
from test_tensor_eigen import (
    test_svdvals_matches_scipy_on_a_tall_matrix as test_tensor_eigen__test_svdvals_matches_scipy_on_a_tall_matrix,
)
from test_tensor_eigen import (
    test_svdvals_matches_scipy_on_hilbert_four as test_tensor_eigen__test_svdvals_matches_scipy_on_hilbert_four,
)
from test_tensor_eigen import (
    test_svdvals_agrees_with_the_array_tier_as_a_multiset as test_tensor_eigen__test_svdvals_agrees_with_the_array_tier_as_a_multiset,
)
from test_tensor_eigen import (
    test_svd_reconstructs_a_from_its_factors as test_tensor_eigen__test_svd_reconstructs_a_from_its_factors,
)
from test_tensor_eigen import (
    test_svd_factors_are_orthonormal_and_values_descending as test_tensor_eigen__test_svd_factors_are_orthonormal_and_values_descending,
)
from test_tensor_eigen import (
    test_svd_values_equal_svdvals as test_tensor_eigen__test_svd_values_equal_svdvals,
)
from test_tensor_eigen import (
    test_svd_blocking_does_not_change_the_answer as test_tensor_eigen__test_svd_blocking_does_not_change_the_answer,
)
from test_tensor_eigen import (
    test_svd_at_n_one_two_three as test_tensor_eigen__test_svd_at_n_one_two_three,
)
from test_tensor_eigen import (
    test_svdvals_finds_a_rank_deficient_matrix as test_tensor_eigen__test_svdvals_finds_a_rank_deficient_matrix,
)
from test_tensor_eigen import (
    test_bdsqr_matches_the_golub_kahan_oracle as test_tensor_eigen__test_bdsqr_matches_the_golub_kahan_oracle,
)
from test_tensor_eigen import (
    test_svd_of_a_rank_deficient_matrix_reconstructs_it as test_tensor_eigen__test_svd_of_a_rank_deficient_matrix_reconstructs_it,
)
from test_tensor_eigen import (
    test_pinv_inverts_a_full_rank_tall_matrix_from_the_left as test_tensor_eigen__test_pinv_inverts_a_full_rank_tall_matrix_from_the_left,
)
from test_tensor_eigen import (
    test_pinv_of_a_square_matrix_is_its_inverse as test_tensor_eigen__test_pinv_of_a_square_matrix_is_its_inverse,
)
from test_tensor_eigen import (
    test_pinv_of_a_rank_deficient_matrix_matches_scipy_and_penrose as test_tensor_eigen__test_pinv_of_a_rank_deficient_matrix_matches_scipy_and_penrose,
)
from test_tensor_eigen import (
    test_cond_matches_scipy_on_hilbert_four as test_tensor_eigen__test_cond_matches_scipy_on_hilbert_four,
)
from test_tensor_eigen import (
    test_cond_of_a_singular_matrix_is_infinite_or_huge as test_tensor_eigen__test_cond_of_a_singular_matrix_is_infinite_or_huge,
)
from test_tensor_eigen import (
    test_matrix_rank_counts_independent_directions as test_tensor_eigen__test_matrix_rank_counts_independent_directions,
)
from test_tensor_eigen import (
    test_matrix_rank_honours_an_explicit_tolerance as test_tensor_eigen__test_matrix_rank_honours_an_explicit_tolerance,
)
from test_tensor_eigen import (
    test_lstsq_svd_agrees_with_qr_at_full_rank as test_tensor_eigen__test_lstsq_svd_agrees_with_qr_at_full_rank,
)
from test_tensor_eigen import (
    test_lstsq_svd_returns_the_minimum_norm_solution_when_rank_deficient as test_tensor_eigen__test_lstsq_svd_returns_the_minimum_norm_solution_when_rank_deficient,
)
from test_tensor_eigen import (
    test_orth_returns_a_basis_of_the_right_width_and_is_orthonormal as test_tensor_eigen__test_orth_returns_a_basis_of_the_right_width_and_is_orthonormal,
)
from test_tensor_eigen import (
    test_orth_of_a_full_rank_matrix_has_every_column as test_tensor_eigen__test_orth_of_a_full_rank_matrix_has_every_column,
)
from test_tensor_eigen import (
    test_null_space_is_annihilated_by_the_matrix as test_tensor_eigen__test_null_space_is_annihilated_by_the_matrix,
)
from test_tensor_eigen import (
    test_null_space_of_a_full_rank_matrix_is_empty as test_tensor_eigen__test_null_space_of_a_full_rank_matrix_is_empty,
)
from test_tensor_eigen import (
    test_polar_factors_reconstruct_and_have_their_defining_properties as test_tensor_eigen__test_polar_factors_reconstruct_and_have_their_defining_properties,
)
from test_tensor_eigen import (
    test_hessenberg_is_zero_below_the_subdiagonal_and_a_similarity as test_tensor_eigen__test_hessenberg_is_zero_below_the_subdiagonal_and_a_similarity,
)
from test_tensor_eigen import (
    test_hessenberg_q_is_orthogonal_at_every_block as test_tensor_eigen__test_hessenberg_q_is_orthogonal_at_every_block,
)
from test_tensor_eigen import (
    test_hessenberg_blocking_does_not_change_the_answer as test_tensor_eigen__test_hessenberg_blocking_does_not_change_the_answer,
)
from test_tensor_eigen import (
    test_hessenberg_at_a_ragged_panel as test_tensor_eigen__test_hessenberg_at_a_ragged_panel,
)
from test_tensor_eigen import (
    test_hessenberg_of_a_two_by_two_is_itself as test_tensor_eigen__test_hessenberg_of_a_two_by_two_is_itself,
)
from test_tensor_eigen import (
    test_eigvals_matches_scipy_for_a_real_spectrum as test_tensor_eigen__test_eigvals_matches_scipy_for_a_real_spectrum,
)
from test_tensor_eigen import (
    test_eigvals_matches_scipy_for_two_complex_pairs as test_tensor_eigen__test_eigvals_matches_scipy_for_two_complex_pairs,
)
from test_tensor_eigen import (
    test_eigvals_of_a_quarter_turn_are_the_imaginary_units as test_tensor_eigen__test_eigvals_of_a_quarter_turn_are_the_imaginary_units,
)
from test_tensor_eigen import (
    test_eigvals_agrees_with_eigvalsh_on_a_symmetric_matrix as test_tensor_eigen__test_eigvals_agrees_with_eigvalsh_on_a_symmetric_matrix,
)
from test_tensor_eigen import (
    test_schur_reconstructs_and_is_quasi_triangular as test_tensor_eigen__test_schur_reconstructs_and_is_quasi_triangular,
)
from test_tensor_eigen import (
    test_schur_of_a_real_spectrum_is_triangular_with_the_eigenvalues_on_the_diagonal as test_tensor_eigen__test_schur_of_a_real_spectrum_is_triangular_with_the_eigenvalues_on_the_diagonal,
)
from test_tensor_eigen import (
    test_schur_blocking_does_not_change_the_answer as test_tensor_eigen__test_schur_blocking_does_not_change_the_answer,
)
from test_tensor_eigen import (
    test_schur_at_n_one_and_two as test_tensor_eigen__test_schur_at_n_one_and_two,
)
from test_tensor_eigen import (
    test_schur_ragged_window_sizes as test_tensor_eigen__test_schur_ragged_window_sizes,
)
from test_tensor_linalg import (
    test_matmul_matches_hand_computed_product as test_tensor_linalg__test_matmul_matches_hand_computed_product,
)
from test_tensor_linalg import (
    test_tensor_matmul_agrees_with_array_matmul as test_tensor_linalg__test_tensor_matmul_agrees_with_array_matmul,
)
from test_tensor_linalg import (
    test_matmul_dynamic_agrees_with_static as test_tensor_linalg__test_matmul_dynamic_agrees_with_static,
)
from test_tensor_linalg import (
    test_matmul_dynamic_rejects_mismatched_shapes as test_tensor_linalg__test_matmul_dynamic_rejects_mismatched_shapes,
)
from test_tensor_linalg import (
    test_matvec_agrees_with_matmul_against_a_column as test_tensor_linalg__test_matvec_agrees_with_matmul_against_a_column,
)
from test_tensor_linalg import (
    test_matvec_when_the_row_count_is_not_a_lane_multiple as test_tensor_linalg__test_matvec_when_the_row_count_is_not_a_lane_multiple,
)
from test_tensor_linalg import (
    test_matvec_odd_rows_and_odd_columns_every_element as test_tensor_linalg__test_matvec_odd_rows_and_odd_columns_every_element,
)
from test_tensor_linalg import (
    test_matvec_at_a_k_misaligned_for_the_widest_lane_counts as test_tensor_linalg__test_matvec_at_a_k_misaligned_for_the_widest_lane_counts,
)
from test_tensor_linalg import (
    test_matvec_at_float32_where_a_lane_is_sixteen_wide as test_tensor_linalg__test_matvec_at_float32_where_a_lane_is_sixteen_wide,
)
from test_tensor_linalg import (
    test_matvec_square_but_not_a_lane_multiple as test_tensor_linalg__test_matvec_square_but_not_a_lane_multiple,
)
from test_tensor_linalg import (
    test_batched_matmul_is_one_product_per_leading_index as test_tensor_linalg__test_batched_matmul_is_one_product_per_leading_index,
)
from test_tensor_linalg import (
    test_batched_matmul_agrees_with_per_matrix_matmul as test_tensor_linalg__test_batched_matmul_agrees_with_per_matrix_matmul,
)
from test_tensor_linalg import (
    test_tril_and_triu_split_the_matrix_at_the_diagonal as test_tensor_linalg__test_tril_and_triu_split_the_matrix_at_the_diagonal,
)
from test_tensor_linalg import (
    test_tril_and_triu_accept_a_non_square_matrix as test_tensor_linalg__test_tril_and_triu_accept_a_non_square_matrix,
)
from test_tensor_linalg import (
    test_cholesky_reconstructs_the_matrix as test_tensor_linalg__test_cholesky_reconstructs_the_matrix,
)
from test_tensor_linalg import (
    test_cholesky_is_lower_triangular as test_tensor_linalg__test_cholesky_is_lower_triangular,
)
from test_tensor_linalg import (
    test_cholesky_blocking_does_not_change_the_answer as test_tensor_linalg__test_cholesky_blocking_does_not_change_the_answer,
)
from test_tensor_linalg import (
    test_cholesky_tiling_does_not_change_the_answer as test_tensor_linalg__test_cholesky_tiling_does_not_change_the_answer,
)
from test_tensor_linalg import (
    test_cholesky_reads_only_the_lower_triangle as test_tensor_linalg__test_cholesky_reads_only_the_lower_triangle,
)
from test_tensor_linalg import (
    test_cholesky_agrees_with_the_array_tier as test_tensor_linalg__test_cholesky_agrees_with_the_array_tier,
)
from test_tensor_linalg import (
    test_cholesky_rejects_a_matrix_that_is_not_positive_definite as test_tensor_linalg__test_cholesky_rejects_a_matrix_that_is_not_positive_definite,
)
from test_tensor_linalg import (
    test_cholesky_reports_a_failure_in_a_later_block as test_tensor_linalg__test_cholesky_reports_a_failure_in_a_later_block,
)
from test_tensor_linalg import (
    test_solve_residual_is_at_machine_precision as test_tensor_linalg__test_solve_residual_is_at_machine_precision,
)
from test_tensor_linalg import (
    test_solve_blocking_does_not_change_the_answer as test_tensor_linalg__test_solve_blocking_does_not_change_the_answer,
)
from test_tensor_linalg import (
    test_solve_agrees_with_the_array_tier as test_tensor_linalg__test_solve_agrees_with_the_array_tier,
)
from test_tensor_linalg import (
    test_lu_factor_handles_a_zero_leading_pivot as test_tensor_linalg__test_lu_factor_handles_a_zero_leading_pivot,
)
from test_tensor_linalg import (
    test_lu_factor_is_reusable_across_right_hand_sides as test_tensor_linalg__test_lu_factor_is_reusable_across_right_hand_sides,
)
from test_tensor_linalg import (
    test_lu_factor_det_agrees_with_the_array_tier as test_tensor_linalg__test_lu_factor_det_agrees_with_the_array_tier,
)
from test_tensor_linalg import (
    test_tensor_dot_agrees_with_the_array_dot as test_tensor_linalg__test_tensor_dot_agrees_with_the_array_dot,
)
from test_tensor_linalg import (
    test_tensor_nrm2_and_asum_agree_with_the_array_versions as test_tensor_linalg__test_tensor_nrm2_and_asum_agree_with_the_array_versions,
)
from test_tensor_linalg import (
    test_tensor_axpy_agrees_with_the_array_axpy as test_tensor_linalg__test_tensor_axpy_agrees_with_the_array_axpy,
)
from test_tensor_linalg import (
    test_tensor_axpy_writes_every_element_of_its_result as test_tensor_linalg__test_tensor_axpy_writes_every_element_of_its_result,
)
from test_tensor_linalg import (
    test_tensor_outer_writes_every_element_of_its_result as test_tensor_linalg__test_tensor_outer_writes_every_element_of_its_result,
)
from test_tensor_linalg import (
    test_tensor_outer_agrees_with_the_array_outer as test_tensor_linalg__test_tensor_outer_agrees_with_the_array_outer,
)
from test_tensor_linalg import (
    test_tensor_outer_accepts_a_rectangular_result as test_tensor_linalg__test_tensor_outer_accepts_a_rectangular_result,
)
from test_tensor_linalg import (
    test_solve_triangular_agrees_with_forward_substitution as test_tensor_linalg__test_solve_triangular_agrees_with_forward_substitution,
)
from test_tensor_linalg import (
    test_solve_triangular_transposed_solves_against_the_transpose as test_tensor_linalg__test_solve_triangular_transposed_solves_against_the_transpose,
)
from test_tensor_linalg import (
    test_solve_triangular_matrix_agrees_with_the_vector_overload as test_tensor_linalg__test_solve_triangular_matrix_agrees_with_the_vector_overload,
)
from test_tensor_linalg import (
    test_cholesky_solve_reproduces_the_right_hand_side as test_tensor_linalg__test_cholesky_solve_reproduces_the_right_hand_side,
)
from test_tensor_linalg import (
    test_cholesky_solve_agrees_with_the_array_tier as test_tensor_linalg__test_cholesky_solve_agrees_with_the_array_tier,
)
from test_tensor_linalg import (
    test_cholesky_solve_matrix_agrees_with_the_vector_overload as test_tensor_linalg__test_cholesky_solve_matrix_agrees_with_the_vector_overload,
)
from test_tensor_linalg import (
    test_lu_factor_solves_several_right_hand_sides_at_once as test_tensor_linalg__test_lu_factor_solves_several_right_hand_sides_at_once,
)
from test_tensor_linalg import (
    test_inverse_times_the_matrix_is_the_identity as test_tensor_linalg__test_inverse_times_the_matrix_is_the_identity,
)
from test_tensor_linalg import (
    test_inverse_agrees_with_the_array_tier as test_tensor_linalg__test_inverse_agrees_with_the_array_tier,
)
from test_tensor_linalg import (
    test_tensor_det_agrees_with_the_reusable_factorization as test_tensor_linalg__test_tensor_det_agrees_with_the_reusable_factorization,
)
from test_tensor_linalg import (
    test_tensor_trace_agrees_with_the_array_trace as test_tensor_linalg__test_tensor_trace_agrees_with_the_array_trace,
)
from test_tensor_linalg import (
    test_tensor_frobenius_norm_agrees_with_the_array_norm as test_tensor_linalg__test_tensor_frobenius_norm_agrees_with_the_array_norm,
)
from test_tensor_linalg import (
    test_tensor_induced_norms_agree_with_the_array_norms as test_tensor_linalg__test_tensor_induced_norms_agree_with_the_array_norms,
)
from test_tensor_linalg import (
    test_tensor_frobenius_norm_is_nrm2_of_the_flattened_matrix as test_tensor_linalg__test_tensor_frobenius_norm_is_nrm2_of_the_flattened_matrix,
)
from test_tensor_linalg import (
    test_tensor_qr_reconstructs_the_matrix as test_tensor_linalg__test_tensor_qr_reconstructs_the_matrix,
)
from test_tensor_linalg import (
    test_tensor_qr_q_has_orthonormal_columns as test_tensor_linalg__test_tensor_qr_q_has_orthonormal_columns,
)
from test_tensor_linalg import (
    test_tensor_qr_r_is_upper_triangular as test_tensor_linalg__test_tensor_qr_r_is_upper_triangular,
)
from test_tensor_linalg import (
    test_tensor_qr_agrees_with_the_array_tier_up_to_column_signs as test_tensor_linalg__test_tensor_qr_agrees_with_the_array_tier_up_to_column_signs,
)
from test_tensor_linalg import (
    test_tensor_qr_apply_q_transpose_agrees_with_forming_q as test_tensor_linalg__test_tensor_qr_apply_q_transpose_agrees_with_forming_q,
)
from test_tensor_linalg import (
    test_tensor_qr_solve_agrees_with_the_array_lstsq as test_tensor_linalg__test_tensor_qr_solve_agrees_with_the_array_lstsq,
)
from test_tensor_linalg import (
    test_tensor_qr_block_size_does_not_change_the_answer as test_tensor_linalg__test_tensor_qr_block_size_does_not_change_the_answer,
)
from test_tensor_linalg import (
    test_tensor_qr_with_a_ragged_last_panel_reconstructs_the_matrix as test_tensor_linalg__test_tensor_qr_with_a_ragged_last_panel_reconstructs_the_matrix,
)
from test_tensor_linalg import (
    test_tensor_qr_of_a_square_matrix_reconstructs_it as test_tensor_linalg__test_tensor_qr_of_a_square_matrix_reconstructs_it,
)
from test_tensor_linalg import (
    test_lstsq_agrees_with_the_factorization_it_wraps as test_tensor_linalg__test_lstsq_agrees_with_the_factorization_it_wraps,
)
from test_tensor_linalg import (
    test_lstsq_recovers_an_exact_linear_fit as test_tensor_linalg__test_lstsq_recovers_an_exact_linear_fit,
)
from test_tensor_linalg import (
    test_rq_reconstructs_the_matrix as test_tensor_linalg__test_rq_reconstructs_the_matrix,
)
from test_tensor_linalg import (
    test_rq_r_is_upper_triangular_and_q_is_orthogonal as test_tensor_linalg__test_rq_r_is_upper_triangular_and_q_is_orthogonal,
)
from test_tensor_linalg import (
    test_rq_of_a_one_by_one_is_the_scalar as test_tensor_linalg__test_rq_of_a_one_by_one_is_the_scalar,
)
from test_tensor_matfuncs import (
    test_sqrtm_matches_scipy_and_squares_back as test_tensor_matfuncs__test_sqrtm_matches_scipy_and_squares_back,
)
from test_tensor_matfuncs import (
    test_sqrtm_of_complex_pairs_is_real_and_matches_scipy as test_tensor_matfuncs__test_sqrtm_of_complex_pairs_is_real_and_matches_scipy,
)
from test_tensor_matfuncs import (
    test_sqrtm_handles_repeated_and_defective_eigenvalues as test_tensor_matfuncs__test_sqrtm_handles_repeated_and_defective_eigenvalues,
)
from test_tensor_matfuncs import (
    test_logm_matches_scipy_and_inverts_expm as test_tensor_matfuncs__test_logm_matches_scipy_and_inverts_expm,
)
from test_tensor_matfuncs import (
    test_funm_at_exp_agrees_with_expm_including_complex_blocks as test_tensor_matfuncs__test_funm_at_exp_agrees_with_expm_including_complex_blocks,
)
from test_tensor_matfuncs import (
    test_funm_raises_on_a_coupled_repeated_eigenvalue as test_tensor_matfuncs__test_funm_raises_on_a_coupled_repeated_eigenvalue,
)
from test_tensor_matfuncs import (
    test_cosm_and_sinm_match_scipy_and_satisfy_the_pythagorean_identity as test_tensor_matfuncs__test_cosm_and_sinm_match_scipy_and_satisfy_the_pythagorean_identity,
)
from test_tensor_matfuncs import (
    test_fractional_matrix_power_matches_scipy_and_sqrtm as test_tensor_matfuncs__test_fractional_matrix_power_matches_scipy_and_sqrtm,
)
from test_tensor_matfuncs import (
    test_tanm_is_the_matrix_quotient_of_sinm_by_cosm as test_tensor_matfuncs__test_tanm_is_the_matrix_quotient_of_sinm_by_cosm,
)
from test_tensor_matfuncs import (
    test_tanm_of_a_diagonal_matrix_is_the_scalar_tangent as test_tensor_matfuncs__test_tanm_of_a_diagonal_matrix_is_the_scalar_tangent,
)
from test_tensor_products import (
    test_cross_of_the_axes_and_antisymmetry as test_tensor_products__test_cross_of_the_axes_and_antisymmetry,
)
from test_tensor_products import (
    test_cross_on_rows as test_tensor_products__test_cross_on_rows,
)
from test_tensor_products import (
    test_tensordot_at_one_axis_is_matmul_and_at_zero_is_outer as test_tensor_products__test_tensordot_at_one_axis_is_matmul_and_at_zero_is_outer,
)
from test_tensor_products import (
    test_tensordot_contracts_two_axes_of_a_rank_three_tensor as test_tensor_products__test_tensordot_contracts_two_axes_of_a_rank_three_tensor,
)
from test_tensor_products import (
    test_tensordot_leaves_one_column_at_every_row_count as test_tensor_products__test_tensordot_leaves_one_column_at_every_row_count,
)
from test_tensor_products import (
    test_tensordot_raises_on_mismatched_contracted_extents as test_tensor_products__test_tensordot_raises_on_mismatched_contracted_extents,
)
from test_tensor_products import (
    test_tensorsolve_recovers_a_known_solution as test_tensor_products__test_tensorsolve_recovers_a_known_solution,
)
from test_tensor_products import (
    test_tensorinv_inverts_with_respect_to_tensordot as test_tensor_products__test_tensorinv_inverts_with_respect_to_tensordot,
)
from test_tensorlike_linalg import (
    test_cholesky_of_a_view_block_matches_the_owned_block as test_tensorlike_linalg__test_cholesky_of_a_view_block_matches_the_owned_block,
)
from test_tensorlike_linalg import (
    test_solve_and_det_accept_a_view as test_tensorlike_linalg__test_solve_and_det_accept_a_view,
)
from test_tensorlike_linalg import (
    test_matmul_and_transpose_accept_views as test_tensorlike_linalg__test_matmul_and_transpose_accept_views,
)


def main() raises:
    var suite = TestSuite()
    # tests/linalg/test_banded.mojo
    suite.test[test_banded__test_solve_banded_matches_the_dense_solve]()
    suite.test[
        test_banded__test_solve_banded_at_bandwidth_one_agrees_with_tridiagonal_solve
    ]()
    suite.test[test_banded__test_solve_banded_pivots]()
    suite.test[test_banded__test_a_singular_band_raises]()
    suite.test[test_banded__test_solveh_banded_matches_solve_banded]()
    suite.test[test_banded__test_the_lower_and_upper_forms_agree]()
    suite.test[
        test_banded__test_cholesky_banded_then_cho_solve_banded_is_solveh_banded
    ]()
    suite.test[test_banded__test_an_indefinite_matrix_raises]()
    suite.test[test_banded__test_solve_toeplitz_matches_the_dense_solve]()
    suite.test[test_banded__test_solve_toeplitz_on_a_symmetric_system]()
    suite.test[test_banded__test_a_zero_leading_entry_raises]()
    suite.test[test_banded__test_solve_circulant_matches_the_dense_solve]()
    suite.test[
        test_banded__test_solve_circulant_at_a_non_power_of_two_matches_scipy
    ]()
    suite.test[test_banded__test_solve_circulant_residual_is_zero]()
    suite.test[test_banded__test_a_singular_circulant_raises]()
    # tests/linalg/test_linalg.mojo
    suite.test[test_linalg__test_cholesky_reproduces_the_matrix]()
    suite.test[test_linalg__test_cholesky_upper_triangle_is_zero]()
    suite.test[test_linalg__test_cholesky_solve_matches_the_general_solve]()
    suite.test[test_linalg__test_solve_reproduces_the_right_hand_side]()
    suite.test[test_linalg__test_solve_matches_a_known_answer]()
    suite.test[test_linalg__test_lu_factors_reproduce_the_matrix]()
    suite.test[test_linalg__test_inverse_produces_the_identity]()
    suite.test[test_linalg__test_determinant_matches_the_cofactor_expansion]()
    suite.test[test_linalg__test_determinant_is_multiplicative]()
    suite.test[test_linalg__test_unpivoted_lu_fails_on_a_zero_pivot]()
    suite.test[test_linalg__test_slogdet_cholesky_matches_the_determinant]()
    suite.test[
        test_linalg__test_substitutions_invert_their_triangular_systems
    ]()
    suite.test[
        test_linalg__test_unit_diagonal_substitution_ignores_the_stored_diagonal
    ]()
    suite.test[test_linalg__test_tridiagonal_solve_matches_a_dense_solve]()
    suite.test[test_linalg__test_tridiagonal_solve_on_the_spline_system]()
    suite.test[test_linalg__test_determinant_is_differentiable]()
    suite.test[test_linalg__test_cholesky_log_det_is_differentiable]()
    suite.test[test_linalg__test_solve_is_differentiable]()
    suite.test[
        test_linalg__test_compensated_cholesky_beats_plain_at_the_same_dtype
    ]()
    suite.test[test_linalg__test_simd_lanes_factor_independent_matrices]()
    suite.test[test_linalg__test_trace_sums_the_diagonal]()
    suite.test[
        test_linalg__test_frobenius_norm_matches_the_entrywise_definition
    ]()
    suite.test[test_linalg__test_norm_1_is_the_largest_absolute_column_sum]()
    suite.test[test_linalg__test_norm_inf_is_the_largest_absolute_row_sum]()
    suite.test[
        test_linalg__test_norm_inf_of_a_symmetric_matrix_equals_its_norm_1
    ]()
    suite.test[test_linalg__test_qr_reconstructs_the_original_matrix]()
    suite.test[test_linalg__test_qr_r_is_upper_triangular]()
    suite.test[test_linalg__test_qr_q_is_orthogonal]()
    suite.test[
        test_linalg__test_qr_of_a_symmetric_positive_definite_matrix_reconstructs_it
    ]()
    suite.test[test_linalg__test_qr_differentiates_through_at_dual]()
    suite.test[test_linalg__test_dot_is_the_inner_product]()
    suite.test[test_linalg__test_nrm2_is_the_euclidean_length]()
    suite.test[test_linalg__test_nrm2_squared_equals_dot_with_itself]()
    suite.test[test_linalg__test_outer_product_has_rank_one_structure]()
    suite.test[
        test_linalg__test_compensated_dot_beats_plain_on_a_long_cancelling_sum
    ]()
    suite.test[test_linalg__test_eigh_eigenvalues_sum_to_the_trace]()
    suite.test[test_linalg__test_eigh_satisfies_the_eigenvalue_equation]()
    suite.test[test_linalg__test_eigh_eigenvectors_are_orthonormal]()
    suite.test[
        test_linalg__test_eigh_of_a_diagonal_matrix_returns_its_diagonal
    ]()
    suite.test[test_linalg__test_eigh_of_the_identity_is_all_ones]()
    suite.test[
        test_linalg__test_eigh_positive_definite_matrix_has_positive_eigenvalues
    ]()
    suite.test[test_linalg__test_svd_reconstructs_the_matrix]()
    suite.test[test_linalg__test_svd_singular_values_are_non_negative]()
    suite.test[test_linalg__test_svd_left_factor_is_orthonormal]()
    suite.test[test_linalg__test_svd_right_factor_is_orthonormal]()
    suite.test[
        test_linalg__test_svd_of_a_symmetric_matrix_matches_its_eigenvalue_magnitudes
    ]()
    suite.test[
        test_linalg__test_svd_of_a_singular_matrix_reports_a_zero_singular_value
    ]()
    suite.test[test_linalg__test_pinv_of_an_invertible_matrix_is_its_inverse]()
    suite.test[
        test_linalg__test_pinv_agrees_with_inverse_on_a_well_conditioned_matrix
    ]()
    suite.test[test_linalg__test_pinv_of_a_singular_matrix_stays_finite]()
    suite.test[test_linalg__test_pinv_satisfies_the_moore_penrose_identity]()
    suite.test[test_linalg__test_cond_of_the_identity_is_one]()
    suite.test[test_linalg__test_cond_is_the_ratio_of_extreme_singular_values]()
    suite.test[test_linalg__test_cond_of_a_scaled_identity_is_still_one]()
    suite.test[test_linalg__test_eigh_is_differentiable_at_dual]()
    suite.test[test_linalg__test_eigh_derivative_survives_float32]()
    suite.test[test_linalg__test_eigh_float32_derivative_sums_to_the_trace]()
    suite.test[test_linalg__test_lstsq_recovers_an_exactly_fitting_line]()
    suite.test[test_linalg__test_lstsq_residual_is_orthogonal_to_the_columns]()
    suite.test[test_linalg__test_lstsq_at_a_square_system_is_the_solve]()
    suite.test[test_linalg__test_lstsq_differentiates_through_the_fit]()
    suite.test[
        test_linalg__test_pivoting_factors_the_matrix_the_unpivoted_lu_cannot_start_on
    ]()
    suite.test[
        test_linalg__test_a_pivoted_solve_reproduces_its_right_hand_side
    ]()
    suite.test[
        test_linalg__test_one_factorization_serves_several_right_hand_sides
    ]()
    suite.test[
        test_linalg__test_the_permuted_matrix_is_the_product_of_its_factors
    ]()
    suite.test[
        test_linalg__test_pivoting_beats_the_unpivoted_route_on_a_small_pivot
    ]()
    suite.test[
        test_linalg__test_eigvals_of_a_triangular_matrix_are_its_diagonal
    ]()
    suite.test[
        test_linalg__test_eigvals_of_a_quarter_turn_are_the_imaginary_units
    ]()
    suite.test[
        test_linalg__test_eigvals_sum_to_the_trace_and_multiply_to_the_determinant
    ]()
    suite.test[
        test_linalg__test_eigvals_agrees_with_eigh_on_a_symmetric_matrix
    ]()
    suite.test[
        test_linalg__test_eigvals_recovers_a_mixed_real_and_complex_spectrum
    ]()
    suite.test[test_linalg__test_asum_and_axpy_agree_with_their_definitions]()
    suite.test[
        test_linalg__test_hessenberg_is_zero_below_the_subdiagonal_and_keeps_the_spectrum
    ]()
    suite.test[
        test_linalg__test_hessenberg_of_a_symmetric_matrix_is_tridiagonal
    ]()
    # tests/linalg/test_matfuncs.mojo
    suite.test[test_matfuncs__test_expm_of_a_diagonal_matrix]()
    suite.test[test_matfuncs__test_expm_of_zero_is_the_identity]()
    suite.test[test_matfuncs__test_expm_of_a_nilpotent_matrix_is_a_finite_sum]()
    suite.test[
        test_matfuncs__test_expm_of_the_rotation_generator_is_a_rotation
    ]()
    suite.test[test_matfuncs__test_expm_a_times_expm_minus_a_is_the_identity]()
    suite.test[test_matfuncs__test_expm_scales_for_a_large_norm]()
    suite.test[test_matfuncs__test_array_expm_agrees_with_the_tensor_tier]()
    suite.test[test_matfuncs__test_array_expm_of_the_rotation_generator]()
    suite.test[test_matfuncs__test_expm_differentiates_at_dual]()
    suite.test[test_matfuncs__test_sqrtm_squares_back_to_the_matrix]()
    suite.test[test_matfuncs__test_sqrtm_of_a_diagonal_matrix]()
    # tests/linalg/test_norms_and_rank.mojo
    suite.test[test_norms_and_rank__test_vector_two_norm_is_exactly_nrm2]()
    suite.test[test_norms_and_rank__test_vector_two_norm_value]()
    suite.test[test_norms_and_rank__test_vector_two_norm_is_the_default]()
    suite.test[test_norms_and_rank__test_vector_one_norm]()
    suite.test[test_norms_and_rank__test_vector_infinity_norms]()
    suite.test[test_norms_and_rank__test_the_matrix_overload_still_resolves]()
    suite.test[test_norms_and_rank__test_eigvalsh_is_eigh_without_the_vectors]()
    suite.test[test_norms_and_rank__test_svdvals_is_svd_without_the_vectors]()
    suite.test[test_norms_and_rank__test_eigenvalues_sum_to_the_trace]()
    suite.test[test_norms_and_rank__test_matrix_rank_of_a_full_rank_matrix]()
    suite.test[
        test_norms_and_rank__test_matrix_rank_of_a_rank_deficient_matrix
    ]()
    suite.test[test_norms_and_rank__test_matrix_rank_counts_per_lane]()
    # tests/linalg/test_panel.mojo
    suite.test[test_panel__test_potrf_diag_factors_the_whole_block]()
    suite.test[test_panel__test_potrf_diag_leaves_the_upper_triangle_alone]()
    suite.test[test_panel__test_potrf_diag_factors_an_offset_block]()
    suite.test[
        test_panel__test_potrf_diag_flags_a_matrix_that_is_not_positive_definite
    ]()
    suite.test[
        test_panel__test_trsm_right_lower_t_solves_against_the_diagonal_block
    ]()
    suite.test[test_panel__test_trsm_left_lower_unit_solves_the_block_row]()
    suite.test[
        test_panel__test_getrf_panel_gives_lu_of_the_columns_it_factored
    ]()
    suite.test[test_panel__test_getrf_panel_picks_the_largest_pivot]()
    suite.test[test_panel__test_pack_block_copies_a_strided_block_densely]()
    suite.test[
        test_panel__test_pack_block_copies_a_width_the_simd_lanes_do_not_divide
    ]()
    suite.test[test_panel__test_pack_block_transposed_copies_a_ragged_width]()
    suite.test[
        test_panel__test_getrf2_agrees_with_the_single_block_panel_at_every_base
    ]()
    # tests/linalg/test_products.mojo
    suite.test[
        test_products__test_inner_equals_matmul_against_an_explicit_transpose
    ]()
    suite.test[test_products__test_inner_is_the_gram_matrix_of_the_rows]()
    suite.test[test_products__test_array_inner_agrees_with_the_tensor_tier]()
    suite.test[test_products__test_kron_matches_a_hand_written_loop]()
    suite.test[
        test_products__test_kron_with_the_identity_tiles_the_other_operand
    ]()
    suite.test[test_products__test_array_kron_agrees_with_the_tensor_tier]()
    suite.test[test_products__test_matrix_power_three_equals_two_matmuls]()
    suite.test[test_products__test_matrix_power_zero_is_the_identity]()
    suite.test[test_products__test_matrix_power_one_is_the_matrix]()
    suite.test[test_products__test_an_even_power_exercises_the_squaring_path]()
    suite.test[
        test_products__test_array_matrix_power_agrees_with_the_tensor_tier
    ]()
    # tests/linalg/test_slogdet.mojo
    suite.test[test_slogdet__test_slogdet_reproduces_det]()
    suite.test[test_slogdet__test_slogdet_reports_the_sign_separately]()
    suite.test[
        test_slogdet__test_a_singular_matrix_gives_sign_zero_and_minus_infinity
    ]()
    suite.test[test_slogdet__test_slogdet_survives_where_det_overflows]()
    suite.test[test_slogdet__test_the_two_tiers_agree]()
    suite.test[
        test_slogdet__test_the_array_tier_reports_a_singular_matrix_too
    ]()
    suite.test[test_slogdet__test_the_factor_can_be_reused_for_both]()
    # tests/linalg/test_special_matrices.mojo
    suite.test[test_special_matrices__test_toeplitz_two_argument_form]()
    suite.test[test_special_matrices__test_toeplitz_symmetric_form]()
    suite.test[
        test_special_matrices__test_the_symmetric_form_equals_the_two_argument_one
    ]()
    suite.test[
        test_special_matrices__test_hankel_is_constant_along_antidiagonals
    ]()
    suite.test[test_special_matrices__test_circulant_rotates_each_column]()
    suite.test[
        test_special_matrices__test_a_symmetric_circulant_is_its_own_toeplitz
    ]()
    suite.test[
        test_special_matrices__test_companion_eigenvalues_are_the_polynomial_roots
    ]()
    suite.test[test_special_matrices__test_companion_has_the_documented_shape]()
    suite.test[test_special_matrices__test_hilbert_entries]()
    suite.test[test_special_matrices__test_hilbert_is_symmetric]()
    suite.test[
        test_special_matrices__test_block_diag_places_the_blocks_and_zeros_the_rest
    ]()
    suite.test[
        test_special_matrices__test_khatri_rao_is_kron_column_by_column
    ]()
    suite.test[
        test_special_matrices__test_convolution_matrix_times_a_vector_is_a_convolution
    ]()
    suite.test[test_special_matrices__test_pascal_symmetric_lower_and_upper]()
    suite.test[
        test_special_matrices__test_invpascal_is_the_inverse_in_every_kind
    ]()
    suite.test[
        test_special_matrices__test_hadamard_matches_sylvesters_construction_and_is_orthogonal
    ]()
    suite.test[
        test_special_matrices__test_helmert_rows_are_orthonormal_contrasts
    ]()
    suite.test[
        test_special_matrices__test_fiedler_is_the_absolute_difference_table
    ]()
    suite.test[
        test_special_matrices__test_fiedler_companion_has_the_polynomial_roots_as_eigenvalues
    ]()
    suite.test[
        test_special_matrices__test_leslie_places_fecundities_and_survivals
    ]()
    # tests/linalg/test_tensor_eigen.mojo
    suite.test[
        test_tensor_eigen__test_sytrd_leaves_q_transpose_a_q_tridiagonal
    ]()
    suite.test[test_tensor_eigen__test_sytrd_reports_the_band_it_produced]()
    suite.test[
        test_tensor_eigen__test_sytrd_is_a_similarity_so_q_t_q_transpose_reconstructs
    ]()
    suite.test[test_tensor_eigen__test_sytrd_q_is_orthogonal]()
    suite.test[
        test_tensor_eigen__test_sytrd_q_matches_the_unblocked_accumulation
    ]()
    suite.test[test_tensor_eigen__test_sytrd_q_at_a_ragged_panel_width]()
    suite.test[
        test_tensor_eigen__test_sytrd_blocking_does_not_change_the_answer
    ]()
    suite.test[test_tensor_eigen__test_sytrd_at_a_ragged_reduction_panel]()
    suite.test[test_tensor_eigen__test_sytrd_preserves_the_trace]()
    suite.test[
        test_tensor_eigen__test_sytrd_leaves_an_already_tridiagonal_matrix_alone
    ]()
    suite.test[test_tensor_eigen__test_sytrd_at_the_sizes_with_nothing_to_do]()
    suite.test[
        test_tensor_eigen__test_eigvalsh_of_a_diagonal_matrix_is_its_diagonal_ascending
    ]()
    suite.test[
        test_tensor_eigen__test_eigvalsh_matches_the_known_spectrum_of_hilbert_four
    ]()
    suite.test[
        test_tensor_eigen__test_eigvalsh_agrees_with_the_array_tier_as_a_multiset
    ]()
    suite.test[
        test_tensor_eigen__test_eigvalsh_sums_to_the_trace_and_multiplies_to_the_determinant
    ]()
    suite.test[
        test_tensor_eigen__test_eigvalsh_handles_a_matrix_with_repeated_eigenvalues
    ]()
    suite.test[
        test_tensor_eigen__test_eigh_satisfies_the_eigenvalue_equation_for_every_pair
    ]()
    suite.test[test_tensor_eigen__test_eigh_eigenvectors_are_orthonormal]()
    suite.test[test_tensor_eigen__test_eigh_reconstructs_a_from_its_factors]()
    suite.test[
        test_tensor_eigen__test_eigh_values_are_ascending_and_equal_eigvalsh
    ]()
    suite.test[
        test_tensor_eigen__test_eigh_of_a_diagonal_matrix_returns_permuted_identity_vectors
    ]()
    suite.test[
        test_tensor_eigen__test_eigh_blocking_does_not_change_the_answer
    ]()
    suite.test[test_tensor_eigen__test_eigh_ragged_window_sizes]()
    suite.test[test_tensor_eigen__test_eigh_at_n_one_and_two]()
    suite.test[
        test_tensor_eigen__test_gebrd_leaves_q_transpose_a_p_upper_bidiagonal
    ]()
    suite.test[test_tensor_eigen__test_gebrd_q_and_p_are_orthogonal]()
    suite.test[
        test_tensor_eigen__test_bidiagonal_q_and_p_match_the_unblocked_walk
    ]()
    suite.test[
        test_tensor_eigen__test_gebrd_blocking_does_not_change_the_answer
    ]()
    suite.test[test_tensor_eigen__test_gebrd_at_a_ragged_panel]()
    suite.test[test_tensor_eigen__test_svdvals_matches_scipy_on_a_tall_matrix]()
    suite.test[test_tensor_eigen__test_svdvals_matches_scipy_on_hilbert_four]()
    suite.test[
        test_tensor_eigen__test_svdvals_agrees_with_the_array_tier_as_a_multiset
    ]()
    suite.test[test_tensor_eigen__test_svd_reconstructs_a_from_its_factors]()
    suite.test[
        test_tensor_eigen__test_svd_factors_are_orthonormal_and_values_descending
    ]()
    suite.test[test_tensor_eigen__test_svd_values_equal_svdvals]()
    suite.test[
        test_tensor_eigen__test_svd_blocking_does_not_change_the_answer
    ]()
    suite.test[test_tensor_eigen__test_svd_at_n_one_two_three]()
    suite.test[test_tensor_eigen__test_svdvals_finds_a_rank_deficient_matrix]()
    suite.test[test_tensor_eigen__test_bdsqr_matches_the_golub_kahan_oracle]()
    suite.test[
        test_tensor_eigen__test_svd_of_a_rank_deficient_matrix_reconstructs_it
    ]()
    suite.test[
        test_tensor_eigen__test_pinv_inverts_a_full_rank_tall_matrix_from_the_left
    ]()
    suite.test[test_tensor_eigen__test_pinv_of_a_square_matrix_is_its_inverse]()
    suite.test[
        test_tensor_eigen__test_pinv_of_a_rank_deficient_matrix_matches_scipy_and_penrose
    ]()
    suite.test[test_tensor_eigen__test_cond_matches_scipy_on_hilbert_four]()
    suite.test[
        test_tensor_eigen__test_cond_of_a_singular_matrix_is_infinite_or_huge
    ]()
    suite.test[
        test_tensor_eigen__test_matrix_rank_counts_independent_directions
    ]()
    suite.test[
        test_tensor_eigen__test_matrix_rank_honours_an_explicit_tolerance
    ]()
    suite.test[test_tensor_eigen__test_lstsq_svd_agrees_with_qr_at_full_rank]()
    suite.test[
        test_tensor_eigen__test_lstsq_svd_returns_the_minimum_norm_solution_when_rank_deficient
    ]()
    suite.test[
        test_tensor_eigen__test_orth_returns_a_basis_of_the_right_width_and_is_orthonormal
    ]()
    suite.test[
        test_tensor_eigen__test_orth_of_a_full_rank_matrix_has_every_column
    ]()
    suite.test[
        test_tensor_eigen__test_null_space_is_annihilated_by_the_matrix
    ]()
    suite.test[
        test_tensor_eigen__test_null_space_of_a_full_rank_matrix_is_empty
    ]()
    suite.test[
        test_tensor_eigen__test_polar_factors_reconstruct_and_have_their_defining_properties
    ]()
    suite.test[
        test_tensor_eigen__test_hessenberg_is_zero_below_the_subdiagonal_and_a_similarity
    ]()
    suite.test[
        test_tensor_eigen__test_hessenberg_q_is_orthogonal_at_every_block
    ]()
    suite.test[
        test_tensor_eigen__test_hessenberg_blocking_does_not_change_the_answer
    ]()
    suite.test[test_tensor_eigen__test_hessenberg_at_a_ragged_panel]()
    suite.test[test_tensor_eigen__test_hessenberg_of_a_two_by_two_is_itself]()
    suite.test[
        test_tensor_eigen__test_eigvals_matches_scipy_for_a_real_spectrum
    ]()
    suite.test[
        test_tensor_eigen__test_eigvals_matches_scipy_for_two_complex_pairs
    ]()
    suite.test[
        test_tensor_eigen__test_eigvals_of_a_quarter_turn_are_the_imaginary_units
    ]()
    suite.test[
        test_tensor_eigen__test_eigvals_agrees_with_eigvalsh_on_a_symmetric_matrix
    ]()
    suite.test[
        test_tensor_eigen__test_schur_reconstructs_and_is_quasi_triangular
    ]()
    suite.test[
        test_tensor_eigen__test_schur_of_a_real_spectrum_is_triangular_with_the_eigenvalues_on_the_diagonal
    ]()
    suite.test[
        test_tensor_eigen__test_schur_blocking_does_not_change_the_answer
    ]()
    suite.test[test_tensor_eigen__test_schur_at_n_one_and_two]()
    suite.test[test_tensor_eigen__test_schur_ragged_window_sizes]()
    # tests/linalg/test_tensor_linalg.mojo
    suite.test[test_tensor_linalg__test_matmul_matches_hand_computed_product]()
    suite.test[
        test_tensor_linalg__test_tensor_matmul_agrees_with_array_matmul
    ]()
    suite.test[test_tensor_linalg__test_matmul_dynamic_agrees_with_static]()
    suite.test[
        test_tensor_linalg__test_matmul_dynamic_rejects_mismatched_shapes
    ]()
    suite.test[
        test_tensor_linalg__test_matvec_agrees_with_matmul_against_a_column
    ]()
    suite.test[
        test_tensor_linalg__test_matvec_when_the_row_count_is_not_a_lane_multiple
    ]()
    suite.test[
        test_tensor_linalg__test_matvec_odd_rows_and_odd_columns_every_element
    ]()
    suite.test[
        test_tensor_linalg__test_matvec_at_a_k_misaligned_for_the_widest_lane_counts
    ]()
    suite.test[
        test_tensor_linalg__test_matvec_at_float32_where_a_lane_is_sixteen_wide
    ]()
    suite.test[test_tensor_linalg__test_matvec_square_but_not_a_lane_multiple]()
    suite.test[
        test_tensor_linalg__test_batched_matmul_is_one_product_per_leading_index
    ]()
    suite.test[
        test_tensor_linalg__test_batched_matmul_agrees_with_per_matrix_matmul
    ]()
    suite.test[
        test_tensor_linalg__test_tril_and_triu_split_the_matrix_at_the_diagonal
    ]()
    suite.test[
        test_tensor_linalg__test_tril_and_triu_accept_a_non_square_matrix
    ]()
    suite.test[test_tensor_linalg__test_cholesky_reconstructs_the_matrix]()
    suite.test[test_tensor_linalg__test_cholesky_is_lower_triangular]()
    suite.test[
        test_tensor_linalg__test_cholesky_blocking_does_not_change_the_answer
    ]()
    suite.test[
        test_tensor_linalg__test_cholesky_tiling_does_not_change_the_answer
    ]()
    suite.test[
        test_tensor_linalg__test_cholesky_reads_only_the_lower_triangle
    ]()
    suite.test[test_tensor_linalg__test_cholesky_agrees_with_the_array_tier]()
    suite.test[
        test_tensor_linalg__test_cholesky_rejects_a_matrix_that_is_not_positive_definite
    ]()
    suite.test[
        test_tensor_linalg__test_cholesky_reports_a_failure_in_a_later_block
    ]()
    suite.test[
        test_tensor_linalg__test_solve_residual_is_at_machine_precision
    ]()
    suite.test[
        test_tensor_linalg__test_solve_blocking_does_not_change_the_answer
    ]()
    suite.test[test_tensor_linalg__test_solve_agrees_with_the_array_tier]()
    suite.test[
        test_tensor_linalg__test_lu_factor_handles_a_zero_leading_pivot
    ]()
    suite.test[
        test_tensor_linalg__test_lu_factor_is_reusable_across_right_hand_sides
    ]()
    suite.test[
        test_tensor_linalg__test_lu_factor_det_agrees_with_the_array_tier
    ]()
    suite.test[test_tensor_linalg__test_tensor_dot_agrees_with_the_array_dot]()
    suite.test[
        test_tensor_linalg__test_tensor_nrm2_and_asum_agree_with_the_array_versions
    ]()
    suite.test[
        test_tensor_linalg__test_tensor_axpy_agrees_with_the_array_axpy
    ]()
    suite.test[
        test_tensor_linalg__test_tensor_axpy_writes_every_element_of_its_result
    ]()
    suite.test[
        test_tensor_linalg__test_tensor_outer_writes_every_element_of_its_result
    ]()
    suite.test[
        test_tensor_linalg__test_tensor_outer_agrees_with_the_array_outer
    ]()
    suite.test[
        test_tensor_linalg__test_tensor_outer_accepts_a_rectangular_result
    ]()
    suite.test[
        test_tensor_linalg__test_solve_triangular_agrees_with_forward_substitution
    ]()
    suite.test[
        test_tensor_linalg__test_solve_triangular_transposed_solves_against_the_transpose
    ]()
    suite.test[
        test_tensor_linalg__test_solve_triangular_matrix_agrees_with_the_vector_overload
    ]()
    suite.test[
        test_tensor_linalg__test_cholesky_solve_reproduces_the_right_hand_side
    ]()
    suite.test[
        test_tensor_linalg__test_cholesky_solve_agrees_with_the_array_tier
    ]()
    suite.test[
        test_tensor_linalg__test_cholesky_solve_matrix_agrees_with_the_vector_overload
    ]()
    suite.test[
        test_tensor_linalg__test_lu_factor_solves_several_right_hand_sides_at_once
    ]()
    suite.test[
        test_tensor_linalg__test_inverse_times_the_matrix_is_the_identity
    ]()
    suite.test[test_tensor_linalg__test_inverse_agrees_with_the_array_tier]()
    suite.test[
        test_tensor_linalg__test_tensor_det_agrees_with_the_reusable_factorization
    ]()
    suite.test[
        test_tensor_linalg__test_tensor_trace_agrees_with_the_array_trace
    ]()
    suite.test[
        test_tensor_linalg__test_tensor_frobenius_norm_agrees_with_the_array_norm
    ]()
    suite.test[
        test_tensor_linalg__test_tensor_induced_norms_agree_with_the_array_norms
    ]()
    suite.test[
        test_tensor_linalg__test_tensor_frobenius_norm_is_nrm2_of_the_flattened_matrix
    ]()
    suite.test[test_tensor_linalg__test_tensor_qr_reconstructs_the_matrix]()
    suite.test[test_tensor_linalg__test_tensor_qr_q_has_orthonormal_columns]()
    suite.test[test_tensor_linalg__test_tensor_qr_r_is_upper_triangular]()
    suite.test[
        test_tensor_linalg__test_tensor_qr_agrees_with_the_array_tier_up_to_column_signs
    ]()
    suite.test[
        test_tensor_linalg__test_tensor_qr_apply_q_transpose_agrees_with_forming_q
    ]()
    suite.test[
        test_tensor_linalg__test_tensor_qr_solve_agrees_with_the_array_lstsq
    ]()
    suite.test[
        test_tensor_linalg__test_tensor_qr_block_size_does_not_change_the_answer
    ]()
    suite.test[
        test_tensor_linalg__test_tensor_qr_with_a_ragged_last_panel_reconstructs_the_matrix
    ]()
    suite.test[
        test_tensor_linalg__test_tensor_qr_of_a_square_matrix_reconstructs_it
    ]()
    suite.test[
        test_tensor_linalg__test_lstsq_agrees_with_the_factorization_it_wraps
    ]()
    suite.test[test_tensor_linalg__test_lstsq_recovers_an_exact_linear_fit]()
    suite.test[test_tensor_linalg__test_rq_reconstructs_the_matrix]()
    suite.test[
        test_tensor_linalg__test_rq_r_is_upper_triangular_and_q_is_orthogonal
    ]()
    suite.test[test_tensor_linalg__test_rq_of_a_one_by_one_is_the_scalar]()
    # tests/linalg/test_tensor_matfuncs.mojo
    suite.test[
        test_tensor_matfuncs__test_sqrtm_matches_scipy_and_squares_back
    ]()
    suite.test[
        test_tensor_matfuncs__test_sqrtm_of_complex_pairs_is_real_and_matches_scipy
    ]()
    suite.test[
        test_tensor_matfuncs__test_sqrtm_handles_repeated_and_defective_eigenvalues
    ]()
    suite.test[test_tensor_matfuncs__test_logm_matches_scipy_and_inverts_expm]()
    suite.test[
        test_tensor_matfuncs__test_funm_at_exp_agrees_with_expm_including_complex_blocks
    ]()
    suite.test[
        test_tensor_matfuncs__test_funm_raises_on_a_coupled_repeated_eigenvalue
    ]()
    suite.test[
        test_tensor_matfuncs__test_cosm_and_sinm_match_scipy_and_satisfy_the_pythagorean_identity
    ]()
    suite.test[
        test_tensor_matfuncs__test_fractional_matrix_power_matches_scipy_and_sqrtm
    ]()
    suite.test[
        test_tensor_matfuncs__test_tanm_is_the_matrix_quotient_of_sinm_by_cosm
    ]()
    suite.test[
        test_tensor_matfuncs__test_tanm_of_a_diagonal_matrix_is_the_scalar_tangent
    ]()
    # tests/linalg/test_tensor_products.mojo
    suite.test[test_tensor_products__test_cross_of_the_axes_and_antisymmetry]()
    suite.test[test_tensor_products__test_cross_on_rows]()
    suite.test[
        test_tensor_products__test_tensordot_at_one_axis_is_matmul_and_at_zero_is_outer
    ]()
    suite.test[
        test_tensor_products__test_tensordot_contracts_two_axes_of_a_rank_three_tensor
    ]()
    suite.test[
        test_tensor_products__test_tensordot_leaves_one_column_at_every_row_count
    ]()
    suite.test[
        test_tensor_products__test_tensordot_raises_on_mismatched_contracted_extents
    ]()
    suite.test[
        test_tensor_products__test_tensorsolve_recovers_a_known_solution
    ]()
    suite.test[
        test_tensor_products__test_tensorinv_inverts_with_respect_to_tensordot
    ]()
    # tests/linalg/test_tensorlike_linalg.mojo
    suite.test[
        test_tensorlike_linalg__test_cholesky_of_a_view_block_matches_the_owned_block
    ]()
    suite.test[test_tensorlike_linalg__test_solve_and_det_accept_a_view]()
    suite.test[test_tensorlike_linalg__test_matmul_and_transpose_accept_views]()
    suite^.run()
