"""GENERATED by tools/gen_test_aggregates.py -- do not edit.

Aggregates the 9 test files of `tests/stats/` into one compiled
binary, so 9 compiler invocations become one. Run it with
`mojo -I . -I tests/stats` (see tools/run_test_aggregates.sh).

Regenerate with `pixi run tests-gen`; CI fails if this file is out of date
with the tree.
"""

from std.testing import TestSuite
from test_correlation import (
    test_cov_and_corrcoef_match_numpy as test_correlation__test_cov_and_corrcoef_match_numpy,
)
from test_correlation import (
    test_cov_of_a_variable_matrix_matches_numpy as test_correlation__test_cov_of_a_variable_matrix_matches_numpy,
)
from test_correlation import (
    test_cov_honours_ddof_and_bias as test_correlation__test_cov_honours_ddof_and_bias,
)
from test_correlation import (
    test_cov_at_one_variable_and_at_two_observations as test_correlation__test_cov_at_one_variable_and_at_two_observations,
)
from test_correlation import (
    test_cov_at_float32_agrees_with_the_float64_answer as test_correlation__test_cov_at_float32_agrees_with_the_float64_answer,
)
from test_correlation import (
    test_corrcoef_of_a_variable_matrix_matches_numpy as test_correlation__test_corrcoef_of_a_variable_matrix_matches_numpy,
)
from test_correlation import (
    test_pearsonr_spearmanr_and_kendalltau_match_scipy as test_correlation__test_pearsonr_spearmanr_and_kendalltau_match_scipy,
)
from test_correlation import (
    test_linregress_matches_scipy as test_correlation__test_linregress_matches_scipy,
)
from test_correlation import (
    test_rankdata_matches_scipy_under_every_method as test_correlation__test_rankdata_matches_scipy_under_every_method,
)
from test_correlation import (
    test_zscore_matches_scipy as test_correlation__test_zscore_matches_scipy,
)
from test_distributions import (
    test_normal_cdf_at_the_mean_is_one_half as test_distributions__test_normal_cdf_at_the_mean_is_one_half,
)
from test_distributions import (
    test_normal_cdf_is_symmetric as test_distributions__test_normal_cdf_is_symmetric,
)
from test_distributions import (
    test_normal_cdf_matches_known_values as test_distributions__test_normal_cdf_matches_known_values,
)
from test_distributions import (
    test_normal_cdf_keeps_precision_in_the_far_tail as test_distributions__test_normal_cdf_keeps_precision_in_the_far_tail,
)
from test_distributions import (
    test_normal_pdf_is_the_derivative_of_normal_cdf as test_distributions__test_normal_pdf_is_the_derivative_of_normal_cdf,
)
from test_distributions import (
    test_normal_quantile_inverts_normal_cdf as test_distributions__test_normal_quantile_inverts_normal_cdf,
)
from test_distributions import (
    test_normal_quantile_matches_a_known_value as test_distributions__test_normal_quantile_matches_a_known_value,
)
from test_distributions import (
    test_exponential_is_zero_below_its_support as test_distributions__test_exponential_is_zero_below_its_support,
)
from test_distributions import (
    test_exponential_cdf_matches_the_closed_form as test_distributions__test_exponential_cdf_matches_the_closed_form,
)
from test_distributions import (
    test_exponential_is_memoryless as test_distributions__test_exponential_is_memoryless,
)
from test_distributions import (
    test_gamma_with_unit_shape_is_exponential as test_distributions__test_gamma_with_unit_shape_is_exponential,
)
from test_distributions import (
    test_gamma_pdf_is_the_derivative_of_gamma_cdf as test_distributions__test_gamma_pdf_is_the_derivative_of_gamma_cdf,
)
from test_distributions import (
    test_gamma_cdf_matches_a_closed_form as test_distributions__test_gamma_cdf_matches_a_closed_form,
)
from test_distributions import (
    test_gamma_quantile_inverts_gamma_cdf as test_distributions__test_gamma_quantile_inverts_gamma_cdf,
)
from test_distributions import (
    test_gamma_quantile_handles_a_small_shape as test_distributions__test_gamma_quantile_handles_a_small_shape,
)
from test_distributions import (
    test_chi_square_with_two_df_is_exponential as test_distributions__test_chi_square_with_two_df_is_exponential,
)
from test_distributions import (
    test_chi_square_critical_value as test_distributions__test_chi_square_critical_value,
)
from test_distributions import (
    test_chi_square_pdf_is_the_derivative_of_its_cdf as test_distributions__test_chi_square_pdf_is_the_derivative_of_its_cdf,
)
from test_distributions import (
    test_beta_with_unit_parameters_is_uniform as test_distributions__test_beta_with_unit_parameters_is_uniform,
)
from test_distributions import (
    test_beta_cdf_matches_an_exact_polynomial as test_distributions__test_beta_cdf_matches_an_exact_polynomial,
)
from test_distributions import (
    test_beta_cdf_reflection as test_distributions__test_beta_cdf_reflection,
)
from test_distributions import (
    test_beta_pdf_is_the_derivative_of_beta_cdf as test_distributions__test_beta_pdf_is_the_derivative_of_beta_cdf,
)
from test_distributions import (
    test_beta_quantile_inverts_beta_cdf as test_distributions__test_beta_quantile_inverts_beta_cdf,
)
from test_distributions import (
    test_beta_quantile_is_symmetric_at_the_median as test_distributions__test_beta_quantile_is_symmetric_at_the_median,
)
from test_distributions import (
    test_student_t_with_one_df_is_cauchy as test_distributions__test_student_t_with_one_df_is_cauchy,
)
from test_distributions import (
    test_student_t_cdf_is_symmetric as test_distributions__test_student_t_cdf_is_symmetric,
)
from test_distributions import (
    test_student_t_cdf_at_zero_is_one_half as test_distributions__test_student_t_cdf_at_zero_is_one_half,
)
from test_distributions import (
    test_student_t_pdf_is_the_derivative_of_its_cdf as test_distributions__test_student_t_pdf_is_the_derivative_of_its_cdf,
)
from test_distributions import (
    test_student_t_quantile_matches_a_table_value as test_distributions__test_student_t_quantile_matches_a_table_value,
)
from test_distributions import (
    test_student_t_approaches_the_normal_for_large_df as test_distributions__test_student_t_approaches_the_normal_for_large_df,
)
from test_distributions import (
    test_f_cdf_matches_numerical_integration as test_distributions__test_f_cdf_matches_numerical_integration,
)
from test_distributions import (
    test_f_relates_to_student_t as test_distributions__test_f_relates_to_student_t,
)
from test_distributions import (
    test_f_pdf_is_the_derivative_of_f_cdf as test_distributions__test_f_pdf_is_the_derivative_of_f_cdf,
)
from test_distributions import (
    test_f_is_zero_below_its_support as test_distributions__test_f_is_zero_below_its_support,
)
from test_distributions import (
    test_poisson_cdf_equals_the_sum_of_its_pmf as test_distributions__test_poisson_cdf_equals_the_sum_of_its_pmf,
)
from test_distributions import (
    test_poisson_pmf_matches_the_closed_form as test_distributions__test_poisson_pmf_matches_the_closed_form,
)
from test_distributions import (
    test_binomial_cdf_equals_the_sum_of_its_pmf as test_distributions__test_binomial_cdf_equals_the_sum_of_its_pmf,
)
from test_distributions import (
    test_binomial_pmf_sums_to_one as test_distributions__test_binomial_pmf_sums_to_one,
)
from test_distributions import (
    test_binomial_with_one_trial_is_bernoulli as test_distributions__test_binomial_with_one_trial_is_bernoulli,
)
from test_distributions import (
    test_survival_functions_complement_their_cdfs as test_distributions__test_survival_functions_complement_their_cdfs,
)
from test_distributions import (
    test_survival_functions_match_scipy as test_distributions__test_survival_functions_match_scipy,
)
from test_distributions import (
    test_survival_functions_are_one_below_the_support as test_distributions__test_survival_functions_are_one_below_the_support,
)
from test_distributions import (
    test_inverse_survival_functions_match_scipy as test_distributions__test_inverse_survival_functions_match_scipy,
)
from test_distributions import (
    test_exponential_quantile_is_the_closed_form_and_inverts_its_cdf as test_distributions__test_exponential_quantile_is_the_closed_form_and_inverts_its_cdf,
)
from test_distributions import (
    test_f_quantile_inverts_f_cdf_and_matches_a_table_value as test_distributions__test_f_quantile_inverts_f_cdf_and_matches_a_table_value,
)
from test_distributions import (
    test_poisson_quantile_is_the_smallest_k_with_cdf_at_least_p as test_distributions__test_poisson_quantile_is_the_smallest_k_with_cdf_at_least_p,
)
from test_distributions import (
    test_binomial_quantile_is_the_smallest_k_with_cdf_at_least_p as test_distributions__test_binomial_quantile_is_the_smallest_k_with_cdf_at_least_p,
)
from test_distributions import (
    test_discrete_survival_functions_match_scipy_and_their_cdfs as test_distributions__test_discrete_survival_functions_match_scipy_and_their_cdfs,
)
from test_distributions import (
    test_log_densities_match_scipy_and_are_the_log_of_the_density as test_distributions__test_log_densities_match_scipy_and_are_the_log_of_the_density,
)
from test_distributions import (
    test_log_densities_are_finite_and_exp_to_zero_off_the_support as test_distributions__test_log_densities_are_finite_and_exp_to_zero_off_the_support,
)
from test_distributions import (
    test_log_cdfs_are_the_log_of_the_cdf as test_distributions__test_log_cdfs_are_the_log_of_the_cdf,
)
from test_distributions import (
    test_simd_lanes_are_independent as test_distributions__test_simd_lanes_are_independent,
)
from test_distributions import (
    test_a_distribution_parameter_can_be_differentiated as test_distributions__test_a_distribution_parameter_can_be_differentiated,
)
from test_histograms import (
    test_histogram_matches_numpy as test_histograms__test_histogram_matches_numpy,
)
from test_histograms import (
    test_histogram_with_range_edges_density_and_weights as test_histograms__test_histogram_with_range_edges_density_and_weights,
)
from test_histograms import (
    test_histogram2d_and_histogramdd_agree_with_numpy as test_histograms__test_histogram2d_and_histogramdd_agree_with_numpy,
)
from test_histograms import (
    test_bincount_matches_numpy as test_histograms__test_bincount_matches_numpy,
)
from test_histograms import (
    test_digitize_matches_numpy as test_histograms__test_digitize_matches_numpy,
)
from test_hypothesis import (
    test_skew_and_kurtosis_match_scipy as test_hypothesis__test_skew_and_kurtosis_match_scipy,
)
from test_hypothesis import (
    test_sem_gmean_hmean_trim_mean_and_entropy_match_scipy as test_hypothesis__test_sem_gmean_hmean_trim_mean_and_entropy_match_scipy,
)
from test_hypothesis import (
    test_describe_matches_scipy as test_hypothesis__test_describe_matches_scipy,
)
from test_hypothesis import (
    test_t_tests_match_scipy as test_hypothesis__test_t_tests_match_scipy,
)
from test_hypothesis import (
    test_chisquare_matches_scipy as test_hypothesis__test_chisquare_matches_scipy,
)
from test_hypothesis import (
    test_ks_1samp_matches_scipy as test_hypothesis__test_ks_1samp_matches_scipy,
)
from test_hypothesis import (
    test_f_oneway_and_mannwhitneyu_match_scipy as test_hypothesis__test_f_oneway_and_mannwhitneyu_match_scipy,
)
from test_hypothesis import (
    test_ks_2samp_matches_scipy as test_hypothesis__test_ks_2samp_matches_scipy,
)
from test_hypothesis import (
    test_ks_2samp_of_identical_samples_has_no_gap as test_hypothesis__test_ks_2samp_of_identical_samples_has_no_gap,
)
from test_hypothesis import (
    test_wilcoxon_matches_scipy as test_hypothesis__test_wilcoxon_matches_scipy,
)
from test_hypothesis import (
    test_wilcoxon_drops_zero_differences as test_hypothesis__test_wilcoxon_drops_zero_differences,
)
from test_hypothesis import (
    test_wilcoxon_rejects_unpaired_lengths as test_hypothesis__test_wilcoxon_rejects_unpaired_lengths,
)
from test_hypothesis import (
    test_wilcoxon_rejects_an_all_tied_sample as test_hypothesis__test_wilcoxon_rejects_an_all_tied_sample,
)
from test_quantiles import (
    test_quantile_matches_numpy_under_every_method as test_quantiles__test_quantile_matches_numpy_under_every_method,
)
from test_quantiles import (
    test_quantile_at_one_and_two_samples as test_quantiles__test_quantile_at_one_and_two_samples,
)
from test_quantiles import (
    test_quantile_with_ties_and_a_constant_sample as test_quantiles__test_quantile_with_ties_and_a_constant_sample,
)
from test_quantiles import (
    test_vector_quantile_agrees_with_the_scalar_form_on_both_routes as test_quantiles__test_vector_quantile_agrees_with_the_scalar_form_on_both_routes,
)
from test_quantiles import (
    test_quantile_of_a_near_constant_sample_stays_linear as test_quantiles__test_quantile_of_a_near_constant_sample_stays_linear,
)
from test_quantiles import (
    test_selection_agrees_with_a_full_sort_on_duplicate_heavy_data as test_quantiles__test_selection_agrees_with_a_full_sort_on_duplicate_heavy_data,
)
from test_quantiles import (
    test_nan_policies_survive_the_selection_route as test_quantiles__test_nan_policies_survive_the_selection_route,
)
from test_quantiles import (
    test_scalar_quantile_and_percentile_agree_with_the_vector_form as test_quantiles__test_scalar_quantile_and_percentile_agree_with_the_vector_form,
)
from test_quantiles import (
    test_nan_reductions_match_numpy as test_quantiles__test_nan_reductions_match_numpy,
)
from test_quantiles import (
    test_nan_reductions_agree_with_the_plain_ones_without_nans as test_quantiles__test_nan_reductions_agree_with_the_plain_ones_without_nans,
)
from test_quantiles import (
    test_all_nan_input_raises_where_numpy_returns_nan as test_quantiles__test_all_nan_input_raises_where_numpy_returns_nan,
)
from test_quantiles import (
    test_iqr_matches_scipy as test_quantiles__test_iqr_matches_scipy,
)
from test_quantiles import (
    test_ptp_average_and_moment_match_numpy_and_scipy as test_quantiles__test_ptp_average_and_moment_match_numpy_and_scipy,
)
from test_random import (
    test_seed_makes_uniform_draws_reproducible as test_random__test_seed_makes_uniform_draws_reproducible,
)
from test_random import (
    test_seed_makes_normal_draws_reproducible as test_random__test_seed_makes_normal_draws_reproducible,
)
from test_random import (
    test_seed_makes_exponential_draws_reproducible as test_random__test_seed_makes_exponential_draws_reproducible,
)
from test_random import (
    test_uniform_draws_land_within_the_requested_range as test_random__test_uniform_draws_land_within_the_requested_range,
)
from test_random import (
    test_uniform_sample_mean_matches_the_midpoint_within_tolerance as test_random__test_uniform_sample_mean_matches_the_midpoint_within_tolerance,
)
from test_random import (
    test_normal_sample_mean_and_stddev_match_the_parameters as test_random__test_normal_sample_mean_and_stddev_match_the_parameters,
)
from test_random import (
    test_exponential_sample_mean_matches_its_scale as test_random__test_exponential_sample_mean_matches_its_scale,
)
from test_random import (
    test_exponential_draws_are_never_negative as test_random__test_exponential_draws_are_never_negative,
)
from test_random import (
    test_two_generators_with_one_seed_agree as test_random__test_two_generators_with_one_seed_agree,
)
from test_random import (
    test_a_generator_advances_between_draws as test_random__test_a_generator_advances_between_draws,
)
from test_random import (
    test_a_generator_is_unaffected_by_the_global_seed as test_random__test_a_generator_is_unaffected_by_the_global_seed,
)
from test_random import (
    test_the_stream_layout_is_philox_word_i as test_random__test_the_stream_layout_is_philox_word_i,
)
from test_random import (
    test_a_generator_ignores_the_global_seed as test_random__test_a_generator_ignores_the_global_seed,
)
from test_random import (
    test_multi_dimensional_shapes_fill_every_element as test_random__test_multi_dimensional_shapes_fill_every_element,
)
from test_random import (
    test_randint_is_integral_and_in_range as test_random__test_randint_is_integral_and_in_range,
)
from test_random import (
    test_randbool_hits_its_probability as test_random__test_randbool_hits_its_probability,
)
from test_statistics import (
    test_sum_matches_hand_computed_total as test_statistics__test_sum_matches_hand_computed_total,
)
from test_statistics import (
    test_prod_matches_hand_computed_product as test_statistics__test_prod_matches_hand_computed_product,
)
from test_statistics import (
    test_min_returns_the_smallest_element as test_statistics__test_min_returns_the_smallest_element,
)
from test_statistics import (
    test_max_returns_the_largest_element as test_statistics__test_max_returns_the_largest_element,
)
from test_statistics import (
    test_the_reductions_agree_with_a_host_walk_on_a_longer_vector as test_statistics__test_the_reductions_agree_with_a_host_walk_on_a_longer_vector,
)
from test_statistics import (
    test_mean_matches_hand_computed_average as test_statistics__test_mean_matches_hand_computed_average,
)
from test_statistics import (
    test_median_of_an_even_count_averages_the_two_middle_values as test_statistics__test_median_of_an_even_count_averages_the_two_middle_values,
)
from test_statistics import (
    test_median_of_an_odd_count_returns_the_middle_value as test_statistics__test_median_of_an_odd_count_returns_the_middle_value,
)
from test_statistics import (
    test_mode_returns_the_most_frequent_value as test_statistics__test_mode_returns_the_most_frequent_value,
)
from test_statistics import (
    test_mode_returns_the_smallest_among_tied_values as test_statistics__test_mode_returns_the_smallest_among_tied_values,
)
from test_statistics import (
    test_argmax_returns_the_index_of_the_largest_element as test_statistics__test_argmax_returns_the_index_of_the_largest_element,
)
from test_statistics import (
    test_argmin_returns_the_index_of_the_smallest_element as test_statistics__test_argmin_returns_the_index_of_the_smallest_element,
)
from test_statistics import (
    test_cumprod_matches_the_running_product as test_statistics__test_cumprod_matches_the_running_product,
)
from test_statistics import (
    test_floatlike_mean_matches_hand_computed_average as test_statistics__test_floatlike_mean_matches_hand_computed_average,
)
from test_statistics import (
    test_floatlike_variance_defaults_to_population_variance as test_statistics__test_floatlike_variance_defaults_to_population_variance,
)
from test_statistics import (
    test_floatlike_variance_honors_ddof as test_statistics__test_floatlike_variance_honors_ddof,
)
from test_statistics import (
    test_floatlike_stddev_is_the_sqrt_of_variance as test_statistics__test_floatlike_stddev_is_the_sqrt_of_variance,
)
from test_statistics import (
    test_floatlike_cumsum_matches_the_running_sum as test_statistics__test_floatlike_cumsum_matches_the_running_sum,
)
from test_statistics import (
    test_compensated_variance_beats_plain_on_a_long_summation as test_statistics__test_compensated_variance_beats_plain_on_a_long_summation,
)
from test_statistics import (
    test_tensor_variance_recovers_a_small_spread_under_a_large_mean as test_statistics__test_tensor_variance_recovers_a_small_spread_under_a_large_mean,
)
from test_statistics import (
    test_tensor_variance_honors_ddof as test_statistics__test_tensor_variance_honors_ddof,
)
from test_statistics import (
    test_variance_axis_agrees_with_the_separate_entry_points as test_statistics__test_variance_axis_agrees_with_the_separate_entry_points,
)
from test_statistics import (
    test_mean_reduces_the_first_axis as test_statistics__test_mean_reduces_the_first_axis,
)
from test_statistics_axis import (
    test_sum_axis_drops_the_axis_it_folded as test_statistics_axis__test_sum_axis_drops_the_axis_it_folded,
)
from test_statistics_axis import (
    test_sum_axis_sums_the_right_elements as test_statistics_axis__test_sum_axis_sums_the_right_elements,
)
from test_statistics_axis import (
    test_folding_every_axis_matches_the_whole_tensor_sum as test_statistics_axis__test_folding_every_axis_matches_the_whole_tensor_sum,
)
from test_statistics_axis import (
    test_min_max_and_prod_along_an_axis as test_statistics_axis__test_min_max_and_prod_along_an_axis,
)
from test_statistics_axis import (
    test_mean_axis_is_the_sum_divided_by_the_axis_length as test_statistics_axis__test_mean_axis_is_the_sum_divided_by_the_axis_length,
)
from test_statistics_axis import (
    test_an_axis_reduction_accepts_a_run_time_shape as test_statistics_axis__test_an_axis_reduction_accepts_a_run_time_shape,
)
from test_statistics_axis import (
    test_median_along_an_axis_matches_the_whole_tensor_one_per_slice as test_statistics_axis__test_median_along_an_axis_matches_the_whole_tensor_one_per_slice,
)
from test_statistics_axis import (
    test_median_along_an_axis_agrees_with_median_of_one_slice as test_statistics_axis__test_median_along_an_axis_agrees_with_median_of_one_slice,
)
from test_statistics_axis import (
    test_mode_along_an_axis_picks_the_smallest_among_ties as test_statistics_axis__test_mode_along_an_axis_picks_the_smallest_among_ties,
)
from test_statistics_axis import (
    test_argmax_along_the_innermost_axis_is_the_position_in_the_slice as test_statistics_axis__test_argmax_along_the_innermost_axis_is_the_position_in_the_slice,
)
from test_statistics_axis import (
    test_argmax_along_an_outer_axis_takes_the_walked_path as test_statistics_axis__test_argmax_along_an_outer_axis_takes_the_walked_path,
)
from test_statistics_axis import (
    test_argmin_along_both_axes as test_statistics_axis__test_argmin_along_both_axes,
)
from test_statistics_axis import (
    test_argmax_takes_the_first_of_a_tie_on_both_paths as test_statistics_axis__test_argmax_takes_the_first_of_a_tie_on_both_paths,
)
from test_statistics_axis import (
    test_axis_reductions_that_need_a_whole_slice_handle_rank_three as test_statistics_axis__test_axis_reductions_that_need_a_whole_slice_handle_rank_three,
)
from test_statistics_axis import (
    test_cumsum_along_an_axis_keeps_the_shape as test_statistics_axis__test_cumsum_along_an_axis_keeps_the_shape,
)
from test_statistics_axis import (
    test_cumprod_along_an_axis_keeps_the_shape as test_statistics_axis__test_cumprod_along_an_axis_keeps_the_shape,
)
from test_statistics_axis import (
    test_cumsum_with_no_axis_flattens_like_numpy as test_statistics_axis__test_cumsum_with_no_axis_flattens_like_numpy,
)
from test_statistics_axis import (
    test_scanning_the_last_axis_of_a_rank_three_tensor as test_statistics_axis__test_scanning_the_last_axis_of_a_rank_three_tensor,
)
from test_tensor_distributions import (
    test_norm_cdf_over_a_tensor_is_the_scalar_kernel_per_element as test_tensor_distributions__test_norm_cdf_over_a_tensor_is_the_scalar_kernel_per_element,
)
from test_tensor_distributions import (
    test_norm_pdf_and_ppf_over_a_tensor_match_the_scalar_kernels as test_tensor_distributions__test_norm_pdf_and_ppf_over_a_tensor_match_the_scalar_kernels,
)
from test_tensor_distributions import (
    test_every_one_parameter_family_matches_its_scalar_kernel as test_tensor_distributions__test_every_one_parameter_family_matches_its_scalar_kernel,
)
from test_tensor_distributions import (
    test_every_two_parameter_family_matches_its_scalar_kernel as test_tensor_distributions__test_every_two_parameter_family_matches_its_scalar_kernel,
)
from test_tensor_distributions import (
    test_quantiles_over_a_tensor_invert_cdfs_over_a_tensor as test_tensor_distributions__test_quantiles_over_a_tensor_invert_cdfs_over_a_tensor,
)
from test_tensor_distributions import (
    test_a_run_time_shaped_tensor_goes_through_the_same_driver as test_tensor_distributions__test_a_run_time_shaped_tensor_goes_through_the_same_driver,
)
from test_tensor_distributions import (
    test_the_tensor_form_covers_a_length_that_does_not_divide_the_width as test_tensor_distributions__test_the_tensor_form_covers_a_length_that_does_not_divide_the_width,
)
from test_tensor_distributions import (
    test_every_family_agrees_between_static_and_run_time_shapes as test_tensor_distributions__test_every_family_agrees_between_static_and_run_time_shapes,
)


def main() raises:
    var suite = TestSuite()
    # tests/stats/test_correlation.mojo
    suite.test[test_correlation__test_cov_and_corrcoef_match_numpy]()
    suite.test[test_correlation__test_cov_of_a_variable_matrix_matches_numpy]()
    suite.test[test_correlation__test_cov_honours_ddof_and_bias]()
    suite.test[
        test_correlation__test_cov_at_one_variable_and_at_two_observations
    ]()
    suite.test[
        test_correlation__test_cov_at_float32_agrees_with_the_float64_answer
    ]()
    suite.test[
        test_correlation__test_corrcoef_of_a_variable_matrix_matches_numpy
    ]()
    suite.test[
        test_correlation__test_pearsonr_spearmanr_and_kendalltau_match_scipy
    ]()
    suite.test[test_correlation__test_linregress_matches_scipy]()
    suite.test[
        test_correlation__test_rankdata_matches_scipy_under_every_method
    ]()
    suite.test[test_correlation__test_zscore_matches_scipy]()
    # tests/stats/test_distributions.mojo
    suite.test[test_distributions__test_normal_cdf_at_the_mean_is_one_half]()
    suite.test[test_distributions__test_normal_cdf_is_symmetric]()
    suite.test[test_distributions__test_normal_cdf_matches_known_values]()
    suite.test[
        test_distributions__test_normal_cdf_keeps_precision_in_the_far_tail
    ]()
    suite.test[
        test_distributions__test_normal_pdf_is_the_derivative_of_normal_cdf
    ]()
    suite.test[test_distributions__test_normal_quantile_inverts_normal_cdf]()
    suite.test[test_distributions__test_normal_quantile_matches_a_known_value]()
    suite.test[test_distributions__test_exponential_is_zero_below_its_support]()
    suite.test[
        test_distributions__test_exponential_cdf_matches_the_closed_form
    ]()
    suite.test[test_distributions__test_exponential_is_memoryless]()
    suite.test[test_distributions__test_gamma_with_unit_shape_is_exponential]()
    suite.test[
        test_distributions__test_gamma_pdf_is_the_derivative_of_gamma_cdf
    ]()
    suite.test[test_distributions__test_gamma_cdf_matches_a_closed_form]()
    suite.test[test_distributions__test_gamma_quantile_inverts_gamma_cdf]()
    suite.test[test_distributions__test_gamma_quantile_handles_a_small_shape]()
    suite.test[test_distributions__test_chi_square_with_two_df_is_exponential]()
    suite.test[test_distributions__test_chi_square_critical_value]()
    suite.test[
        test_distributions__test_chi_square_pdf_is_the_derivative_of_its_cdf
    ]()
    suite.test[test_distributions__test_beta_with_unit_parameters_is_uniform]()
    suite.test[test_distributions__test_beta_cdf_matches_an_exact_polynomial]()
    suite.test[test_distributions__test_beta_cdf_reflection]()
    suite.test[
        test_distributions__test_beta_pdf_is_the_derivative_of_beta_cdf
    ]()
    suite.test[test_distributions__test_beta_quantile_inverts_beta_cdf]()
    suite.test[
        test_distributions__test_beta_quantile_is_symmetric_at_the_median
    ]()
    suite.test[test_distributions__test_student_t_with_one_df_is_cauchy]()
    suite.test[test_distributions__test_student_t_cdf_is_symmetric]()
    suite.test[test_distributions__test_student_t_cdf_at_zero_is_one_half]()
    suite.test[
        test_distributions__test_student_t_pdf_is_the_derivative_of_its_cdf
    ]()
    suite.test[
        test_distributions__test_student_t_quantile_matches_a_table_value
    ]()
    suite.test[
        test_distributions__test_student_t_approaches_the_normal_for_large_df
    ]()
    suite.test[test_distributions__test_f_cdf_matches_numerical_integration]()
    suite.test[test_distributions__test_f_relates_to_student_t]()
    suite.test[test_distributions__test_f_pdf_is_the_derivative_of_f_cdf]()
    suite.test[test_distributions__test_f_is_zero_below_its_support]()
    suite.test[test_distributions__test_poisson_cdf_equals_the_sum_of_its_pmf]()
    suite.test[test_distributions__test_poisson_pmf_matches_the_closed_form]()
    suite.test[
        test_distributions__test_binomial_cdf_equals_the_sum_of_its_pmf
    ]()
    suite.test[test_distributions__test_binomial_pmf_sums_to_one]()
    suite.test[test_distributions__test_binomial_with_one_trial_is_bernoulli]()
    suite.test[
        test_distributions__test_survival_functions_complement_their_cdfs
    ]()
    suite.test[test_distributions__test_survival_functions_match_scipy]()
    suite.test[
        test_distributions__test_survival_functions_are_one_below_the_support
    ]()
    suite.test[
        test_distributions__test_inverse_survival_functions_match_scipy
    ]()
    suite.test[
        test_distributions__test_exponential_quantile_is_the_closed_form_and_inverts_its_cdf
    ]()
    suite.test[
        test_distributions__test_f_quantile_inverts_f_cdf_and_matches_a_table_value
    ]()
    suite.test[
        test_distributions__test_poisson_quantile_is_the_smallest_k_with_cdf_at_least_p
    ]()
    suite.test[
        test_distributions__test_binomial_quantile_is_the_smallest_k_with_cdf_at_least_p
    ]()
    suite.test[
        test_distributions__test_discrete_survival_functions_match_scipy_and_their_cdfs
    ]()
    suite.test[
        test_distributions__test_log_densities_match_scipy_and_are_the_log_of_the_density
    ]()
    suite.test[
        test_distributions__test_log_densities_are_finite_and_exp_to_zero_off_the_support
    ]()
    suite.test[test_distributions__test_log_cdfs_are_the_log_of_the_cdf]()
    suite.test[test_distributions__test_simd_lanes_are_independent]()
    suite.test[
        test_distributions__test_a_distribution_parameter_can_be_differentiated
    ]()
    # tests/stats/test_histograms.mojo
    suite.test[test_histograms__test_histogram_matches_numpy]()
    suite.test[
        test_histograms__test_histogram_with_range_edges_density_and_weights
    ]()
    suite.test[
        test_histograms__test_histogram2d_and_histogramdd_agree_with_numpy
    ]()
    suite.test[test_histograms__test_bincount_matches_numpy]()
    suite.test[test_histograms__test_digitize_matches_numpy]()
    # tests/stats/test_hypothesis.mojo
    suite.test[test_hypothesis__test_skew_and_kurtosis_match_scipy]()
    suite.test[
        test_hypothesis__test_sem_gmean_hmean_trim_mean_and_entropy_match_scipy
    ]()
    suite.test[test_hypothesis__test_describe_matches_scipy]()
    suite.test[test_hypothesis__test_t_tests_match_scipy]()
    suite.test[test_hypothesis__test_chisquare_matches_scipy]()
    suite.test[test_hypothesis__test_ks_1samp_matches_scipy]()
    suite.test[test_hypothesis__test_f_oneway_and_mannwhitneyu_match_scipy]()
    suite.test[test_hypothesis__test_ks_2samp_matches_scipy]()
    suite.test[test_hypothesis__test_ks_2samp_of_identical_samples_has_no_gap]()
    suite.test[test_hypothesis__test_wilcoxon_matches_scipy]()
    suite.test[test_hypothesis__test_wilcoxon_drops_zero_differences]()
    suite.test[test_hypothesis__test_wilcoxon_rejects_unpaired_lengths]()
    suite.test[test_hypothesis__test_wilcoxon_rejects_an_all_tied_sample]()
    # tests/stats/test_quantiles.mojo
    suite.test[test_quantiles__test_quantile_matches_numpy_under_every_method]()
    suite.test[test_quantiles__test_quantile_at_one_and_two_samples]()
    suite.test[test_quantiles__test_quantile_with_ties_and_a_constant_sample]()
    suite.test[
        test_quantiles__test_vector_quantile_agrees_with_the_scalar_form_on_both_routes
    ]()
    suite.test[
        test_quantiles__test_quantile_of_a_near_constant_sample_stays_linear
    ]()
    suite.test[
        test_quantiles__test_selection_agrees_with_a_full_sort_on_duplicate_heavy_data
    ]()
    suite.test[test_quantiles__test_nan_policies_survive_the_selection_route]()
    suite.test[
        test_quantiles__test_scalar_quantile_and_percentile_agree_with_the_vector_form
    ]()
    suite.test[test_quantiles__test_nan_reductions_match_numpy]()
    suite.test[
        test_quantiles__test_nan_reductions_agree_with_the_plain_ones_without_nans
    ]()
    suite.test[
        test_quantiles__test_all_nan_input_raises_where_numpy_returns_nan
    ]()
    suite.test[test_quantiles__test_iqr_matches_scipy]()
    suite.test[
        test_quantiles__test_ptp_average_and_moment_match_numpy_and_scipy
    ]()
    # tests/stats/test_random.mojo
    suite.test[test_random__test_seed_makes_uniform_draws_reproducible]()
    suite.test[test_random__test_seed_makes_normal_draws_reproducible]()
    suite.test[test_random__test_seed_makes_exponential_draws_reproducible]()
    suite.test[
        test_random__test_uniform_draws_land_within_the_requested_range
    ]()
    suite.test[
        test_random__test_uniform_sample_mean_matches_the_midpoint_within_tolerance
    ]()
    suite.test[
        test_random__test_normal_sample_mean_and_stddev_match_the_parameters
    ]()
    suite.test[test_random__test_exponential_sample_mean_matches_its_scale]()
    suite.test[test_random__test_exponential_draws_are_never_negative]()
    suite.test[test_random__test_two_generators_with_one_seed_agree]()
    suite.test[test_random__test_a_generator_advances_between_draws]()
    suite.test[test_random__test_a_generator_is_unaffected_by_the_global_seed]()
    suite.test[test_random__test_the_stream_layout_is_philox_word_i]()
    suite.test[test_random__test_a_generator_ignores_the_global_seed]()
    suite.test[test_random__test_multi_dimensional_shapes_fill_every_element]()
    suite.test[test_random__test_randint_is_integral_and_in_range]()
    suite.test[test_random__test_randbool_hits_its_probability]()
    # tests/stats/test_statistics.mojo
    suite.test[test_statistics__test_sum_matches_hand_computed_total]()
    suite.test[test_statistics__test_prod_matches_hand_computed_product]()
    suite.test[test_statistics__test_min_returns_the_smallest_element]()
    suite.test[test_statistics__test_max_returns_the_largest_element]()
    suite.test[
        test_statistics__test_the_reductions_agree_with_a_host_walk_on_a_longer_vector
    ]()
    suite.test[test_statistics__test_mean_matches_hand_computed_average]()
    suite.test[
        test_statistics__test_median_of_an_even_count_averages_the_two_middle_values
    ]()
    suite.test[
        test_statistics__test_median_of_an_odd_count_returns_the_middle_value
    ]()
    suite.test[test_statistics__test_mode_returns_the_most_frequent_value]()
    suite.test[
        test_statistics__test_mode_returns_the_smallest_among_tied_values
    ]()
    suite.test[
        test_statistics__test_argmax_returns_the_index_of_the_largest_element
    ]()
    suite.test[
        test_statistics__test_argmin_returns_the_index_of_the_smallest_element
    ]()
    suite.test[test_statistics__test_cumprod_matches_the_running_product]()
    suite.test[
        test_statistics__test_floatlike_mean_matches_hand_computed_average
    ]()
    suite.test[
        test_statistics__test_floatlike_variance_defaults_to_population_variance
    ]()
    suite.test[test_statistics__test_floatlike_variance_honors_ddof]()
    suite.test[test_statistics__test_floatlike_stddev_is_the_sqrt_of_variance]()
    suite.test[test_statistics__test_floatlike_cumsum_matches_the_running_sum]()
    suite.test[
        test_statistics__test_compensated_variance_beats_plain_on_a_long_summation
    ]()
    suite.test[
        test_statistics__test_tensor_variance_recovers_a_small_spread_under_a_large_mean
    ]()
    suite.test[test_statistics__test_tensor_variance_honors_ddof]()
    suite.test[
        test_statistics__test_variance_axis_agrees_with_the_separate_entry_points
    ]()
    suite.test[test_statistics__test_mean_reduces_the_first_axis]()
    # tests/stats/test_statistics_axis.mojo
    suite.test[test_statistics_axis__test_sum_axis_drops_the_axis_it_folded]()
    suite.test[test_statistics_axis__test_sum_axis_sums_the_right_elements]()
    suite.test[
        test_statistics_axis__test_folding_every_axis_matches_the_whole_tensor_sum
    ]()
    suite.test[test_statistics_axis__test_min_max_and_prod_along_an_axis]()
    suite.test[
        test_statistics_axis__test_mean_axis_is_the_sum_divided_by_the_axis_length
    ]()
    suite.test[
        test_statistics_axis__test_an_axis_reduction_accepts_a_run_time_shape
    ]()
    suite.test[
        test_statistics_axis__test_median_along_an_axis_matches_the_whole_tensor_one_per_slice
    ]()
    suite.test[
        test_statistics_axis__test_median_along_an_axis_agrees_with_median_of_one_slice
    ]()
    suite.test[
        test_statistics_axis__test_mode_along_an_axis_picks_the_smallest_among_ties
    ]()
    suite.test[
        test_statistics_axis__test_argmax_along_the_innermost_axis_is_the_position_in_the_slice
    ]()
    suite.test[
        test_statistics_axis__test_argmax_along_an_outer_axis_takes_the_walked_path
    ]()
    suite.test[test_statistics_axis__test_argmin_along_both_axes]()
    suite.test[
        test_statistics_axis__test_argmax_takes_the_first_of_a_tie_on_both_paths
    ]()
    suite.test[
        test_statistics_axis__test_axis_reductions_that_need_a_whole_slice_handle_rank_three
    ]()
    suite.test[
        test_statistics_axis__test_cumsum_along_an_axis_keeps_the_shape
    ]()
    suite.test[
        test_statistics_axis__test_cumprod_along_an_axis_keeps_the_shape
    ]()
    suite.test[
        test_statistics_axis__test_cumsum_with_no_axis_flattens_like_numpy
    ]()
    suite.test[
        test_statistics_axis__test_scanning_the_last_axis_of_a_rank_three_tensor
    ]()
    # tests/stats/test_tensor_distributions.mojo
    suite.test[
        test_tensor_distributions__test_norm_cdf_over_a_tensor_is_the_scalar_kernel_per_element
    ]()
    suite.test[
        test_tensor_distributions__test_norm_pdf_and_ppf_over_a_tensor_match_the_scalar_kernels
    ]()
    suite.test[
        test_tensor_distributions__test_every_one_parameter_family_matches_its_scalar_kernel
    ]()
    suite.test[
        test_tensor_distributions__test_every_two_parameter_family_matches_its_scalar_kernel
    ]()
    suite.test[
        test_tensor_distributions__test_quantiles_over_a_tensor_invert_cdfs_over_a_tensor
    ]()
    suite.test[
        test_tensor_distributions__test_a_run_time_shaped_tensor_goes_through_the_same_driver
    ]()
    suite.test[
        test_tensor_distributions__test_the_tensor_form_covers_a_length_that_does_not_divide_the_width
    ]()
    suite.test[
        test_tensor_distributions__test_every_family_agrees_between_static_and_run_time_shapes
    ]()
    suite^.run()
