"""GENERATED by tools/gen_test_aggregates.py -- do not edit.

Aggregates the 1 test files of `tests/cluster/` into one compiled
binary, so 1 compiler invocations become one. Run it with
`mojo -I . -I tests/cluster` (see tools/run_test_aggregates.sh).

Regenerate with `pixi run tests-gen`; CI fails if this file is out of date
with the tree.
"""

from std.testing import TestSuite
from test_cluster import (
    test_vq_and_whiten_match_scipy as test_cluster__test_vq_and_whiten_match_scipy,
)
from test_cluster import (
    test_kmeans_matches_scipy as test_cluster__test_kmeans_matches_scipy,
)
from test_cluster import (
    test_kmeans2_matches_scipy as test_cluster__test_kmeans2_matches_scipy,
)
from test_cluster import (
    test_linkage_matches_scipy as test_cluster__test_linkage_matches_scipy,
)
from test_cluster import (
    test_inconsistent_and_fcluster_match_scipy as test_cluster__test_inconsistent_and_fcluster_match_scipy,
)


def main() raises:
    var suite = TestSuite()
    # tests/cluster/test_cluster.mojo
    suite.test[test_cluster__test_vq_and_whiten_match_scipy]()
    suite.test[test_cluster__test_kmeans_matches_scipy]()
    suite.test[test_cluster__test_kmeans2_matches_scipy]()
    suite.test[test_cluster__test_linkage_matches_scipy]()
    suite.test[test_cluster__test_inconsistent_and_fcluster_match_scipy]()
    suite^.run()
