"""GENERATED by tools/gen_test_aggregates.py -- do not edit.

Aggregates the 5 test files of `tests/integrate/` into one compiled
binary, so 5 compiler invocations become one. Run it with
`mojo -I . -I tests/integrate` (see tools/run_test_aggregates.sh).

Regenerate with `pixi run tests-gen`; CI fails if this file is out of date
with the tree.
"""

from std.testing import TestSuite
from test_integrate import (
    test_quad_integrates_a_constant as test_integrate__test_quad_integrates_a_constant,
)
from test_integrate import (
    test_quad_integrates_a_linear_function as test_integrate__test_quad_integrates_a_linear_function,
)
from test_integrate import (
    test_quad_integrates_a_cubic_exactly_in_one_panel as test_integrate__test_quad_integrates_a_cubic_exactly_in_one_panel,
)
from test_integrate import (
    test_quad_integrates_the_gaussian_bell as test_integrate__test_quad_integrates_the_gaussian_bell,
)
from test_integrate import (
    test_quad_integrates_the_peak_to_its_closed_form as test_integrate__test_quad_integrates_the_peak_to_its_closed_form,
)
from test_integrate import (
    test_quad_integrates_the_kink_to_its_closed_form as test_integrate__test_quad_integrates_the_kink_to_its_closed_form,
)
from test_integrate import (
    test_quad_negates_for_reversed_limits as test_integrate__test_quad_negates_for_reversed_limits,
)
from test_integrate import (
    test_quad_on_an_empty_interval_is_exactly_zero as test_integrate__test_quad_on_an_empty_interval_is_exactly_zero,
)
from test_integrate import (
    test_quad_reports_the_error_it_estimated as test_integrate__test_quad_reports_the_error_it_estimated,
)
from test_integrate import (
    test_quad_reports_non_convergence_when_panels_run_out as test_integrate__test_quad_reports_non_convergence_when_panels_run_out,
)
from test_integrate import (
    test_tighter_tolerance_uses_more_panels as test_integrate__test_tighter_tolerance_uses_more_panels,
)
from test_integrate import (
    test_adaptive_beats_the_fixed_rule_on_a_peak as test_integrate__test_adaptive_beats_the_fixed_rule_on_a_peak,
)
from test_integrate import (
    test_fixed_rule_wins_on_a_smooth_integrand as test_integrate__test_fixed_rule_wins_on_a_smooth_integrand,
)
from test_integrate import (
    test_a_named_breakpoint_costs_far_fewer_panels as test_integrate__test_a_named_breakpoint_costs_far_fewer_panels,
)
from test_integrate import (
    test_quad_vec_ignores_breakpoints_outside_the_interval as test_integrate__test_quad_vec_ignores_breakpoints_outside_the_interval,
)
from test_integrate import (
    test_quad_vec_handles_unsorted_breakpoints as test_integrate__test_quad_vec_handles_unsorted_breakpoints,
)
from test_integrate import (
    test_quad_vec_with_no_breakpoints_matches_quad as test_integrate__test_quad_vec_with_no_breakpoints_matches_quad,
)
from test_integrate import (
    test_solve_ivp_matches_the_exponential_solution as test_integrate__test_solve_ivp_matches_the_exponential_solution,
)
from test_integrate import (
    test_solve_ivp_reaches_the_requested_endpoint as test_integrate__test_solve_ivp_reaches_the_requested_endpoint,
)
from test_integrate import (
    test_solve_ivp_integrates_growth as test_integrate__test_solve_ivp_integrates_growth,
)
from test_integrate import (
    test_solve_ivp_uses_the_time_argument as test_integrate__test_solve_ivp_uses_the_time_argument,
)
from test_integrate import (
    test_solve_ivp_integrates_backwards_in_time as test_integrate__test_solve_ivp_integrates_backwards_in_time,
)
from test_integrate import (
    test_solve_ivp_on_a_zero_length_interval_returns_the_initial_value as test_integrate__test_solve_ivp_on_a_zero_length_interval_returns_the_initial_value,
)
from test_integrate import (
    test_solve_ivp_accepts_most_of_its_steps_on_a_smooth_problem as test_integrate__test_solve_ivp_accepts_most_of_its_steps_on_a_smooth_problem,
)
from test_integrate import (
    test_tighter_tolerance_takes_more_steps as test_integrate__test_tighter_tolerance_takes_more_steps,
)
from test_integrate import (
    test_solve_ivp_reports_non_convergence_when_steps_run_out as test_integrate__test_solve_ivp_reports_non_convergence_when_steps_run_out,
)
from test_integrate import (
    test_solve_ivp_beats_fixed_steps_on_a_transient as test_integrate__test_solve_ivp_beats_fixed_steps_on_a_transient,
)
from test_integrate import (
    test_solve_ivp_agrees_with_a_well_resolved_fixed_step_run as test_integrate__test_solve_ivp_agrees_with_a_well_resolved_fixed_step_run,
)
from test_integrate import (
    test_the_stiff_solver_reaches_the_same_answer as test_integrate__test_the_stiff_solver_reaches_the_same_answer,
)
from test_integrate import (
    test_the_stiff_solver_integrates_a_time_dependent_equation as test_integrate__test_the_stiff_solver_integrates_a_time_dependent_equation,
)
from test_integrate import (
    test_the_stiff_solver_takes_far_fewer_steps_on_a_stiff_problem as test_integrate__test_the_stiff_solver_takes_far_fewer_steps_on_a_stiff_problem,
)
from test_ode import (
    test_rk4_matches_an_exponential as test_ode__test_rk4_matches_an_exponential,
)
from test_ode import (
    test_rk4_is_fourth_order as test_ode__test_rk4_is_fourth_order,
)
from test_ode import (
    test_dopri5_is_fifth_order as test_ode__test_dopri5_is_fifth_order,
)
from test_ode import (
    test_dopri5_beats_rk4_at_the_same_step_count as test_ode__test_dopri5_beats_rk4_at_the_same_step_count,
)
from test_ode import (
    test_both_integrators_are_exact_on_a_polynomial as test_ode__test_both_integrators_are_exact_on_a_polynomial,
)
from test_ode import (
    test_nonlinear_right_hand_side as test_ode__test_nonlinear_right_hand_side,
)
from test_ode import (
    test_backwards_integration_inverts_forwards as test_ode__test_backwards_integration_inverts_forwards,
)
from test_ode import (
    test_error_estimate_is_positive_and_shrinks_with_step_count as test_ode__test_error_estimate_is_positive_and_shrinks_with_step_count,
)
from test_ode import (
    test_error_estimate_tracks_the_true_error as test_ode__test_error_estimate_tracks_the_true_error,
)
from test_ode import (
    test_system_solves_the_harmonic_oscillator as test_ode__test_system_solves_the_harmonic_oscillator,
)
from test_ode import (
    test_system_nearly_conserves_energy as test_ode__test_system_nearly_conserves_energy,
)
from test_ode import (
    test_initial_condition_sensitivity_via_dual as test_ode__test_initial_condition_sensitivity_via_dual,
)
from test_ode import (
    test_parameter_sensitivity_via_augmented_state as test_ode__test_parameter_sensitivity_via_augmented_state,
)
from test_ode import (
    test_simd_lanes_integrate_independently as test_ode__test_simd_lanes_integrate_independently,
)
from test_quadrature import (
    test_gauss_legendre_is_exact_for_low_degree_polynomials as test_quadrature__test_gauss_legendre_is_exact_for_low_degree_polynomials,
)
from test_quadrature import (
    test_gauss_legendre_matches_a_known_transcendental_integral as test_quadrature__test_gauss_legendre_matches_a_known_transcendental_integral,
)
from test_quadrature import (
    test_gauss_legendre_on_a_gaussian as test_quadrature__test_gauss_legendre_on_a_gaussian,
)
from test_quadrature import (
    test_gauss_legendre_beats_a_much_finer_trapezoid_grid as test_quadrature__test_gauss_legendre_beats_a_much_finer_trapezoid_grid,
)
from test_quadrature import (
    test_gauss_legendre_handles_a_reversed_interval as test_quadrature__test_gauss_legendre_handles_a_reversed_interval,
)
from test_quadrature import (
    test_simpson_matches_a_polynomial_exactly as test_quadrature__test_simpson_matches_a_polynomial_exactly,
)
from test_quadrature import (
    test_simpson_beats_trapezoid_on_the_same_grid as test_quadrature__test_simpson_beats_trapezoid_on_the_same_grid,
)
from test_quadrature import (
    test_trapezoid_matches_a_logarithm as test_quadrature__test_trapezoid_matches_a_logarithm,
)
from test_quadrature import (
    test_integrating_at_dual_differentiates_the_upper_limit as test_quadrature__test_integrating_at_dual_differentiates_the_upper_limit,
)
from test_quadrature import (
    test_integrating_at_dual_differentiates_the_lower_limit as test_quadrature__test_integrating_at_dual_differentiates_the_lower_limit,
)
from test_quadrature import (
    test_gauss_legendre_nodes_are_symmetric_and_weights_sum_to_two as test_quadrature__test_gauss_legendre_nodes_are_symmetric_and_weights_sum_to_two,
)
from test_quadrature import (
    test_hermite_matches_closed_forms as test_quadrature__test_hermite_matches_closed_forms,
)
from test_quadrature import (
    test_laguerre_matches_closed_forms as test_quadrature__test_laguerre_matches_closed_forms,
)
from test_quadrature import (
    test_chebyshev_t_matches_the_trigonometric_form as test_quadrature__test_chebyshev_t_matches_the_trigonometric_form,
)
from test_quadrature import (
    test_chebyshev_u_matches_the_trigonometric_form as test_quadrature__test_chebyshev_u_matches_the_trigonometric_form,
)
from test_quadrature import (
    test_orthogonal_polynomial_derivatives_via_dual as test_quadrature__test_orthogonal_polynomial_derivatives_via_dual,
)
from test_quadrature import (
    test_hermite_derivative_identity as test_quadrature__test_hermite_derivative_identity,
)
from test_tensor_ode import (
    test_rk4_system_solves_the_harmonic_oscillator as test_tensor_ode__test_rk4_system_solves_the_harmonic_oscillator,
)
from test_tensor_ode import (
    test_rk4_system_agrees_with_the_array_tier_component_by_component as test_tensor_ode__test_rk4_system_agrees_with_the_array_tier_component_by_component,
)
from test_tensor_ode import (
    test_rk4_system_is_fourth_order as test_tensor_ode__test_rk4_system_is_fourth_order,
)
from test_tensor_ode import (
    test_dopri5_is_fifth_order_and_beats_rk4 as test_tensor_ode__test_dopri5_is_fifth_order_and_beats_rk4,
)
from test_tensor_ode import (
    test_both_integrators_are_exact_on_a_polynomial as test_tensor_ode__test_both_integrators_are_exact_on_a_polynomial,
)
from test_tensor_ode import (
    test_backwards_integration_inverts_forwards as test_tensor_ode__test_backwards_integration_inverts_forwards,
)
from test_tensor_ode import (
    test_solve_ivp_reaches_the_exponential_within_tolerance as test_tensor_ode__test_solve_ivp_reaches_the_exponential_within_tolerance,
)
from test_tensor_ode import (
    test_solve_ivp_takes_the_same_steps_as_the_scalar_controller as test_tensor_ode__test_solve_ivp_takes_the_same_steps_as_the_scalar_controller,
)
from test_tensor_ode import (
    test_solve_ivp_reports_non_convergence_when_steps_run_out as test_tensor_ode__test_solve_ivp_reports_non_convergence_when_steps_run_out,
)
from test_tensor_quadrature import (
    test_trapezoid_with_dx_matches_scipy as test_tensor_quadrature__test_trapezoid_with_dx_matches_scipy,
)
from test_tensor_quadrature import (
    test_trapezoid_at_non_uniform_points_matches_scipy as test_tensor_quadrature__test_trapezoid_at_non_uniform_points_matches_scipy,
)
from test_tensor_quadrature import (
    test_simpson_is_exact_for_a_quadratic_at_an_odd_count as test_tensor_quadrature__test_simpson_is_exact_for_a_quadratic_at_an_odd_count,
)
from test_tensor_quadrature import (
    test_simpson_at_an_even_count_uses_cartwrights_correction as test_tensor_quadrature__test_simpson_at_an_even_count_uses_cartwrights_correction,
)
from test_tensor_quadrature import (
    test_simpson_at_non_uniform_points_matches_scipy as test_tensor_quadrature__test_simpson_at_non_uniform_points_matches_scipy,
)
from test_tensor_quadrature import (
    test_cumulative_trapezoid_returns_one_value_per_interval as test_tensor_quadrature__test_cumulative_trapezoid_returns_one_value_per_interval,
)
from test_tensor_quadrature import (
    test_cumulative_trapezoid_with_initial_prepends_a_zero as test_tensor_quadrature__test_cumulative_trapezoid_with_initial_prepends_a_zero,
)
from test_tensor_quadrature import (
    test_cumulative_trapezoid_at_non_uniform_points_matches_scipy as test_tensor_quadrature__test_cumulative_trapezoid_at_non_uniform_points_matches_scipy,
)
from test_tensor_quadrature import (
    test_a_mismatched_x_raises as test_tensor_quadrature__test_a_mismatched_x_raises,
)


def main() raises:
    var suite = TestSuite()
    # tests/integrate/test_integrate.mojo
    suite.test[test_integrate__test_quad_integrates_a_constant]()
    suite.test[test_integrate__test_quad_integrates_a_linear_function]()
    suite.test[
        test_integrate__test_quad_integrates_a_cubic_exactly_in_one_panel
    ]()
    suite.test[test_integrate__test_quad_integrates_the_gaussian_bell]()
    suite.test[
        test_integrate__test_quad_integrates_the_peak_to_its_closed_form
    ]()
    suite.test[
        test_integrate__test_quad_integrates_the_kink_to_its_closed_form
    ]()
    suite.test[test_integrate__test_quad_negates_for_reversed_limits]()
    suite.test[test_integrate__test_quad_on_an_empty_interval_is_exactly_zero]()
    suite.test[test_integrate__test_quad_reports_the_error_it_estimated]()
    suite.test[
        test_integrate__test_quad_reports_non_convergence_when_panels_run_out
    ]()
    suite.test[test_integrate__test_tighter_tolerance_uses_more_panels]()
    suite.test[test_integrate__test_adaptive_beats_the_fixed_rule_on_a_peak]()
    suite.test[test_integrate__test_fixed_rule_wins_on_a_smooth_integrand]()
    suite.test[test_integrate__test_a_named_breakpoint_costs_far_fewer_panels]()
    suite.test[
        test_integrate__test_quad_vec_ignores_breakpoints_outside_the_interval
    ]()
    suite.test[test_integrate__test_quad_vec_handles_unsorted_breakpoints]()
    suite.test[test_integrate__test_quad_vec_with_no_breakpoints_matches_quad]()
    suite.test[
        test_integrate__test_solve_ivp_matches_the_exponential_solution
    ]()
    suite.test[test_integrate__test_solve_ivp_reaches_the_requested_endpoint]()
    suite.test[test_integrate__test_solve_ivp_integrates_growth]()
    suite.test[test_integrate__test_solve_ivp_uses_the_time_argument]()
    suite.test[test_integrate__test_solve_ivp_integrates_backwards_in_time]()
    suite.test[
        test_integrate__test_solve_ivp_on_a_zero_length_interval_returns_the_initial_value
    ]()
    suite.test[
        test_integrate__test_solve_ivp_accepts_most_of_its_steps_on_a_smooth_problem
    ]()
    suite.test[test_integrate__test_tighter_tolerance_takes_more_steps]()
    suite.test[
        test_integrate__test_solve_ivp_reports_non_convergence_when_steps_run_out
    ]()
    suite.test[
        test_integrate__test_solve_ivp_beats_fixed_steps_on_a_transient
    ]()
    suite.test[
        test_integrate__test_solve_ivp_agrees_with_a_well_resolved_fixed_step_run
    ]()
    suite.test[test_integrate__test_the_stiff_solver_reaches_the_same_answer]()
    suite.test[
        test_integrate__test_the_stiff_solver_integrates_a_time_dependent_equation
    ]()
    suite.test[
        test_integrate__test_the_stiff_solver_takes_far_fewer_steps_on_a_stiff_problem
    ]()
    # tests/integrate/test_ode.mojo
    suite.test[test_ode__test_rk4_matches_an_exponential]()
    suite.test[test_ode__test_rk4_is_fourth_order]()
    suite.test[test_ode__test_dopri5_is_fifth_order]()
    suite.test[test_ode__test_dopri5_beats_rk4_at_the_same_step_count]()
    suite.test[test_ode__test_both_integrators_are_exact_on_a_polynomial]()
    suite.test[test_ode__test_nonlinear_right_hand_side]()
    suite.test[test_ode__test_backwards_integration_inverts_forwards]()
    suite.test[
        test_ode__test_error_estimate_is_positive_and_shrinks_with_step_count
    ]()
    suite.test[test_ode__test_error_estimate_tracks_the_true_error]()
    suite.test[test_ode__test_system_solves_the_harmonic_oscillator]()
    suite.test[test_ode__test_system_nearly_conserves_energy]()
    suite.test[test_ode__test_initial_condition_sensitivity_via_dual]()
    suite.test[test_ode__test_parameter_sensitivity_via_augmented_state]()
    suite.test[test_ode__test_simd_lanes_integrate_independently]()
    # tests/integrate/test_quadrature.mojo
    suite.test[
        test_quadrature__test_gauss_legendre_is_exact_for_low_degree_polynomials
    ]()
    suite.test[
        test_quadrature__test_gauss_legendre_matches_a_known_transcendental_integral
    ]()
    suite.test[test_quadrature__test_gauss_legendre_on_a_gaussian]()
    suite.test[
        test_quadrature__test_gauss_legendre_beats_a_much_finer_trapezoid_grid
    ]()
    suite.test[
        test_quadrature__test_gauss_legendre_handles_a_reversed_interval
    ]()
    suite.test[test_quadrature__test_simpson_matches_a_polynomial_exactly]()
    suite.test[test_quadrature__test_simpson_beats_trapezoid_on_the_same_grid]()
    suite.test[test_quadrature__test_trapezoid_matches_a_logarithm]()
    suite.test[
        test_quadrature__test_integrating_at_dual_differentiates_the_upper_limit
    ]()
    suite.test[
        test_quadrature__test_integrating_at_dual_differentiates_the_lower_limit
    ]()
    suite.test[
        test_quadrature__test_gauss_legendre_nodes_are_symmetric_and_weights_sum_to_two
    ]()
    suite.test[test_quadrature__test_hermite_matches_closed_forms]()
    suite.test[test_quadrature__test_laguerre_matches_closed_forms]()
    suite.test[
        test_quadrature__test_chebyshev_t_matches_the_trigonometric_form
    ]()
    suite.test[
        test_quadrature__test_chebyshev_u_matches_the_trigonometric_form
    ]()
    suite.test[
        test_quadrature__test_orthogonal_polynomial_derivatives_via_dual
    ]()
    suite.test[test_quadrature__test_hermite_derivative_identity]()
    # tests/integrate/test_tensor_ode.mojo
    suite.test[
        test_tensor_ode__test_rk4_system_solves_the_harmonic_oscillator
    ]()
    suite.test[
        test_tensor_ode__test_rk4_system_agrees_with_the_array_tier_component_by_component
    ]()
    suite.test[test_tensor_ode__test_rk4_system_is_fourth_order]()
    suite.test[test_tensor_ode__test_dopri5_is_fifth_order_and_beats_rk4]()
    suite.test[
        test_tensor_ode__test_both_integrators_are_exact_on_a_polynomial
    ]()
    suite.test[test_tensor_ode__test_backwards_integration_inverts_forwards]()
    suite.test[
        test_tensor_ode__test_solve_ivp_reaches_the_exponential_within_tolerance
    ]()
    suite.test[
        test_tensor_ode__test_solve_ivp_takes_the_same_steps_as_the_scalar_controller
    ]()
    suite.test[
        test_tensor_ode__test_solve_ivp_reports_non_convergence_when_steps_run_out
    ]()
    # tests/integrate/test_tensor_quadrature.mojo
    suite.test[test_tensor_quadrature__test_trapezoid_with_dx_matches_scipy]()
    suite.test[
        test_tensor_quadrature__test_trapezoid_at_non_uniform_points_matches_scipy
    ]()
    suite.test[
        test_tensor_quadrature__test_simpson_is_exact_for_a_quadratic_at_an_odd_count
    ]()
    suite.test[
        test_tensor_quadrature__test_simpson_at_an_even_count_uses_cartwrights_correction
    ]()
    suite.test[
        test_tensor_quadrature__test_simpson_at_non_uniform_points_matches_scipy
    ]()
    suite.test[
        test_tensor_quadrature__test_cumulative_trapezoid_returns_one_value_per_interval
    ]()
    suite.test[
        test_tensor_quadrature__test_cumulative_trapezoid_with_initial_prepends_a_zero
    ]()
    suite.test[
        test_tensor_quadrature__test_cumulative_trapezoid_at_non_uniform_points_matches_scipy
    ]()
    suite.test[test_tensor_quadrature__test_a_mismatched_x_raises]()
    suite^.run()
