"""GENERATED by tools/gen_test_aggregates.py -- do not edit.

Aggregates the 4 test files of `tests/interpolate/` into one compiled
binary, so 4 compiler invocations become one. Run it with
`mojo -I . -I tests/interpolate` (see tools/run_test_aggregates.sh).

Regenerate with `pixi run tests-gen`; CI fails if this file is out of date
with the tree.
"""

from std.testing import TestSuite
from test_interp import (
    test_horner_matches_the_expanded_polynomial as test_interp__test_horner_matches_the_expanded_polynomial,
)
from test_interp import (
    test_horner_of_a_constant_is_constant as test_interp__test_horner_of_a_constant_is_constant,
)
from test_interp import (
    test_horner_is_differentiable as test_interp__test_horner_is_differentiable,
)
from test_interp import (
    test_spline_passes_through_every_knot as test_interp__test_spline_passes_through_every_knot,
)
from test_interp import (
    test_non_uniform_overloads_agree_with_the_uniform_ones_on_a_grid as test_interp__test_non_uniform_overloads_agree_with_the_uniform_ones_on_a_grid,
)
from test_interp import (
    test_non_uniform_spline_passes_through_its_knots as test_interp__test_non_uniform_spline_passes_through_its_knots,
)
from test_interp import (
    test_natural_spline_has_zero_end_moments as test_interp__test_natural_spline_has_zero_end_moments,
)
from test_interp import (
    test_spline_approximates_between_knots as test_interp__test_spline_approximates_between_knots,
)
from test_interp import (
    test_spline_error_falls_like_the_fourth_power_of_spacing as test_interp__test_spline_error_falls_like_the_fourth_power_of_spacing,
)
from test_interp import (
    test_spline_of_a_cubic_is_exact_in_the_interior as test_interp__test_spline_of_a_cubic_is_exact_in_the_interior,
)
from test_interp import (
    test_spline_clamps_outside_the_grid as test_interp__test_spline_clamps_outside_the_grid,
)
from test_interp import (
    test_spline_is_differentiable as test_interp__test_spline_is_differentiable,
)
from test_interp import (
    test_chebyshev_reproduces_a_smooth_function as test_interp__test_chebyshev_reproduces_a_smooth_function,
)
from test_interp import (
    test_chebyshev_reproduces_a_gaussian as test_interp__test_chebyshev_reproduces_a_gaussian,
)
from test_interp import (
    test_chebyshev_is_exact_at_its_own_nodes as test_interp__test_chebyshev_is_exact_at_its_own_nodes,
)
from test_interp import (
    test_chebyshev_converges_geometrically_on_the_runge_function as test_interp__test_chebyshev_converges_geometrically_on_the_runge_function,
)
from test_interp import (
    test_chebyshev_evaluation_is_differentiable as test_interp__test_chebyshev_evaluation_is_differentiable,
)
from test_interp import (
    test_simd_lanes_evaluate_independently as test_interp__test_simd_lanes_evaluate_independently,
)
from test_interp import (
    test_cubic_spline_object_matches_the_two_call_form as test_interp__test_cubic_spline_object_matches_the_two_call_form,
)
from test_interp import (
    test_chebyshev_object_matches_the_two_call_form as test_interp__test_chebyshev_object_matches_the_two_call_form,
)
from test_interp import (
    test_chebyshev_object_approximates_the_function_it_fit as test_interp__test_chebyshev_object_approximates_the_function_it_fit,
)
from test_tensor_fitting import (
    test_chebyshev_fit_matches_numpy as test_tensor_fitting__test_chebyshev_fit_matches_numpy,
)
from test_tensor_fitting import (
    test_chebyshev_fit_with_as_many_terms_as_points_interpolates as test_tensor_fitting__test_chebyshev_fit_with_as_many_terms_as_points_interpolates,
)
from test_tensor_fitting import (
    test_chebval_matches_numpy_on_the_natural_domain as test_tensor_fitting__test_chebval_matches_numpy_on_the_natural_domain,
)
from test_tensor_fitting import (
    test_chebval_agrees_with_the_series_on_the_natural_domain as test_tensor_fitting__test_chebval_agrees_with_the_series_on_the_natural_domain,
)
from test_tensor_fitting import (
    test_regular_grid_linear_matches_scipy as test_tensor_fitting__test_regular_grid_linear_matches_scipy,
)
from test_tensor_fitting import (
    test_regular_grid_nearest_matches_scipy as test_tensor_fitting__test_regular_grid_nearest_matches_scipy,
)
from test_tensor_fitting import (
    test_regular_grid_out_of_bounds_follows_scipy as test_tensor_fitting__test_regular_grid_out_of_bounds_follows_scipy,
)
from test_tensor_fitting import (
    test_regular_grid_unknown_method_raises as test_tensor_fitting__test_regular_grid_unknown_method_raises,
)
from test_tensor_interp import (
    test_interp_matches_numpy as test_tensor_interp__test_interp_matches_numpy,
)
from test_tensor_interp import (
    test_interp_takes_left_and_right as test_tensor_interp__test_interp_takes_left_and_right,
)
from test_tensor_interp import (
    test_interp_reuses_the_grid as test_tensor_interp__test_interp_reuses_the_grid,
)
from test_tensor_interp import (
    test_interp_on_a_single_knot_is_constant as test_tensor_interp__test_interp_on_a_single_knot_is_constant,
)
from test_tensor_interp import (
    test_horner_matches_polyval as test_tensor_interp__test_horner_matches_polyval,
)
from test_tensor_interp import (
    test_horner_with_one_coefficient_is_constant as test_tensor_interp__test_horner_with_one_coefficient_is_constant,
)
from test_tensor_interp import (
    test_polyval_is_horner_with_the_order_reversed as test_tensor_interp__test_polyval_is_horner_with_the_order_reversed,
)
from test_tensor_interp import (
    test_polyder_and_polyint_are_inverse_up_to_the_constant as test_tensor_interp__test_polyder_and_polyint_are_inverse_up_to_the_constant,
)
from test_tensor_interp import (
    test_polyint_places_the_constant_in_the_last_slot as test_tensor_interp__test_polyint_places_the_constant_in_the_last_slot,
)
from test_tensor_interp import (
    test_roots_finds_a_real_pair as test_tensor_interp__test_roots_finds_a_real_pair,
)
from test_tensor_interp import (
    test_roots_finds_a_complex_pair as test_tensor_interp__test_roots_finds_a_complex_pair,
)
from test_tensor_interp import (
    test_roots_agrees_with_polyval_at_the_roots_it_finds as test_tensor_interp__test_roots_agrees_with_polyval_at_the_roots_it_finds,
)
from test_tensor_interp import (
    test_polyfit_recovers_a_polynomial_it_was_sampled_from as test_tensor_interp__test_polyfit_recovers_a_polynomial_it_was_sampled_from,
)
from test_tensor_interp import (
    test_polyfit_at_degree_one_is_a_straight_line as test_tensor_interp__test_polyfit_at_degree_one_is_a_straight_line,
)
from test_tensor_spline import (
    test_not_a_knot_spline_matches_scipy as test_tensor_spline__test_not_a_knot_spline_matches_scipy,
)
from test_tensor_spline import (
    test_natural_spline_matches_scipy as test_tensor_spline__test_natural_spline_matches_scipy,
)
from test_tensor_spline import (
    test_clamped_spline_matches_scipy as test_tensor_spline__test_clamped_spline_matches_scipy,
)
from test_tensor_spline import (
    test_spline_integrates_exactly as test_tensor_spline__test_spline_integrates_exactly,
)
from test_tensor_spline import (
    test_two_and_three_knots_take_scipys_special_cases as test_tensor_spline__test_two_and_three_knots_take_scipys_special_cases,
)
from test_tensor_spline import (
    test_unknown_boundary_condition_raises as test_tensor_spline__test_unknown_boundary_condition_raises,
)
from test_tensor_spline import (
    test_extrapolate_false_gives_nan_outside_the_knots as test_tensor_spline__test_extrapolate_false_gives_nan_outside_the_knots,
)
from test_tensor_spline import (
    test_hermite_spline_takes_prescribed_slopes as test_tensor_spline__test_hermite_spline_takes_prescribed_slopes,
)
from test_tensor_spline import (
    test_pchip_matches_scipy as test_tensor_spline__test_pchip_matches_scipy,
)
from test_tensor_spline import (
    test_akima_matches_scipy_and_is_nan_outside as test_tensor_spline__test_akima_matches_scipy_and_is_nan_outside,
)
from test_tensor_spline import (
    test_array_tier_non_uniform_moments_agree_with_the_tensor_natural_spline as test_tensor_spline__test_array_tier_non_uniform_moments_agree_with_the_tensor_natural_spline,
)


def main() raises:
    var suite = TestSuite()
    # tests/interpolate/test_interp.mojo
    suite.test[test_interp__test_horner_matches_the_expanded_polynomial]()
    suite.test[test_interp__test_horner_of_a_constant_is_constant]()
    suite.test[test_interp__test_horner_is_differentiable]()
    suite.test[test_interp__test_spline_passes_through_every_knot]()
    suite.test[
        test_interp__test_non_uniform_overloads_agree_with_the_uniform_ones_on_a_grid
    ]()
    suite.test[test_interp__test_non_uniform_spline_passes_through_its_knots]()
    suite.test[test_interp__test_natural_spline_has_zero_end_moments]()
    suite.test[test_interp__test_spline_approximates_between_knots]()
    suite.test[
        test_interp__test_spline_error_falls_like_the_fourth_power_of_spacing
    ]()
    suite.test[test_interp__test_spline_of_a_cubic_is_exact_in_the_interior]()
    suite.test[test_interp__test_spline_clamps_outside_the_grid]()
    suite.test[test_interp__test_spline_is_differentiable]()
    suite.test[test_interp__test_chebyshev_reproduces_a_smooth_function]()
    suite.test[test_interp__test_chebyshev_reproduces_a_gaussian]()
    suite.test[test_interp__test_chebyshev_is_exact_at_its_own_nodes]()
    suite.test[
        test_interp__test_chebyshev_converges_geometrically_on_the_runge_function
    ]()
    suite.test[test_interp__test_chebyshev_evaluation_is_differentiable]()
    suite.test[test_interp__test_simd_lanes_evaluate_independently]()
    suite.test[
        test_interp__test_cubic_spline_object_matches_the_two_call_form
    ]()
    suite.test[test_interp__test_chebyshev_object_matches_the_two_call_form]()
    suite.test[
        test_interp__test_chebyshev_object_approximates_the_function_it_fit
    ]()
    # tests/interpolate/test_tensor_fitting.mojo
    suite.test[test_tensor_fitting__test_chebyshev_fit_matches_numpy]()
    suite.test[
        test_tensor_fitting__test_chebyshev_fit_with_as_many_terms_as_points_interpolates
    ]()
    suite.test[
        test_tensor_fitting__test_chebval_matches_numpy_on_the_natural_domain
    ]()
    suite.test[
        test_tensor_fitting__test_chebval_agrees_with_the_series_on_the_natural_domain
    ]()
    suite.test[test_tensor_fitting__test_regular_grid_linear_matches_scipy]()
    suite.test[test_tensor_fitting__test_regular_grid_nearest_matches_scipy]()
    suite.test[
        test_tensor_fitting__test_regular_grid_out_of_bounds_follows_scipy
    ]()
    suite.test[test_tensor_fitting__test_regular_grid_unknown_method_raises]()
    # tests/interpolate/test_tensor_interp.mojo
    suite.test[test_tensor_interp__test_interp_matches_numpy]()
    suite.test[test_tensor_interp__test_interp_takes_left_and_right]()
    suite.test[test_tensor_interp__test_interp_reuses_the_grid]()
    suite.test[test_tensor_interp__test_interp_on_a_single_knot_is_constant]()
    suite.test[test_tensor_interp__test_horner_matches_polyval]()
    suite.test[
        test_tensor_interp__test_horner_with_one_coefficient_is_constant
    ]()
    suite.test[
        test_tensor_interp__test_polyval_is_horner_with_the_order_reversed
    ]()
    suite.test[
        test_tensor_interp__test_polyder_and_polyint_are_inverse_up_to_the_constant
    ]()
    suite.test[
        test_tensor_interp__test_polyint_places_the_constant_in_the_last_slot
    ]()
    suite.test[test_tensor_interp__test_roots_finds_a_real_pair]()
    suite.test[test_tensor_interp__test_roots_finds_a_complex_pair]()
    suite.test[
        test_tensor_interp__test_roots_agrees_with_polyval_at_the_roots_it_finds
    ]()
    suite.test[
        test_tensor_interp__test_polyfit_recovers_a_polynomial_it_was_sampled_from
    ]()
    suite.test[
        test_tensor_interp__test_polyfit_at_degree_one_is_a_straight_line
    ]()
    # tests/interpolate/test_tensor_spline.mojo
    suite.test[test_tensor_spline__test_not_a_knot_spline_matches_scipy]()
    suite.test[test_tensor_spline__test_natural_spline_matches_scipy]()
    suite.test[test_tensor_spline__test_clamped_spline_matches_scipy]()
    suite.test[test_tensor_spline__test_spline_integrates_exactly]()
    suite.test[
        test_tensor_spline__test_two_and_three_knots_take_scipys_special_cases
    ]()
    suite.test[test_tensor_spline__test_unknown_boundary_condition_raises]()
    suite.test[
        test_tensor_spline__test_extrapolate_false_gives_nan_outside_the_knots
    ]()
    suite.test[
        test_tensor_spline__test_hermite_spline_takes_prescribed_slopes
    ]()
    suite.test[test_tensor_spline__test_pchip_matches_scipy]()
    suite.test[
        test_tensor_spline__test_akima_matches_scipy_and_is_nan_outside
    ]()
    suite.test[
        test_tensor_spline__test_array_tier_non_uniform_moments_agree_with_the_tensor_natural_spline
    ]()
    suite^.run()
