"""GENERATED by tools/gen_test_aggregates.py -- do not edit.

Aggregates the 6 test files of `tests/optimize/` into one compiled
binary, so 6 compiler invocations become one. Run it with
`mojo -I . -I tests/optimize` (see tools/run_test_aggregates.sh).

Regenerate with `pixi run tests-gen`; CI fails if this file is out of date
with the tree.
"""

from std.testing import TestSuite
from test_minimize import (
    test_minimize_bfgs_is_exactly_bfgs as test_minimize__test_minimize_bfgs_is_exactly_bfgs,
)
from test_minimize import (
    test_minimize_defaults_to_bfgs as test_minimize__test_minimize_defaults_to_bfgs,
)
from test_minimize import (
    test_minimize_cg_is_exactly_cg as test_minimize__test_minimize_cg_is_exactly_cg,
)
from test_minimize import (
    test_minimize_nelder_mead_is_exactly_nelder_mead as test_minimize__test_minimize_nelder_mead_is_exactly_nelder_mead,
)
from test_minimize import (
    test_omitted_tol_reproduces_each_methods_own_default as test_minimize__test_omitted_tol_reproduces_each_methods_own_default,
)
from test_minimize import (
    test_a_tighter_tol_is_honoured_through_the_dispatch as test_minimize__test_a_tighter_tol_is_honoured_through_the_dispatch,
)
from test_minimize import (
    test_max_iter_is_honoured_through_the_dispatch as test_minimize__test_max_iter_is_honoured_through_the_dispatch,
)
from test_minimize import (
    test_an_unknown_method_raises_and_names_itself as test_minimize__test_an_unknown_method_raises_and_names_itself,
)
from test_minimize import (
    test_cg_minimizes_rosenbrock_from_the_standard_start as test_minimize__test_cg_minimizes_rosenbrock_from_the_standard_start,
)
from test_minimize import (
    test_cg_minimizes_a_quadratic_bowl as test_minimize__test_cg_minimizes_a_quadratic_bowl,
)
from test_minimize import (
    test_cg_starting_at_the_minimum_converges_immediately as test_minimize__test_cg_starting_at_the_minimum_converges_immediately,
)
from test_minimize import (
    test_cg_and_bfgs_land_on_the_same_minimum as test_minimize__test_cg_and_bfgs_land_on_the_same_minimum,
)
from test_minimize import (
    test_cg_reports_the_gradient_norm_it_converged_on as test_minimize__test_cg_reports_the_gradient_norm_it_converged_on,
)
from test_minimize import (
    test_brent_finds_a_minimum_far_outside_the_starting_pair as test_minimize__test_brent_finds_a_minimum_far_outside_the_starting_pair,
)
from test_minimize import (
    test_golden_agrees_with_brent as test_minimize__test_golden_agrees_with_brent,
)
from test_minimize import (
    test_brent_beats_golden_on_evaluation_count as test_minimize__test_brent_beats_golden_on_evaluation_count,
)
from test_minimize import (
    test_an_unbounded_descent_is_reported_not_run_away_from as test_minimize__test_an_unbounded_descent_is_reported_not_run_away_from,
)
from test_minimize import (
    test_fminbound_keeps_the_answer_inside_the_bounds as test_minimize__test_fminbound_keeps_the_answer_inside_the_bounds,
)
from test_minimize import (
    test_fminbound_finds_an_interior_minimum as test_minimize__test_fminbound_finds_an_interior_minimum,
)
from test_minimize import (
    test_minimize_scalar_brent_is_exactly_brent as test_minimize__test_minimize_scalar_brent_is_exactly_brent,
)
from test_minimize import (
    test_minimize_scalar_defaults_to_brent_with_the_default_bracket as test_minimize__test_minimize_scalar_defaults_to_brent_with_the_default_bracket,
)
from test_minimize import (
    test_minimize_scalar_golden_is_exactly_golden as test_minimize__test_minimize_scalar_golden_is_exactly_golden,
)
from test_minimize import (
    test_minimize_scalar_bounded_is_exactly_fminbound as test_minimize__test_minimize_scalar_bounded_is_exactly_fminbound,
)
from test_minimize import (
    test_bounded_without_bounds_raises as test_minimize__test_bounded_without_bounds_raises,
)
from test_minimize import (
    test_a_bracket_is_not_silently_accepted_as_bounds as test_minimize__test_a_bracket_is_not_silently_accepted_as_bounds,
)
from test_minimize import (
    test_reversed_bounds_raise as test_minimize__test_reversed_bounds_raise,
)
from test_minimize import (
    test_minimize_scalar_rejects_an_unknown_method as test_minimize__test_minimize_scalar_rejects_an_unknown_method,
)
from test_minimize import (
    test_scalar_tol_defaults_per_method as test_minimize__test_scalar_tol_defaults_per_method,
)
from test_minimize import (
    test_halley_tol_converges_faster_than_newton_tol as test_minimize__test_halley_tol_converges_faster_than_newton_tol,
)
from test_minimize import (
    test_secant_finds_the_root_without_a_derivative as test_minimize__test_secant_finds_the_root_without_a_derivative,
)
from test_minimize import (
    test_secant_accepts_an_explicit_second_point as test_minimize__test_secant_accepts_an_explicit_second_point,
)
from test_minimize import (
    test_bisect_tol_halves_to_the_root as test_minimize__test_bisect_tol_halves_to_the_root,
)
from test_minimize import (
    test_bisect_tol_reports_a_bracket_without_a_sign_change as test_minimize__test_bisect_tol_reports_a_bracket_without_a_sign_change,
)
from test_minimize import (
    test_brentq_beats_bisect_tol_on_the_same_bracket as test_minimize__test_brentq_beats_bisect_tol_on_the_same_bracket,
)
from test_minimize import (
    test_all_five_methods_find_the_same_root as test_minimize__test_all_five_methods_find_the_same_root,
)
from test_minimize import (
    test_root_scalar_dispatches_to_exactly_the_named_function as test_minimize__test_root_scalar_dispatches_to_exactly_the_named_function,
)
from test_minimize import (
    test_a_bracketing_method_without_a_bracket_raises as test_minimize__test_a_bracketing_method_without_a_bracket_raises,
)
from test_minimize import (
    test_a_guess_method_without_x0_raises as test_minimize__test_a_guess_method_without_x0_raises,
)
from test_minimize import (
    test_a_guess_method_given_a_bracket_raises as test_minimize__test_a_guess_method_given_a_bracket_raises,
)
from test_minimize import (
    test_root_scalar_rejects_an_unknown_method as test_minimize__test_root_scalar_rejects_an_unknown_method,
)
from test_minimize import (
    test_root_solves_a_square_system as test_minimize__test_root_solves_a_square_system,
)
from test_minimize import (
    test_root_is_exactly_least_squares_on_the_same_system as test_minimize__test_root_is_exactly_least_squares_on_the_same_system,
)
from test_minimize import (
    test_a_system_with_no_root_is_told_apart_by_the_cost as test_minimize__test_a_system_with_no_root_is_told_apart_by_the_cost,
)
from test_minimize import (
    test_root_rejects_an_unknown_method as test_minimize__test_root_rejects_an_unknown_method,
)
from test_optimize import (
    test_newton_tol_finds_the_dottie_number as test_optimize__test_newton_tol_finds_the_dottie_number,
)
from test_optimize import (
    test_newton_tol_converges_quadratically as test_optimize__test_newton_tol_converges_quadratically,
)
from test_optimize import (
    test_newton_tol_solves_wallis_cubic as test_optimize__test_newton_tol_solves_wallis_cubic,
)
from test_optimize import (
    test_newton_tol_reports_failure_on_a_zero_derivative as test_optimize__test_newton_tol_reports_failure_on_a_zero_derivative,
)
from test_optimize import (
    test_newton_tol_agrees_with_the_tier_one_sibling as test_optimize__test_newton_tol_agrees_with_the_tier_one_sibling,
)
from test_optimize import (
    test_brentq_finds_the_dottie_number as test_optimize__test_brentq_finds_the_dottie_number,
)
from test_optimize import (
    test_brentq_beats_pure_bisection_in_iteration_count as test_optimize__test_brentq_beats_pure_bisection_in_iteration_count,
)
from test_optimize import (
    test_brentq_finds_pi as test_optimize__test_brentq_finds_pi,
)
from test_optimize import (
    test_brentq_returns_an_exact_endpoint_root_immediately as test_optimize__test_brentq_returns_an_exact_endpoint_root_immediately,
)
from test_optimize import (
    test_brentq_reports_failure_on_a_bracket_without_a_sign_change as test_optimize__test_brentq_reports_failure_on_a_bracket_without_a_sign_change,
)
from test_optimize import (
    test_brentq_and_newton_tol_agree as test_optimize__test_brentq_and_newton_tol_agree,
)
from test_optimize import (
    test_bfgs_minimizes_a_quadratic_bowl as test_optimize__test_bfgs_minimizes_a_quadratic_bowl,
)
from test_optimize import (
    test_bfgs_minimizes_rosenbrock_from_the_standard_start as test_optimize__test_bfgs_minimizes_rosenbrock_from_the_standard_start,
)
from test_optimize import (
    test_bfgs_drives_the_objective_essentially_to_zero as test_optimize__test_bfgs_drives_the_objective_essentially_to_zero,
)
from test_optimize import (
    test_bfgs_reports_the_gradient_norm_it_converged_on as test_optimize__test_bfgs_reports_the_gradient_norm_it_converged_on,
)
from test_optimize import (
    test_bfgs_starting_at_the_minimum_converges_immediately as test_optimize__test_bfgs_starting_at_the_minimum_converges_immediately,
)
from test_optimize import (
    test_bfgs_minimizes_a_one_variable_objective as test_optimize__test_bfgs_minimizes_a_one_variable_objective,
)
from test_optimize import (
    test_ad_gradient_beats_a_central_difference as test_optimize__test_ad_gradient_beats_a_central_difference,
)
from test_optimize import (
    test_bfgs_objective_is_the_same_function_evaluated_three_ways as test_optimize__test_bfgs_objective_is_the_same_function_evaluated_three_ways,
)
from test_optimize import (
    test_least_squares_finds_the_rosenbrock_minimum as test_optimize__test_least_squares_finds_the_rosenbrock_minimum,
)
from test_optimize import (
    test_least_squares_recovers_an_exactly_fitting_line as test_optimize__test_least_squares_recovers_an_exactly_fitting_line,
)
from test_optimize import (
    test_curve_fit_recovers_the_parameters_of_exact_data as test_optimize__test_curve_fit_recovers_the_parameters_of_exact_data,
)
from test_optimize import (
    test_curve_fit_averages_the_noise_it_cannot_fit as test_optimize__test_curve_fit_averages_the_noise_it_cannot_fit,
)
from test_optimize import (
    test_curve_fit_and_least_squares_agree_on_the_same_problem as test_optimize__test_curve_fit_and_least_squares_agree_on_the_same_problem,
)
from test_optimize import (
    test_the_fitted_jacobian_is_exact_where_a_difference_is_not as test_optimize__test_the_fitted_jacobian_is_exact_where_a_difference_is_not,
)
from test_optimize import (
    test_nelder_mead_minimizes_rosenbrock as test_optimize__test_nelder_mead_minimizes_rosenbrock,
)
from test_optimize import (
    test_nelder_mead_minimizes_a_quadratic_bowl as test_optimize__test_nelder_mead_minimizes_a_quadratic_bowl,
)
from test_optimize import (
    test_nelder_mead_handles_the_kinks_that_defeat_a_gradient as test_optimize__test_nelder_mead_handles_the_kinks_that_defeat_a_gradient,
)
from test_optimize import (
    test_nelder_mead_reports_the_gradient_it_did_not_use as test_optimize__test_nelder_mead_reports_the_gradient_it_did_not_use,
)
from test_optimize import (
    test_nelder_mead_and_bfgs_land_on_the_same_minimum as test_optimize__test_nelder_mead_and_bfgs_land_on_the_same_minimum,
)
from test_solve import (
    test_newton_finds_the_cube_root_of_two as test_solve__test_newton_finds_the_cube_root_of_two,
)
from test_solve import (
    test_newton_finds_the_dottie_number as test_solve__test_newton_finds_the_dottie_number,
)
from test_solve import (
    test_newton_finds_a_logarithm as test_solve__test_newton_finds_a_logarithm,
)
from test_solve import (
    test_newton_converges_from_a_poor_guess as test_solve__test_newton_converges_from_a_poor_guess,
)
from test_solve import (
    test_newton_solves_each_simd_lane_independently as test_solve__test_newton_solves_each_simd_lane_independently,
)
from test_solve import (
    test_newton_at_a_critical_point_stays_finite as test_solve__test_newton_at_a_critical_point_stays_finite,
)
from test_solve import (
    test_halley_matches_newton as test_solve__test_halley_matches_newton,
)
from test_solve import (
    test_halley_converges_faster_than_newton as test_solve__test_halley_converges_faster_than_newton,
)
from test_solve import (
    test_halley_on_a_transcendental as test_solve__test_halley_on_a_transcendental,
)
from test_solve import (
    test_bisection_finds_the_cube_root_of_two as test_solve__test_bisection_finds_the_cube_root_of_two,
)
from test_solve import (
    test_bisection_works_with_the_bracket_either_way_around as test_solve__test_bisection_works_with_the_bracket_either_way_around,
)
from test_solve import (
    test_bisection_needs_no_derivative_and_cannot_diverge as test_solve__test_bisection_needs_no_derivative_and_cannot_diverge,
)
from test_solve import (
    test_bisection_bisects_lanes_independently as test_solve__test_bisection_bisects_lanes_independently,
)
from test_solve import (
    test_solving_at_dual_differentiates_the_root as test_solve__test_solving_at_dual_differentiates_the_root,
)
from test_tensor_least_squares import (
    test_least_squares_recovers_an_exact_exponential_fit as test_tensor_least_squares__test_least_squares_recovers_an_exact_exponential_fit,
)
from test_tensor_least_squares import (
    test_least_squares_solves_a_linear_fit as test_tensor_least_squares__test_least_squares_solves_a_linear_fit,
)
from test_tensor_least_squares import (
    test_least_squares_starting_at_the_solution_converges_immediately as test_tensor_least_squares__test_least_squares_starting_at_the_solution_converges_immediately,
)
from test_tensor_least_squares import (
    test_least_squares_reports_failure_rather_than_raising as test_tensor_least_squares__test_least_squares_reports_failure_rather_than_raising,
)
from test_tensor_least_squares import (
    test_curve_fit_matches_least_squares_on_the_same_problem as test_tensor_least_squares__test_curve_fit_matches_least_squares_on_the_same_problem,
)
from test_tensor_least_squares import (
    test_the_two_tiers_agree as test_tensor_least_squares__test_the_two_tiers_agree,
)
from test_tensor_minimize import (
    test_bfgs_minimizes_rosenbrock as test_tensor_minimize__test_bfgs_minimizes_rosenbrock,
)
from test_tensor_minimize import (
    test_cg_minimizes_rosenbrock as test_tensor_minimize__test_cg_minimizes_rosenbrock,
)
from test_tensor_minimize import (
    test_bfgs_minimizes_a_quadratic_bowl as test_tensor_minimize__test_bfgs_minimizes_a_quadratic_bowl,
)
from test_tensor_minimize import (
    test_cg_minimizes_a_quadratic_bowl as test_tensor_minimize__test_cg_minimizes_a_quadratic_bowl,
)
from test_tensor_minimize import (
    test_starting_at_the_minimum_converges_immediately as test_tensor_minimize__test_starting_at_the_minimum_converges_immediately,
)
from test_tensor_minimize import (
    test_the_two_tiers_agree as test_tensor_minimize__test_the_two_tiers_agree,
)
from test_tensor_minimize import (
    test_the_context_survives_a_whole_run as test_tensor_minimize__test_the_context_survives_a_whole_run,
)
from test_tensor_minimize import (
    test_grad_norm_is_the_quantity_that_converged as test_tensor_minimize__test_grad_norm_is_the_quantity_that_converged,
)
from test_tensor_minimize import (
    test_a_tight_iteration_cap_reports_failure as test_tensor_minimize__test_a_tight_iteration_cap_reports_failure,
)
from test_tensor_minimize import (
    test_an_unknown_method_raises as test_tensor_minimize__test_an_unknown_method_raises,
)
from test_tensor_optimize import (
    test_lbfgs_reaches_the_rosenbrock_minimum as test_tensor_optimize__test_lbfgs_reaches_the_rosenbrock_minimum,
)
from test_tensor_optimize import (
    test_lbfgs_agrees_with_bfgs_on_a_quadratic as test_tensor_optimize__test_lbfgs_agrees_with_bfgs_on_a_quadratic,
)
from test_tensor_optimize import (
    test_bounded_minimize_stops_on_the_active_bound as test_tensor_optimize__test_bounded_minimize_stops_on_the_active_bound,
)
from test_tensor_optimize import (
    test_powell_needs_no_gradient_and_finds_the_minimum as test_tensor_optimize__test_powell_needs_no_gradient_and_finds_the_minimum,
)
from test_tensor_optimize import (
    test_a_gradient_method_without_jac_raises as test_tensor_optimize__test_a_gradient_method_without_jac_raises,
)
from test_tensor_optimize import (
    test_root_by_newton_and_lm_both_find_scipys_root as test_tensor_optimize__test_root_by_newton_and_lm_both_find_scipys_root,
)
from test_tensor_optimize import (
    test_nnls_matches_scipy as test_tensor_optimize__test_nnls_matches_scipy,
)
from test_tensor_optimize import (
    test_lsq_linear_matches_scipy_with_and_without_active_bounds as test_tensor_optimize__test_lsq_linear_matches_scipy_with_and_without_active_bounds,
)


def main() raises:
    var suite = TestSuite()
    # tests/optimize/test_minimize.mojo
    suite.test[test_minimize__test_minimize_bfgs_is_exactly_bfgs]()
    suite.test[test_minimize__test_minimize_defaults_to_bfgs]()
    suite.test[test_minimize__test_minimize_cg_is_exactly_cg]()
    suite.test[
        test_minimize__test_minimize_nelder_mead_is_exactly_nelder_mead
    ]()
    suite.test[
        test_minimize__test_omitted_tol_reproduces_each_methods_own_default
    ]()
    suite.test[
        test_minimize__test_a_tighter_tol_is_honoured_through_the_dispatch
    ]()
    suite.test[test_minimize__test_max_iter_is_honoured_through_the_dispatch]()
    suite.test[test_minimize__test_an_unknown_method_raises_and_names_itself]()
    suite.test[
        test_minimize__test_cg_minimizes_rosenbrock_from_the_standard_start
    ]()
    suite.test[test_minimize__test_cg_minimizes_a_quadratic_bowl]()
    suite.test[
        test_minimize__test_cg_starting_at_the_minimum_converges_immediately
    ]()
    suite.test[test_minimize__test_cg_and_bfgs_land_on_the_same_minimum]()
    suite.test[
        test_minimize__test_cg_reports_the_gradient_norm_it_converged_on
    ]()
    suite.test[
        test_minimize__test_brent_finds_a_minimum_far_outside_the_starting_pair
    ]()
    suite.test[test_minimize__test_golden_agrees_with_brent]()
    suite.test[test_minimize__test_brent_beats_golden_on_evaluation_count]()
    suite.test[
        test_minimize__test_an_unbounded_descent_is_reported_not_run_away_from
    ]()
    suite.test[
        test_minimize__test_fminbound_keeps_the_answer_inside_the_bounds
    ]()
    suite.test[test_minimize__test_fminbound_finds_an_interior_minimum]()
    suite.test[test_minimize__test_minimize_scalar_brent_is_exactly_brent]()
    suite.test[
        test_minimize__test_minimize_scalar_defaults_to_brent_with_the_default_bracket
    ]()
    suite.test[test_minimize__test_minimize_scalar_golden_is_exactly_golden]()
    suite.test[
        test_minimize__test_minimize_scalar_bounded_is_exactly_fminbound
    ]()
    suite.test[test_minimize__test_bounded_without_bounds_raises]()
    suite.test[
        test_minimize__test_a_bracket_is_not_silently_accepted_as_bounds
    ]()
    suite.test[test_minimize__test_reversed_bounds_raise]()
    suite.test[test_minimize__test_minimize_scalar_rejects_an_unknown_method]()
    suite.test[test_minimize__test_scalar_tol_defaults_per_method]()
    suite.test[
        test_minimize__test_halley_tol_converges_faster_than_newton_tol
    ]()
    suite.test[test_minimize__test_secant_finds_the_root_without_a_derivative]()
    suite.test[test_minimize__test_secant_accepts_an_explicit_second_point]()
    suite.test[test_minimize__test_bisect_tol_halves_to_the_root]()
    suite.test[
        test_minimize__test_bisect_tol_reports_a_bracket_without_a_sign_change
    ]()
    suite.test[
        test_minimize__test_brentq_beats_bisect_tol_on_the_same_bracket
    ]()
    suite.test[test_minimize__test_all_five_methods_find_the_same_root]()
    suite.test[
        test_minimize__test_root_scalar_dispatches_to_exactly_the_named_function
    ]()
    suite.test[
        test_minimize__test_a_bracketing_method_without_a_bracket_raises
    ]()
    suite.test[test_minimize__test_a_guess_method_without_x0_raises]()
    suite.test[test_minimize__test_a_guess_method_given_a_bracket_raises]()
    suite.test[test_minimize__test_root_scalar_rejects_an_unknown_method]()
    suite.test[test_minimize__test_root_solves_a_square_system]()
    suite.test[
        test_minimize__test_root_is_exactly_least_squares_on_the_same_system
    ]()
    suite.test[
        test_minimize__test_a_system_with_no_root_is_told_apart_by_the_cost
    ]()
    suite.test[test_minimize__test_root_rejects_an_unknown_method]()
    # tests/optimize/test_optimize.mojo
    suite.test[test_optimize__test_newton_tol_finds_the_dottie_number]()
    suite.test[test_optimize__test_newton_tol_converges_quadratically]()
    suite.test[test_optimize__test_newton_tol_solves_wallis_cubic]()
    suite.test[
        test_optimize__test_newton_tol_reports_failure_on_a_zero_derivative
    ]()
    suite.test[
        test_optimize__test_newton_tol_agrees_with_the_tier_one_sibling
    ]()
    suite.test[test_optimize__test_brentq_finds_the_dottie_number]()
    suite.test[
        test_optimize__test_brentq_beats_pure_bisection_in_iteration_count
    ]()
    suite.test[test_optimize__test_brentq_finds_pi]()
    suite.test[
        test_optimize__test_brentq_returns_an_exact_endpoint_root_immediately
    ]()
    suite.test[
        test_optimize__test_brentq_reports_failure_on_a_bracket_without_a_sign_change
    ]()
    suite.test[test_optimize__test_brentq_and_newton_tol_agree]()
    suite.test[test_optimize__test_bfgs_minimizes_a_quadratic_bowl]()
    suite.test[
        test_optimize__test_bfgs_minimizes_rosenbrock_from_the_standard_start
    ]()
    suite.test[
        test_optimize__test_bfgs_drives_the_objective_essentially_to_zero
    ]()
    suite.test[
        test_optimize__test_bfgs_reports_the_gradient_norm_it_converged_on
    ]()
    suite.test[
        test_optimize__test_bfgs_starting_at_the_minimum_converges_immediately
    ]()
    suite.test[test_optimize__test_bfgs_minimizes_a_one_variable_objective]()
    suite.test[test_optimize__test_ad_gradient_beats_a_central_difference]()
    suite.test[
        test_optimize__test_bfgs_objective_is_the_same_function_evaluated_three_ways
    ]()
    suite.test[test_optimize__test_least_squares_finds_the_rosenbrock_minimum]()
    suite.test[
        test_optimize__test_least_squares_recovers_an_exactly_fitting_line
    ]()
    suite.test[
        test_optimize__test_curve_fit_recovers_the_parameters_of_exact_data
    ]()
    suite.test[test_optimize__test_curve_fit_averages_the_noise_it_cannot_fit]()
    suite.test[
        test_optimize__test_curve_fit_and_least_squares_agree_on_the_same_problem
    ]()
    suite.test[
        test_optimize__test_the_fitted_jacobian_is_exact_where_a_difference_is_not
    ]()
    suite.test[test_optimize__test_nelder_mead_minimizes_rosenbrock]()
    suite.test[test_optimize__test_nelder_mead_minimizes_a_quadratic_bowl]()
    suite.test[
        test_optimize__test_nelder_mead_handles_the_kinks_that_defeat_a_gradient
    ]()
    suite.test[
        test_optimize__test_nelder_mead_reports_the_gradient_it_did_not_use
    ]()
    suite.test[
        test_optimize__test_nelder_mead_and_bfgs_land_on_the_same_minimum
    ]()
    # tests/optimize/test_solve.mojo
    suite.test[test_solve__test_newton_finds_the_cube_root_of_two]()
    suite.test[test_solve__test_newton_finds_the_dottie_number]()
    suite.test[test_solve__test_newton_finds_a_logarithm]()
    suite.test[test_solve__test_newton_converges_from_a_poor_guess]()
    suite.test[test_solve__test_newton_solves_each_simd_lane_independently]()
    suite.test[test_solve__test_newton_at_a_critical_point_stays_finite]()
    suite.test[test_solve__test_halley_matches_newton]()
    suite.test[test_solve__test_halley_converges_faster_than_newton]()
    suite.test[test_solve__test_halley_on_a_transcendental]()
    suite.test[test_solve__test_bisection_finds_the_cube_root_of_two]()
    suite.test[
        test_solve__test_bisection_works_with_the_bracket_either_way_around
    ]()
    suite.test[
        test_solve__test_bisection_needs_no_derivative_and_cannot_diverge
    ]()
    suite.test[test_solve__test_bisection_bisects_lanes_independently]()
    suite.test[test_solve__test_solving_at_dual_differentiates_the_root]()
    # tests/optimize/test_tensor_least_squares.mojo
    suite.test[
        test_tensor_least_squares__test_least_squares_recovers_an_exact_exponential_fit
    ]()
    suite.test[
        test_tensor_least_squares__test_least_squares_solves_a_linear_fit
    ]()
    suite.test[
        test_tensor_least_squares__test_least_squares_starting_at_the_solution_converges_immediately
    ]()
    suite.test[
        test_tensor_least_squares__test_least_squares_reports_failure_rather_than_raising
    ]()
    suite.test[
        test_tensor_least_squares__test_curve_fit_matches_least_squares_on_the_same_problem
    ]()
    suite.test[test_tensor_least_squares__test_the_two_tiers_agree]()
    # tests/optimize/test_tensor_minimize.mojo
    suite.test[test_tensor_minimize__test_bfgs_minimizes_rosenbrock]()
    suite.test[test_tensor_minimize__test_cg_minimizes_rosenbrock]()
    suite.test[test_tensor_minimize__test_bfgs_minimizes_a_quadratic_bowl]()
    suite.test[test_tensor_minimize__test_cg_minimizes_a_quadratic_bowl]()
    suite.test[
        test_tensor_minimize__test_starting_at_the_minimum_converges_immediately
    ]()
    suite.test[test_tensor_minimize__test_the_two_tiers_agree]()
    suite.test[test_tensor_minimize__test_the_context_survives_a_whole_run]()
    suite.test[
        test_tensor_minimize__test_grad_norm_is_the_quantity_that_converged
    ]()
    suite.test[
        test_tensor_minimize__test_a_tight_iteration_cap_reports_failure
    ]()
    suite.test[test_tensor_minimize__test_an_unknown_method_raises]()
    # tests/optimize/test_tensor_optimize.mojo
    suite.test[
        test_tensor_optimize__test_lbfgs_reaches_the_rosenbrock_minimum
    ]()
    suite.test[
        test_tensor_optimize__test_lbfgs_agrees_with_bfgs_on_a_quadratic
    ]()
    suite.test[
        test_tensor_optimize__test_bounded_minimize_stops_on_the_active_bound
    ]()
    suite.test[
        test_tensor_optimize__test_powell_needs_no_gradient_and_finds_the_minimum
    ]()
    suite.test[
        test_tensor_optimize__test_a_gradient_method_without_jac_raises
    ]()
    suite.test[
        test_tensor_optimize__test_root_by_newton_and_lm_both_find_scipys_root
    ]()
    suite.test[test_tensor_optimize__test_nnls_matches_scipy]()
    suite.test[
        test_tensor_optimize__test_lsq_linear_matches_scipy_with_and_without_active_bounds
    ]()
    suite^.run()
