"""GENERATED by tools/gen_test_aggregates.py -- do not edit.

Aggregates the 16 test files of `tests/special/` into one compiled
binary, so 16 compiler invocations become one. Run it with
`mojo -I . -I tests/special` (see tools/run_test_aggregates.sh).

Regenerate with `pixi run tests-gen`; CI fails if this file is out of date
with the tree.
"""

from std.testing import TestSuite
from test_activations import (
    test_relu_matches_max_with_zero as test_activations__test_relu_matches_max_with_zero,
)
from test_activations import (
    test_relu_derivative_is_zero_or_one as test_activations__test_relu_derivative_is_zero_or_one,
)
from test_activations import (
    test_leaky_relu_matches_closed_form as test_activations__test_leaky_relu_matches_closed_form,
)
from test_activations import (
    test_leaky_relu_derivative_is_one_or_alpha as test_activations__test_leaky_relu_derivative_is_one_or_alpha,
)
from test_activations import (
    test_gelu_at_zero_is_zero as test_activations__test_gelu_at_zero_is_zero,
)
from test_activations import (
    test_gelu_matches_known_value as test_activations__test_gelu_matches_known_value,
)
from test_activations import (
    test_softmax_rows_sum_to_one_and_match_reference as test_activations__test_softmax_rows_sum_to_one_and_match_reference,
)
from test_airy import (
    test_airy_matches_mpmath_in_all_three_regions as test_airy__test_airy_matches_mpmath_in_all_three_regions,
)
from test_airy import (
    test_airy_derivative_slots_agree_with_dual as test_airy__test_airy_derivative_slots_agree_with_dual,
)
from test_airy import (
    test_airy_wronskian_is_one_over_pi as test_airy__test_airy_wronskian_is_one_over_pi,
)
from test_airy import (
    test_struve_matches_mpmath_on_both_sides_of_forty as test_airy__test_struve_matches_mpmath_on_both_sides_of_forty,
)
from test_airy import (
    test_struve_half_order_is_elementary_and_differentiates as test_airy__test_struve_half_order_is_elementary_and_differentiates,
)
from test_bessel import (
    test_bessel_j0_at_zero_is_one as test_bessel__test_bessel_j0_at_zero_is_one,
)
from test_bessel import (
    test_bessel_j0_matches_known_values as test_bessel__test_bessel_j0_matches_known_values,
)
from test_bessel import (
    test_bessel_j0_is_even as test_bessel__test_bessel_j0_is_even,
)
from test_bessel import (
    test_bessel_j0_far_branch_matches_std_math as test_bessel__test_bessel_j0_far_branch_matches_std_math,
)
from test_bessel import (
    test_bessel_j0_blend_is_continuous_at_the_boundary as test_bessel__test_bessel_j0_blend_is_continuous_at_the_boundary,
)
from test_bessel import (
    test_bessel_j1_is_odd as test_bessel__test_bessel_j1_is_odd,
)
from test_bessel import (
    test_bessel_j1_at_zero_is_zero as test_bessel__test_bessel_j1_at_zero_is_zero,
)
from test_bessel import (
    test_bessel_j1_matches_std_math_near_and_far as test_bessel__test_bessel_j1_matches_std_math_near_and_far,
)
from test_bessel import (
    test_bessel_y0_matches_std_math_near_and_far as test_bessel__test_bessel_y0_matches_std_math_near_and_far,
)
from test_bessel import (
    test_bessel_y1_matches_std_math_near_and_far as test_bessel__test_bessel_y1_matches_std_math_near_and_far,
)
from test_bessel import (
    test_bessel_j0_derivative_is_negative_j1 as test_bessel__test_bessel_j0_derivative_is_negative_j1,
)
from test_besselv import (
    test_jv_matches_mpmath_across_orders_and_both_regions as test_besselv__test_jv_matches_mpmath_across_orders_and_both_regions,
)
from test_besselv import (
    test_yv_matches_mpmath_across_orders_and_both_regions as test_besselv__test_yv_matches_mpmath_across_orders_and_both_regions,
)
from test_besselv import (
    test_negative_orders_reflect_and_are_exact_at_integers as test_besselv__test_negative_orders_reflect_and_are_exact_at_integers,
)
from test_besselv import (
    test_half_integer_orders_are_elementary as test_besselv__test_half_integer_orders_are_elementary,
)
from test_besselv import (
    test_integer_orders_agree_with_the_polynomial_j0_j1_within_their_bound as test_besselv__test_integer_orders_agree_with_the_polynomial_j0_j1_within_their_bound,
)
from test_besselv import (
    test_iv_kv_match_mpmath_and_the_scaled_forms_agree as test_besselv__test_iv_kv_match_mpmath_and_the_scaled_forms_agree,
)
from test_besselv import (
    test_spherical_bessel_functions as test_besselv__test_spherical_bessel_functions,
)
from test_besselv import (
    test_bessel_functions_differentiate as test_besselv__test_bessel_functions_differentiate,
)
from test_beta import (
    test_beta_at_small_integers as test_beta__test_beta_at_small_integers,
)
from test_beta import (
    test_beta_at_one_half_is_pi as test_beta__test_beta_at_one_half_is_pi,
)
from test_beta import (
    test_beta_is_symmetric as test_beta__test_beta_is_symmetric,
)
from test_beta import (
    test_betainc_with_both_parameters_one_is_the_identity as test_beta__test_betainc_with_both_parameters_one_is_the_identity,
)
from test_beta import (
    test_betainc_is_one_half_at_the_symmetric_midpoint as test_beta__test_betainc_is_one_half_at_the_symmetric_midpoint,
)
from test_beta import (
    test_betainc_with_b_equal_one_is_a_power as test_beta__test_betainc_with_b_equal_one_is_a_power,
)
from test_beta import (
    test_betainc_with_a_equal_one_is_one_minus_a_power as test_beta__test_betainc_with_a_equal_one_is_one_minus_a_power,
)
from test_beta import (
    test_betainc_at_the_endpoints as test_beta__test_betainc_at_the_endpoints,
)
from test_beta import (
    test_betainc_reflection_symmetry as test_beta__test_betainc_reflection_symmetry,
)
from test_beta import (
    test_betainc_matches_the_parameter_recurrence as test_beta__test_betainc_matches_the_parameter_recurrence,
)
from test_beta import (
    test_betainc_is_monotone as test_beta__test_betainc_is_monotone,
)
from test_beta import (
    test_betaincc_is_one_minus_betainc as test_beta__test_betaincc_is_one_minus_betainc,
)
from test_beta import (
    test_betainc_derivative_matches_the_density as test_beta__test_betainc_derivative_matches_the_density,
)
from test_beta import (
    test_beta_relates_to_the_gamma_ratio_numerically as test_beta__test_beta_relates_to_the_gamma_ratio_numerically,
)
from test_beta import (
    test_betaln_agrees_with_the_log_of_beta_where_beta_survives as test_beta__test_betaln_agrees_with_the_log_of_beta_where_beta_survives,
)
from test_beta import (
    test_betaln_survives_where_beta_underflows_to_zero as test_beta__test_betaln_survives_where_beta_underflows_to_zero,
)
from test_beta import (
    test_betaln_is_symmetric_and_differentiable as test_beta__test_betaln_is_symmetric_and_differentiable,
)
from test_elliptic import (
    test_elliptic_k_e_at_zero_are_pi_over_two as test_elliptic__test_elliptic_k_e_at_zero_are_pi_over_two,
)
from test_elliptic import (
    test_elliptic_e_at_one_is_one as test_elliptic__test_elliptic_e_at_one_is_one,
)
from test_elliptic import (
    test_elliptic_k_diverges_but_stays_finite_at_one as test_elliptic__test_elliptic_k_diverges_but_stays_finite_at_one,
)
from test_elliptic import (
    test_elliptic_k_matches_agm_reference as test_elliptic__test_elliptic_k_matches_agm_reference,
)
from test_elliptic import (
    test_elliptic_e_matches_agm_reference as test_elliptic__test_elliptic_e_matches_agm_reference,
)
from test_elliptic import (
    test_elliptic_k_derivative_matches_closed_form as test_elliptic__test_elliptic_k_derivative_matches_closed_form,
)
from test_elliptic import (
    test_elliptic_e_derivative_matches_closed_form as test_elliptic__test_elliptic_e_derivative_matches_closed_form,
)
from test_enclosure import (
    test_erf_encloses_its_range as test_enclosure__test_erf_encloses_its_range,
)
from test_enclosure import (
    test_erf_enclosure_is_tight_when_monotone as test_enclosure__test_erf_enclosure_is_tight_when_monotone,
)
from test_enclosure import (
    test_erfc_encloses_and_reverses_the_endpoints as test_enclosure__test_erfc_encloses_and_reverses_the_endpoints,
)
from test_enclosure import (
    test_gaussian_encloses_across_its_peak as test_enclosure__test_gaussian_encloses_across_its_peak,
)
from test_enclosure import (
    test_bessel_j0_and_j1_enclose_inside_the_near_branch as test_enclosure__test_bessel_j0_and_j1_enclose_inside_the_near_branch,
)
from test_enclosure import (
    test_degenerate_interval_is_the_point_value as test_enclosure__test_degenerate_interval_is_the_point_value,
)
from test_enclosure import (
    test_decimal_arithmetic_is_exact_through_a_kernel as test_enclosure__test_decimal_arithmetic_is_exact_through_a_kernel,
)
from test_enclosure import (
    test_decimal_erf_agrees_with_plain_to_the_approximation as test_enclosure__test_decimal_erf_agrees_with_plain_to_the_approximation,
)
from test_enclosure import (
    test_decimal_bessel_and_expi_agree_with_plain as test_enclosure__test_decimal_bessel_and_expi_agree_with_plain,
)
from test_enclosure import (
    test_decimal_gamma_agrees_with_plain_to_fixed_point_precision as test_enclosure__test_decimal_gamma_agrees_with_plain_to_fixed_point_precision,
)
from test_erf import (
    test_erf_at_zero_is_zero as test_erf__test_erf_at_zero_is_zero,
)
from test_erf import (
    test_erf_matches_known_values as test_erf__test_erf_matches_known_values,
)
from test_erf import test_erf_is_odd as test_erf__test_erf_is_odd
from test_erf import (
    test_erf_derivative_matches_closed_form as test_erf__test_erf_derivative_matches_closed_form,
)
from test_erf import (
    test_erfc_is_one_minus_erf as test_erf__test_erfc_is_one_minus_erf,
)
from test_erf import (
    test_erfinv_matches_scipy_at_known_points as test_erf__test_erfinv_matches_scipy_at_known_points,
)
from test_erf import (
    test_erfinv_inverts_erf_both_ways as test_erf__test_erfinv_inverts_erf_both_ways,
)
from test_erf import (
    test_erfinv_is_odd_and_zero_at_zero as test_erf__test_erfinv_is_odd_and_zero_at_zero,
)
from test_erf import (
    test_erfinv_is_finite_at_the_clamped_endpoint as test_erf__test_erfinv_is_finite_at_the_clamped_endpoint,
)
from test_erf import (
    test_erfinv_stays_accurate_where_erf_saturates_to_one as test_erf__test_erfinv_stays_accurate_where_erf_saturates_to_one,
)
from test_erf import (
    test_erfinv_derivative_matches_closed_form as test_erf__test_erfinv_derivative_matches_closed_form,
)
from test_erf import (
    test_erfcinv_is_erfinv_of_one_minus_y as test_erf__test_erfcinv_is_erfinv_of_one_minus_y,
)
from test_expint import (
    test_exp1_matches_mpmath_across_the_blend as test_expint__test_exp1_matches_mpmath_across_the_blend,
)
from test_expint import (
    test_expi_matches_mpmath_on_both_sides_of_zero as test_expint__test_expi_matches_mpmath_on_both_sides_of_zero,
)
from test_expint import (
    test_expi_asymptotic_region_and_derivative as test_expint__test_expi_asymptotic_region_and_derivative,
)
from test_expint import (
    test_expn_matches_mpmath as test_expint__test_expn_matches_mpmath,
)
from test_expint import (
    test_sici_matches_mpmath_and_is_odd_in_si as test_expint__test_sici_matches_mpmath_and_is_odd_in_si,
)
from test_expint import (
    test_fresnel_matches_mpmath_and_is_odd as test_expint__test_fresnel_matches_mpmath_and_is_odd,
)
from test_gamma import (
    test_gamma_at_positive_integers_matches_factorial as test_gamma__test_gamma_at_positive_integers_matches_factorial,
)
from test_gamma import (
    test_gamma_at_one_half_is_sqrt_pi as test_gamma__test_gamma_at_one_half_is_sqrt_pi,
)
from test_gamma import (
    test_lgamma_matches_ln_of_gamma as test_gamma__test_lgamma_matches_ln_of_gamma,
)
from test_gamma import (
    test_lgamma_derivative_matches_digamma as test_gamma__test_lgamma_derivative_matches_digamma,
)
from test_gamma import (
    test_gamma_derivative_matches_gamma_times_digamma as test_gamma__test_gamma_derivative_matches_gamma_times_digamma,
)
from test_gamma import (
    test_gammainc_matches_closed_form_for_integer_a as test_gamma__test_gammainc_matches_closed_form_for_integer_a,
)
from test_gamma import (
    test_gammainc_at_a_equals_one_is_exponential_cdf as test_gamma__test_gammainc_at_a_equals_one_is_exponential_cdf,
)
from test_gamma import (
    test_gammaincc_is_one_minus_gammainc as test_gamma__test_gammaincc_is_one_minus_gammainc,
)
from test_gamma import (
    test_gammainc_approaches_one_for_large_x as test_gamma__test_gammainc_approaches_one_for_large_x,
)
from test_gamma import (
    test_gamma_reflects_to_negative_non_integers as test_gamma__test_gamma_reflects_to_negative_non_integers,
)
from test_gamma import (
    test_lgamma_reflects_to_negative_non_integers as test_gamma__test_lgamma_reflects_to_negative_non_integers,
)
from test_gamma import (
    test_gamma_agrees_at_the_reflection_boundary as test_gamma__test_gamma_agrees_at_the_reflection_boundary,
)
from test_gamma import (
    test_gamma_derivative_matches_gamma_times_digamma_for_negative_x as test_gamma__test_gamma_derivative_matches_gamma_times_digamma_for_negative_x,
)
from test_gamma import (
    test_gammainc_matches_recurrence_for_negative_a as test_gamma__test_gammainc_matches_recurrence_for_negative_a,
)
from test_gamma import (
    test_digamma_matches_closed_form_values as test_gamma__test_digamma_matches_closed_form_values,
)
from test_gamma import (
    test_digamma_satisfies_the_recurrence as test_gamma__test_digamma_satisfies_the_recurrence,
)
from test_gamma import (
    test_digamma_reflects_to_negative_arguments as test_gamma__test_digamma_reflects_to_negative_arguments,
)
from test_hyper import (
    test_riemann_zeta_matches_mpmath_on_both_sides_of_the_pole as test_hyper__test_riemann_zeta_matches_mpmath_on_both_sides_of_the_pole,
)
from test_hyper import (
    test_riemann_zeta_reflects_far_below_the_pole as test_hyper__test_riemann_zeta_reflects_far_below_the_pole,
)
from test_hyper import (
    test_riemann_zeta_vanishes_at_the_trivial_zeros as test_hyper__test_riemann_zeta_vanishes_at_the_trivial_zeros,
)
from test_hyper import (
    test_hurwitz_zeta_matches_mpmath_and_reduces_to_riemann as test_hyper__test_hurwitz_zeta_matches_mpmath_and_reduces_to_riemann,
)
from test_hyper import (
    test_hyp1f1_matches_mpmath_on_both_sides_of_zero as test_hyper__test_hyp1f1_matches_mpmath_on_both_sides_of_zero,
)
from test_hyper import (
    test_hyp2f1_matches_mpmath_on_both_sides_of_zero as test_hyper__test_hyp2f1_matches_mpmath_on_both_sides_of_zero,
)
from test_hyper import (
    test_hyp2f1_past_nine_tenths_matches_mpmath as test_hyper__test_hyp2f1_past_nine_tenths_matches_mpmath,
)
from test_hyper import (
    test_hyp2f1_at_an_integer_d_falls_back_to_the_series as test_hyper__test_hyp2f1_at_an_integer_d_falls_back_to_the_series,
)
from test_hyper import (
    test_hypergeometric_functions_differentiate as test_hyper__test_hypergeometric_functions_differentiate,
)
from test_information import (
    test_combinatorics_match_scipy as test_information__test_combinatorics_match_scipy,
)
from test_information import (
    test_xlogy_and_xlog1py_apply_the_zero_convention as test_information__test_xlogy_and_xlog1py_apply_the_zero_convention,
)
from test_information import (
    test_entropy_terms_match_scipy as test_information__test_entropy_terms_match_scipy,
)
from test_information import (
    test_logit_inverts_the_sigmoid as test_information__test_logit_inverts_the_sigmoid,
)
from test_information import (
    test_information_functions_differentiate as test_information__test_information_functions_differentiate,
)
from test_information import (
    test_logsumexp_over_an_array_is_stable_and_differentiates as test_information__test_logsumexp_over_an_array_is_stable_and_differentiates,
)
from test_information import (
    test_logsumexp_over_a_tensor_matches_scipy_and_the_array_tier as test_information__test_logsumexp_over_a_tensor_matches_scipy_and_the_array_tier,
)
from test_lambertw import (
    test_lambertw_at_zero_is_zero as test_lambertw__test_lambertw_at_zero_is_zero,
)
from test_lambertw import (
    test_lambertw_at_one_is_omega_constant as test_lambertw__test_lambertw_at_one_is_omega_constant,
)
from test_lambertw import (
    test_lambertw_at_e_is_one as test_lambertw__test_lambertw_at_e_is_one,
)
from test_lambertw import (
    test_lambertw_satisfies_w_exp_w_equals_x as test_lambertw__test_lambertw_satisfies_w_exp_w_equals_x,
)
from test_lambertw import (
    test_lambertw_derivative_matches_closed_form as test_lambertw__test_lambertw_derivative_matches_closed_form,
)
from test_lambertw import (
    test_lambertw_extends_to_negative_x_down_to_branch_point as test_lambertw__test_lambertw_extends_to_negative_x_down_to_branch_point,
)
from test_lambertw import (
    test_lambertw_m1_satisfies_w_exp_w_equals_x as test_lambertw__test_lambertw_m1_satisfies_w_exp_w_equals_x,
)
from test_lambertw import (
    test_lambertw_m1_matches_known_values as test_lambertw__test_lambertw_m1_matches_known_values,
)
from test_lambertw import (
    test_lambertw_m1_stays_accurate_at_extreme_small_x as test_lambertw__test_lambertw_m1_stays_accurate_at_extreme_small_x,
)
from test_lambertw import (
    test_lambertw_and_lambertw_m1_agree_at_the_branch_point as test_lambertw__test_lambertw_and_lambertw_m1_agree_at_the_branch_point,
)
from test_lambertw import (
    test_lambertw_m1_derivative_matches_closed_form as test_lambertw__test_lambertw_m1_derivative_matches_closed_form,
)
from test_legendre import (
    test_low_degrees_match_closed_forms as test_legendre__test_low_degrees_match_closed_forms,
)
from test_legendre import (
    test_endpoints_are_plus_minus_one as test_legendre__test_endpoints_are_plus_minus_one,
)
from test_legendre import (
    test_negative_degree_is_p0 as test_legendre__test_negative_degree_is_p0,
)
from test_legendre import (
    test_derivative_matches_the_standard_identity as test_legendre__test_derivative_matches_the_standard_identity,
)
from test_legendre import (
    test_orthogonality_by_quadrature_on_a_fine_grid as test_legendre__test_orthogonality_by_quadrature_on_a_fine_grid,
)
from test_owens import (
    test_owens_t_matches_mpmath_quadrature as test_owens__test_owens_t_matches_mpmath_quadrature,
)
from test_owens import (
    test_owens_t_symmetries_and_closed_forms as test_owens__test_owens_t_symmetries_and_closed_forms,
)
from test_owens import (
    test_owens_t_differentiates_in_h as test_owens__test_owens_t_differentiates_in_h,
)
from test_special import (
    test_gaussian_value as test_special__test_gaussian_value,
)
from test_special import (
    test_gaussian_derivative as test_special__test_gaussian_derivative,
)
from test_special import (
    test_sigmoid_at_zero as test_special__test_sigmoid_at_zero,
)
from test_special import (
    test_sigmoid_derivative_is_p_times_one_minus_p as test_special__test_sigmoid_derivative_is_p_times_one_minus_p,
)
from test_special import (
    test_swish_is_x_times_sigmoid as test_special__test_swish_is_x_times_sigmoid,
)
from test_special import (
    test_tanh_matches_sigmoid_identity as test_special__test_tanh_matches_sigmoid_identity,
)


def main() raises:
    var suite = TestSuite()
    # tests/special/test_activations.mojo
    suite.test[test_activations__test_relu_matches_max_with_zero]()
    suite.test[test_activations__test_relu_derivative_is_zero_or_one]()
    suite.test[test_activations__test_leaky_relu_matches_closed_form]()
    suite.test[test_activations__test_leaky_relu_derivative_is_one_or_alpha]()
    suite.test[test_activations__test_gelu_at_zero_is_zero]()
    suite.test[test_activations__test_gelu_matches_known_value]()
    suite.test[
        test_activations__test_softmax_rows_sum_to_one_and_match_reference
    ]()
    # tests/special/test_airy.mojo
    suite.test[test_airy__test_airy_matches_mpmath_in_all_three_regions]()
    suite.test[test_airy__test_airy_derivative_slots_agree_with_dual]()
    suite.test[test_airy__test_airy_wronskian_is_one_over_pi]()
    suite.test[test_airy__test_struve_matches_mpmath_on_both_sides_of_forty]()
    suite.test[
        test_airy__test_struve_half_order_is_elementary_and_differentiates
    ]()
    # tests/special/test_bessel.mojo
    suite.test[test_bessel__test_bessel_j0_at_zero_is_one]()
    suite.test[test_bessel__test_bessel_j0_matches_known_values]()
    suite.test[test_bessel__test_bessel_j0_is_even]()
    suite.test[test_bessel__test_bessel_j0_far_branch_matches_std_math]()
    suite.test[
        test_bessel__test_bessel_j0_blend_is_continuous_at_the_boundary
    ]()
    suite.test[test_bessel__test_bessel_j1_is_odd]()
    suite.test[test_bessel__test_bessel_j1_at_zero_is_zero]()
    suite.test[test_bessel__test_bessel_j1_matches_std_math_near_and_far]()
    suite.test[test_bessel__test_bessel_y0_matches_std_math_near_and_far]()
    suite.test[test_bessel__test_bessel_y1_matches_std_math_near_and_far]()
    suite.test[test_bessel__test_bessel_j0_derivative_is_negative_j1]()
    # tests/special/test_besselv.mojo
    suite.test[
        test_besselv__test_jv_matches_mpmath_across_orders_and_both_regions
    ]()
    suite.test[
        test_besselv__test_yv_matches_mpmath_across_orders_and_both_regions
    ]()
    suite.test[
        test_besselv__test_negative_orders_reflect_and_are_exact_at_integers
    ]()
    suite.test[test_besselv__test_half_integer_orders_are_elementary]()
    suite.test[
        test_besselv__test_integer_orders_agree_with_the_polynomial_j0_j1_within_their_bound
    ]()
    suite.test[
        test_besselv__test_iv_kv_match_mpmath_and_the_scaled_forms_agree
    ]()
    suite.test[test_besselv__test_spherical_bessel_functions]()
    suite.test[test_besselv__test_bessel_functions_differentiate]()
    # tests/special/test_beta.mojo
    suite.test[test_beta__test_beta_at_small_integers]()
    suite.test[test_beta__test_beta_at_one_half_is_pi]()
    suite.test[test_beta__test_beta_is_symmetric]()
    suite.test[
        test_beta__test_betainc_with_both_parameters_one_is_the_identity
    ]()
    suite.test[test_beta__test_betainc_is_one_half_at_the_symmetric_midpoint]()
    suite.test[test_beta__test_betainc_with_b_equal_one_is_a_power]()
    suite.test[test_beta__test_betainc_with_a_equal_one_is_one_minus_a_power]()
    suite.test[test_beta__test_betainc_at_the_endpoints]()
    suite.test[test_beta__test_betainc_reflection_symmetry]()
    suite.test[test_beta__test_betainc_matches_the_parameter_recurrence]()
    suite.test[test_beta__test_betainc_is_monotone]()
    suite.test[test_beta__test_betaincc_is_one_minus_betainc]()
    suite.test[test_beta__test_betainc_derivative_matches_the_density]()
    suite.test[test_beta__test_beta_relates_to_the_gamma_ratio_numerically]()
    suite.test[
        test_beta__test_betaln_agrees_with_the_log_of_beta_where_beta_survives
    ]()
    suite.test[test_beta__test_betaln_survives_where_beta_underflows_to_zero]()
    suite.test[test_beta__test_betaln_is_symmetric_and_differentiable]()
    # tests/special/test_elliptic.mojo
    suite.test[test_elliptic__test_elliptic_k_e_at_zero_are_pi_over_two]()
    suite.test[test_elliptic__test_elliptic_e_at_one_is_one]()
    suite.test[
        test_elliptic__test_elliptic_k_diverges_but_stays_finite_at_one
    ]()
    suite.test[test_elliptic__test_elliptic_k_matches_agm_reference]()
    suite.test[test_elliptic__test_elliptic_e_matches_agm_reference]()
    suite.test[test_elliptic__test_elliptic_k_derivative_matches_closed_form]()
    suite.test[test_elliptic__test_elliptic_e_derivative_matches_closed_form]()
    # tests/special/test_enclosure.mojo
    suite.test[test_enclosure__test_erf_encloses_its_range]()
    suite.test[test_enclosure__test_erf_enclosure_is_tight_when_monotone]()
    suite.test[test_enclosure__test_erfc_encloses_and_reverses_the_endpoints]()
    suite.test[test_enclosure__test_gaussian_encloses_across_its_peak]()
    suite.test[
        test_enclosure__test_bessel_j0_and_j1_enclose_inside_the_near_branch
    ]()
    suite.test[test_enclosure__test_degenerate_interval_is_the_point_value]()
    suite.test[
        test_enclosure__test_decimal_arithmetic_is_exact_through_a_kernel
    ]()
    suite.test[
        test_enclosure__test_decimal_erf_agrees_with_plain_to_the_approximation
    ]()
    suite.test[test_enclosure__test_decimal_bessel_and_expi_agree_with_plain]()
    suite.test[
        test_enclosure__test_decimal_gamma_agrees_with_plain_to_fixed_point_precision
    ]()
    # tests/special/test_erf.mojo
    suite.test[test_erf__test_erf_at_zero_is_zero]()
    suite.test[test_erf__test_erf_matches_known_values]()
    suite.test[test_erf__test_erf_is_odd]()
    suite.test[test_erf__test_erf_derivative_matches_closed_form]()
    suite.test[test_erf__test_erfc_is_one_minus_erf]()
    suite.test[test_erf__test_erfinv_matches_scipy_at_known_points]()
    suite.test[test_erf__test_erfinv_inverts_erf_both_ways]()
    suite.test[test_erf__test_erfinv_is_odd_and_zero_at_zero]()
    suite.test[test_erf__test_erfinv_is_finite_at_the_clamped_endpoint]()
    suite.test[
        test_erf__test_erfinv_stays_accurate_where_erf_saturates_to_one
    ]()
    suite.test[test_erf__test_erfinv_derivative_matches_closed_form]()
    suite.test[test_erf__test_erfcinv_is_erfinv_of_one_minus_y]()
    # tests/special/test_expint.mojo
    suite.test[test_expint__test_exp1_matches_mpmath_across_the_blend]()
    suite.test[test_expint__test_expi_matches_mpmath_on_both_sides_of_zero]()
    suite.test[test_expint__test_expi_asymptotic_region_and_derivative]()
    suite.test[test_expint__test_expn_matches_mpmath]()
    suite.test[test_expint__test_sici_matches_mpmath_and_is_odd_in_si]()
    suite.test[test_expint__test_fresnel_matches_mpmath_and_is_odd]()
    # tests/special/test_gamma.mojo
    suite.test[test_gamma__test_gamma_at_positive_integers_matches_factorial]()
    suite.test[test_gamma__test_gamma_at_one_half_is_sqrt_pi]()
    suite.test[test_gamma__test_lgamma_matches_ln_of_gamma]()
    suite.test[test_gamma__test_lgamma_derivative_matches_digamma]()
    suite.test[test_gamma__test_gamma_derivative_matches_gamma_times_digamma]()
    suite.test[test_gamma__test_gammainc_matches_closed_form_for_integer_a]()
    suite.test[test_gamma__test_gammainc_at_a_equals_one_is_exponential_cdf]()
    suite.test[test_gamma__test_gammaincc_is_one_minus_gammainc]()
    suite.test[test_gamma__test_gammainc_approaches_one_for_large_x]()
    suite.test[test_gamma__test_gamma_reflects_to_negative_non_integers]()
    suite.test[test_gamma__test_lgamma_reflects_to_negative_non_integers]()
    suite.test[test_gamma__test_gamma_agrees_at_the_reflection_boundary]()
    suite.test[
        test_gamma__test_gamma_derivative_matches_gamma_times_digamma_for_negative_x
    ]()
    suite.test[test_gamma__test_gammainc_matches_recurrence_for_negative_a]()
    suite.test[test_gamma__test_digamma_matches_closed_form_values]()
    suite.test[test_gamma__test_digamma_satisfies_the_recurrence]()
    suite.test[test_gamma__test_digamma_reflects_to_negative_arguments]()
    # tests/special/test_hyper.mojo
    suite.test[
        test_hyper__test_riemann_zeta_matches_mpmath_on_both_sides_of_the_pole
    ]()
    suite.test[test_hyper__test_riemann_zeta_reflects_far_below_the_pole]()
    suite.test[test_hyper__test_riemann_zeta_vanishes_at_the_trivial_zeros]()
    suite.test[
        test_hyper__test_hurwitz_zeta_matches_mpmath_and_reduces_to_riemann
    ]()
    suite.test[test_hyper__test_hyp1f1_matches_mpmath_on_both_sides_of_zero]()
    suite.test[test_hyper__test_hyp2f1_matches_mpmath_on_both_sides_of_zero]()
    suite.test[test_hyper__test_hyp2f1_past_nine_tenths_matches_mpmath]()
    suite.test[
        test_hyper__test_hyp2f1_at_an_integer_d_falls_back_to_the_series
    ]()
    suite.test[test_hyper__test_hypergeometric_functions_differentiate]()
    # tests/special/test_information.mojo
    suite.test[test_information__test_combinatorics_match_scipy]()
    suite.test[
        test_information__test_xlogy_and_xlog1py_apply_the_zero_convention
    ]()
    suite.test[test_information__test_entropy_terms_match_scipy]()
    suite.test[test_information__test_logit_inverts_the_sigmoid]()
    suite.test[test_information__test_information_functions_differentiate]()
    suite.test[
        test_information__test_logsumexp_over_an_array_is_stable_and_differentiates
    ]()
    suite.test[
        test_information__test_logsumexp_over_a_tensor_matches_scipy_and_the_array_tier
    ]()
    # tests/special/test_lambertw.mojo
    suite.test[test_lambertw__test_lambertw_at_zero_is_zero]()
    suite.test[test_lambertw__test_lambertw_at_one_is_omega_constant]()
    suite.test[test_lambertw__test_lambertw_at_e_is_one]()
    suite.test[test_lambertw__test_lambertw_satisfies_w_exp_w_equals_x]()
    suite.test[test_lambertw__test_lambertw_derivative_matches_closed_form]()
    suite.test[
        test_lambertw__test_lambertw_extends_to_negative_x_down_to_branch_point
    ]()
    suite.test[test_lambertw__test_lambertw_m1_satisfies_w_exp_w_equals_x]()
    suite.test[test_lambertw__test_lambertw_m1_matches_known_values]()
    suite.test[
        test_lambertw__test_lambertw_m1_stays_accurate_at_extreme_small_x
    ]()
    suite.test[
        test_lambertw__test_lambertw_and_lambertw_m1_agree_at_the_branch_point
    ]()
    suite.test[test_lambertw__test_lambertw_m1_derivative_matches_closed_form]()
    # tests/special/test_legendre.mojo
    suite.test[test_legendre__test_low_degrees_match_closed_forms]()
    suite.test[test_legendre__test_endpoints_are_plus_minus_one]()
    suite.test[test_legendre__test_negative_degree_is_p0]()
    suite.test[test_legendre__test_derivative_matches_the_standard_identity]()
    suite.test[test_legendre__test_orthogonality_by_quadrature_on_a_fine_grid]()
    # tests/special/test_owens.mojo
    suite.test[test_owens__test_owens_t_matches_mpmath_quadrature]()
    suite.test[test_owens__test_owens_t_symmetries_and_closed_forms]()
    suite.test[test_owens__test_owens_t_differentiates_in_h]()
    # tests/special/test_special.mojo
    suite.test[test_special__test_gaussian_value]()
    suite.test[test_special__test_gaussian_derivative]()
    suite.test[test_special__test_sigmoid_at_zero]()
    suite.test[test_special__test_sigmoid_derivative_is_p_times_one_minus_p]()
    suite.test[test_special__test_swish_is_x_times_sigmoid]()
    suite.test[test_special__test_tanh_matches_sigmoid_identity]()
    suite^.run()
