"""GENERATED by tools/gen_test_aggregates.py -- do not edit.

Aggregates the 2 test files of `tests/spatial/` into one compiled
binary, so 2 compiler invocations become one. Run it with
`mojo -I . -I tests/spatial` (see tools/run_test_aggregates.sh).

Regenerate with `pixi run tests-gen`; CI fails if this file is out of date
with the tree.
"""

from std.testing import TestSuite
from test_distance import (
    test_cdist_matches_scipy as test_distance__test_cdist_matches_scipy,
)
from test_distance import (
    test_pdist_and_squareform as test_distance__test_pdist_and_squareform,
)
from test_kdtree import (
    test_query_matches_brute_force as test_kdtree__test_query_matches_brute_force,
)
from test_kdtree import (
    test_query_ball_point_matches_brute_force as test_kdtree__test_query_ball_point_matches_brute_force,
)
from test_kdtree import (
    test_degenerate_cases as test_kdtree__test_degenerate_cases,
)


def main() raises:
    var suite = TestSuite()
    # tests/spatial/test_distance.mojo
    suite.test[test_distance__test_cdist_matches_scipy]()
    suite.test[test_distance__test_pdist_and_squareform]()
    # tests/spatial/test_kdtree.mojo
    suite.test[test_kdtree__test_query_matches_brute_force]()
    suite.test[test_kdtree__test_query_ball_point_matches_brute_force]()
    suite.test[test_kdtree__test_degenerate_cases]()
    suite^.run()
