"""GENERATED by tools/gen_test_aggregates.py -- do not edit.

Aggregates the 1 test files of `tests/ndimage/` into one compiled
binary, so 1 compiler invocations become one. Run it with
`mojo -I . -I tests/ndimage` (see tools/run_test_aggregates.sh).

Regenerate with `pixi run tests-gen`; CI fails if this file is out of date
with the tree.
"""

from std.testing import TestSuite
from test_filters import (
    test_correlate_and_convolve_match_scipy as test_filters__test_correlate_and_convolve_match_scipy,
)
from test_filters import (
    test_separable_filters_match_scipy as test_filters__test_separable_filters_match_scipy,
)
from test_filters import (
    test_rank_filters_match_scipy as test_filters__test_rank_filters_match_scipy,
)


def main() raises:
    var suite = TestSuite()
    # tests/ndimage/test_filters.mojo
    suite.test[test_filters__test_correlate_and_convolve_match_scipy]()
    suite.test[test_filters__test_separable_filters_match_scipy]()
    suite.test[test_filters__test_rank_filters_match_scipy]()
    suite^.run()
