"""GENERATED by tools/gen_test_aggregates.py -- do not edit.

Aggregates the 4 test files of `tests/signal/` into one compiled
binary, so 4 compiler invocations become one. Run it with
`mojo -I . -I tests/signal` (see tools/run_test_aggregates.sh).

Regenerate with `pixi run tests-gen`; CI fails if this file is out of date
with the tree.
"""

from std.testing import TestSuite
from test_signal import (
    test_convolve_matches_numpy_on_an_asymmetric_pair as test_signal__test_convolve_matches_numpy_on_an_asymmetric_pair,
)
from test_signal import (
    test_convolve_with_a_delta_is_the_identity as test_signal__test_convolve_with_a_delta_is_the_identity,
)
from test_signal import (
    test_convolve_with_a_shifted_delta_shifts_the_signal as test_signal__test_convolve_with_a_shifted_delta_shifts_the_signal,
)
from test_signal import (
    test_convolve_is_commutative as test_signal__test_convolve_is_commutative,
)
from test_signal import (
    test_convolve_sums_to_the_product_of_the_sums as test_signal__test_convolve_sums_to_the_product_of_the_sums,
)
from test_signal import (
    test_convolve_mode_same_takes_the_central_window as test_signal__test_convolve_mode_same_takes_the_central_window,
)
from test_signal import (
    test_convolve_mode_same_centres_an_odd_kernel as test_signal__test_convolve_mode_same_centres_an_odd_kernel,
)
from test_signal import (
    test_correlate_matches_numpy_on_an_asymmetric_pair as test_signal__test_correlate_matches_numpy_on_an_asymmetric_pair,
)
from test_signal import (
    test_correlate_equals_convolve_with_a_reversed_kernel as test_signal__test_correlate_equals_convolve_with_a_reversed_kernel,
)
from test_signal import (
    test_autocorrelation_peaks_at_zero_lag as test_signal__test_autocorrelation_peaks_at_zero_lag,
)
from test_signal import (
    test_autocorrelation_at_zero_lag_is_the_energy as test_signal__test_autocorrelation_at_zero_lag_is_the_energy,
)
from test_signal import (
    test_hann_matches_its_closed_form as test_signal__test_hann_matches_its_closed_form,
)
from test_signal import (
    test_hann_endpoints_are_exactly_zero as test_signal__test_hann_endpoints_are_exactly_zero,
)
from test_signal import (
    test_hann_is_symmetric as test_signal__test_hann_is_symmetric,
)
from test_signal import (
    test_hann_peaks_at_one_for_odd_length as test_signal__test_hann_peaks_at_one_for_odd_length,
)
from test_signal import (
    test_hamming_endpoints_are_the_pedestal as test_signal__test_hamming_endpoints_are_the_pedestal,
)
from test_signal import (
    test_hamming_is_symmetric as test_signal__test_hamming_is_symmetric,
)
from test_signal import (
    test_blackman_endpoints_are_zero as test_signal__test_blackman_endpoints_are_zero,
)
from test_signal import (
    test_blackman_is_narrower_at_the_shoulders_than_hann as test_signal__test_blackman_is_narrower_at_the_shoulders_than_hann,
)
from test_signal import (
    test_apply_window_multiplies_elementwise as test_signal__test_apply_window_multiplies_elementwise,
)
from test_signal import (
    test_windowing_suppresses_spectral_leakage as test_signal__test_windowing_suppresses_spectral_leakage,
)
from test_signal import (
    test_convolve_differentiates_at_dual as test_signal__test_convolve_differentiates_at_dual,
)
from test_signal import (
    test_convolve_lanes_are_independent as test_signal__test_convolve_lanes_are_independent,
)
from test_signal import (
    test_linear_convolution_matches_zero_padded_circular as test_signal__test_linear_convolution_matches_zero_padded_circular,
)
from test_signal import (
    test_lfilter_with_no_recursion_is_a_convolution as test_signal__test_lfilter_with_no_recursion_is_a_convolution,
)
from test_signal import (
    test_lfilter_runs_a_recursion_no_convolution_can as test_signal__test_lfilter_runs_a_recursion_no_convolution_can,
)
from test_signal import (
    test_lfilter_divides_by_the_leading_coefficient as test_signal__test_lfilter_divides_by_the_leading_coefficient,
)
from test_signal import (
    test_firwin_passes_a_constant_unchanged as test_signal__test_firwin_passes_a_constant_unchanged,
)
from test_signal import (
    test_firwin_is_symmetric_so_the_phase_is_linear as test_signal__test_firwin_is_symmetric_so_the_phase_is_linear,
)
from test_signal import (
    test_firwin_attenuates_above_its_cutoff as test_signal__test_firwin_attenuates_above_its_cutoff,
)
from test_tensor_convolution import (
    test_convolve_matches_numpy_in_every_mode as test_tensor_convolution__test_convolve_matches_numpy_in_every_mode,
)
from test_tensor_convolution import (
    test_convolve_is_symmetric_in_its_arguments as test_tensor_convolution__test_convolve_is_symmetric_in_its_arguments,
)
from test_tensor_convolution import (
    test_correlate_matches_numpy_in_every_mode as test_tensor_convolution__test_correlate_matches_numpy_in_every_mode,
)
from test_tensor_convolution import (
    test_correlate_is_convolve_with_the_taps_reversed as test_tensor_convolution__test_correlate_is_convolve_with_the_taps_reversed,
)
from test_tensor_convolution import (
    test_fftconvolve_agrees_with_convolve_in_every_mode as test_tensor_convolution__test_fftconvolve_agrees_with_convolve_in_every_mode,
)
from test_tensor_convolution import (
    test_fftconvolve_of_long_inputs_agrees_with_the_direct_sum as test_tensor_convolution__test_fftconvolve_of_long_inputs_agrees_with_the_direct_sum,
)
from test_tensor_convolution import (
    test_windows_match_scipy_symmetric as test_tensor_convolution__test_windows_match_scipy_symmetric,
)
from test_tensor_convolution import (
    test_windows_match_scipy_periodic as test_tensor_convolution__test_windows_match_scipy_periodic,
)
from test_tensor_convolution import (
    test_kaiser_matches_scipy as test_tensor_convolution__test_kaiser_matches_scipy,
)
from test_tensor_convolution import (
    test_get_window_names_the_factories as test_tensor_convolution__test_get_window_names_the_factories,
)
from test_tensor_convolution import (
    test_convolve_accepts_views_of_both_operands as test_tensor_convolution__test_convolve_accepts_views_of_both_operands,
)
from test_tensor_filters import (
    test_lfilter_matches_scipy as test_tensor_filters__test_lfilter_matches_scipy,
)
from test_tensor_filters import (
    test_lfilter_normalizes_by_a0_and_takes_a_longer_numerator as test_tensor_filters__test_lfilter_normalizes_by_a0_and_takes_a_longer_numerator,
)
from test_tensor_filters import (
    test_lfilter_zi_matches_scipy as test_tensor_filters__test_lfilter_zi_matches_scipy,
)
from test_tensor_filters import (
    test_filtfilt_matches_scipy as test_tensor_filters__test_filtfilt_matches_scipy,
)
from test_tensor_filters import (
    test_sosfilt_matches_scipy as test_tensor_filters__test_sosfilt_matches_scipy,
)
from test_tensor_filters import (
    test_the_recurrence_runs_at_the_input_dtype as test_tensor_filters__test_the_recurrence_runs_at_the_input_dtype,
)
from test_tensor_filters import (
    test_the_in_place_passes_leave_their_input_alone as test_tensor_filters__test_the_in_place_passes_leave_their_input_alone,
)
from test_tensor_filters import (
    test_medfilt_matches_scipy as test_tensor_filters__test_medfilt_matches_scipy,
)
from test_tensor_filters import (
    test_detrend_matches_scipy as test_tensor_filters__test_detrend_matches_scipy,
)
from test_tensor_filters import (
    test_savgol_filter_matches_scipy_in_every_mode as test_tensor_filters__test_savgol_filter_matches_scipy_in_every_mode,
)
from test_tensor_filters import (
    test_savgol_filter_derivatives_match_scipy as test_tensor_filters__test_savgol_filter_derivatives_match_scipy,
)
from test_tensor_filters import (
    test_resample_matches_scipy as test_tensor_filters__test_resample_matches_scipy,
)
from test_tensor_filters import (
    test_firwin_matches_scipy as test_tensor_filters__test_firwin_matches_scipy,
)
from test_tensor_spectral import (
    test_periodogram_matches_scipy as test_tensor_spectral__test_periodogram_matches_scipy,
)
from test_tensor_spectral import (
    test_welch_matches_scipy as test_tensor_spectral__test_welch_matches_scipy,
)
from test_tensor_spectral import (
    test_spectrogram_matches_scipy as test_tensor_spectral__test_spectrogram_matches_scipy,
)
from test_tensor_spectral import (
    test_stft_matches_scipy as test_tensor_spectral__test_stft_matches_scipy,
)
from test_tensor_spectral import (
    test_hilbert_matches_scipy as test_tensor_spectral__test_hilbert_matches_scipy,
)
from test_tensor_spectral import (
    test_find_peaks_matches_scipy as test_tensor_spectral__test_find_peaks_matches_scipy,
)
from test_tensor_spectral import (
    test_butter_matches_scipy as test_tensor_spectral__test_butter_matches_scipy,
)
from test_tensor_spectral import (
    test_butter_band_forms_match_scipy as test_tensor_spectral__test_butter_band_forms_match_scipy,
)
from test_tensor_spectral import (
    test_cheby1_matches_scipy as test_tensor_spectral__test_cheby1_matches_scipy,
)
from test_tensor_spectral import (
    test_cheby2_matches_scipy as test_tensor_spectral__test_cheby2_matches_scipy,
)
from test_tensor_spectral import (
    test_ellip_matches_scipy as test_tensor_spectral__test_ellip_matches_scipy,
)
from test_tensor_spectral import (
    test_iirfilter_dispatches_on_ftype_and_refuses_an_unknown_one as test_tensor_spectral__test_iirfilter_dispatches_on_ftype_and_refuses_an_unknown_one,
)
from test_tensor_spectral import (
    test_the_ripple_and_attenuation_arguments_are_honored as test_tensor_spectral__test_the_ripple_and_attenuation_arguments_are_honored,
)
from test_tensor_spectral import (
    test_freqz_matches_scipy as test_tensor_spectral__test_freqz_matches_scipy,
)
from test_tensor_spectral import (
    test_butter_feeds_freqz_with_unit_gain_at_dc as test_tensor_spectral__test_butter_feeds_freqz_with_unit_gain_at_dc,
)
from test_tensor_spectral import (
    test_csd_of_a_signal_with_itself_is_its_welch_psd as test_tensor_spectral__test_csd_of_a_signal_with_itself_is_its_welch_psd,
)
from test_tensor_spectral import (
    test_csd_is_conjugate_symmetric_in_its_arguments as test_tensor_spectral__test_csd_is_conjugate_symmetric_in_its_arguments,
)
from test_tensor_spectral import (
    test_coherence_lies_in_the_unit_interval as test_tensor_spectral__test_coherence_lies_in_the_unit_interval,
)
from test_tensor_spectral import (
    test_coherence_of_a_signal_with_itself_is_one as test_tensor_spectral__test_coherence_of_a_signal_with_itself_is_one,
)
from test_tensor_spectral import (
    test_coherence_of_a_scaled_copy_is_also_one as test_tensor_spectral__test_coherence_of_a_scaled_copy_is_also_one,
)
from test_tensor_spectral import (
    test_istft_inverts_stft as test_tensor_spectral__test_istft_inverts_stft,
)
from test_tensor_spectral import (
    test_istft_output_covers_at_least_the_original_length as test_tensor_spectral__test_istft_output_covers_at_least_the_original_length,
)
from test_tensor_spectral import (
    test_oaconvolve_agrees_with_fftconvolve as test_tensor_spectral__test_oaconvolve_agrees_with_fftconvolve,
)
from test_tensor_spectral import (
    test_peak_prominences_matches_the_definition as test_tensor_spectral__test_peak_prominences_matches_the_definition,
)
from test_tensor_spectral import (
    test_peak_prominences_uses_the_higher_saddle as test_tensor_spectral__test_peak_prominences_uses_the_higher_saddle,
)
from test_tensor_spectral import (
    test_peak_prominences_rejects_an_index_off_the_signal as test_tensor_spectral__test_peak_prominences_rejects_an_index_off_the_signal,
)
from test_tensor_spectral import (
    test_decimate_keeps_a_slow_signal_and_shortens_it as test_tensor_spectral__test_decimate_keeps_a_slow_signal_and_shortens_it,
)
from test_tensor_spectral import (
    test_decimate_attenuates_a_signal_above_the_new_nyquist as test_tensor_spectral__test_decimate_attenuates_a_signal_above_the_new_nyquist,
)
from test_tensor_spectral import (
    test_zpk2tf_expands_a_real_root_pair as test_tensor_spectral__test_zpk2tf_expands_a_real_root_pair,
)
from test_tensor_spectral import (
    test_zpk2tf_of_a_conjugate_pair_is_real as test_tensor_spectral__test_zpk2tf_of_a_conjugate_pair_is_real,
)


def main() raises:
    var suite = TestSuite()
    # tests/signal/test_signal.mojo
    suite.test[test_signal__test_convolve_matches_numpy_on_an_asymmetric_pair]()
    suite.test[test_signal__test_convolve_with_a_delta_is_the_identity]()
    suite.test[
        test_signal__test_convolve_with_a_shifted_delta_shifts_the_signal
    ]()
    suite.test[test_signal__test_convolve_is_commutative]()
    suite.test[test_signal__test_convolve_sums_to_the_product_of_the_sums]()
    suite.test[test_signal__test_convolve_mode_same_takes_the_central_window]()
    suite.test[test_signal__test_convolve_mode_same_centres_an_odd_kernel]()
    suite.test[
        test_signal__test_correlate_matches_numpy_on_an_asymmetric_pair
    ]()
    suite.test[
        test_signal__test_correlate_equals_convolve_with_a_reversed_kernel
    ]()
    suite.test[test_signal__test_autocorrelation_peaks_at_zero_lag]()
    suite.test[test_signal__test_autocorrelation_at_zero_lag_is_the_energy]()
    suite.test[test_signal__test_hann_matches_its_closed_form]()
    suite.test[test_signal__test_hann_endpoints_are_exactly_zero]()
    suite.test[test_signal__test_hann_is_symmetric]()
    suite.test[test_signal__test_hann_peaks_at_one_for_odd_length]()
    suite.test[test_signal__test_hamming_endpoints_are_the_pedestal]()
    suite.test[test_signal__test_hamming_is_symmetric]()
    suite.test[test_signal__test_blackman_endpoints_are_zero]()
    suite.test[
        test_signal__test_blackman_is_narrower_at_the_shoulders_than_hann
    ]()
    suite.test[test_signal__test_apply_window_multiplies_elementwise]()
    suite.test[test_signal__test_windowing_suppresses_spectral_leakage]()
    suite.test[test_signal__test_convolve_differentiates_at_dual]()
    suite.test[test_signal__test_convolve_lanes_are_independent]()
    suite.test[
        test_signal__test_linear_convolution_matches_zero_padded_circular
    ]()
    suite.test[test_signal__test_lfilter_with_no_recursion_is_a_convolution]()
    suite.test[test_signal__test_lfilter_runs_a_recursion_no_convolution_can]()
    suite.test[test_signal__test_lfilter_divides_by_the_leading_coefficient]()
    suite.test[test_signal__test_firwin_passes_a_constant_unchanged]()
    suite.test[test_signal__test_firwin_is_symmetric_so_the_phase_is_linear]()
    suite.test[test_signal__test_firwin_attenuates_above_its_cutoff]()
    # tests/signal/test_tensor_convolution.mojo
    suite.test[
        test_tensor_convolution__test_convolve_matches_numpy_in_every_mode
    ]()
    suite.test[
        test_tensor_convolution__test_convolve_is_symmetric_in_its_arguments
    ]()
    suite.test[
        test_tensor_convolution__test_correlate_matches_numpy_in_every_mode
    ]()
    suite.test[
        test_tensor_convolution__test_correlate_is_convolve_with_the_taps_reversed
    ]()
    suite.test[
        test_tensor_convolution__test_fftconvolve_agrees_with_convolve_in_every_mode
    ]()
    suite.test[
        test_tensor_convolution__test_fftconvolve_of_long_inputs_agrees_with_the_direct_sum
    ]()
    suite.test[test_tensor_convolution__test_windows_match_scipy_symmetric]()
    suite.test[test_tensor_convolution__test_windows_match_scipy_periodic]()
    suite.test[test_tensor_convolution__test_kaiser_matches_scipy]()
    suite.test[test_tensor_convolution__test_get_window_names_the_factories]()
    suite.test[
        test_tensor_convolution__test_convolve_accepts_views_of_both_operands
    ]()
    # tests/signal/test_tensor_filters.mojo
    suite.test[test_tensor_filters__test_lfilter_matches_scipy]()
    suite.test[
        test_tensor_filters__test_lfilter_normalizes_by_a0_and_takes_a_longer_numerator
    ]()
    suite.test[test_tensor_filters__test_lfilter_zi_matches_scipy]()
    suite.test[test_tensor_filters__test_filtfilt_matches_scipy]()
    suite.test[test_tensor_filters__test_sosfilt_matches_scipy]()
    suite.test[
        test_tensor_filters__test_the_recurrence_runs_at_the_input_dtype
    ]()
    suite.test[
        test_tensor_filters__test_the_in_place_passes_leave_their_input_alone
    ]()
    suite.test[test_tensor_filters__test_medfilt_matches_scipy]()
    suite.test[test_tensor_filters__test_detrend_matches_scipy]()
    suite.test[
        test_tensor_filters__test_savgol_filter_matches_scipy_in_every_mode
    ]()
    suite.test[
        test_tensor_filters__test_savgol_filter_derivatives_match_scipy
    ]()
    suite.test[test_tensor_filters__test_resample_matches_scipy]()
    suite.test[test_tensor_filters__test_firwin_matches_scipy]()
    # tests/signal/test_tensor_spectral.mojo
    suite.test[test_tensor_spectral__test_periodogram_matches_scipy]()
    suite.test[test_tensor_spectral__test_welch_matches_scipy]()
    suite.test[test_tensor_spectral__test_spectrogram_matches_scipy]()
    suite.test[test_tensor_spectral__test_stft_matches_scipy]()
    suite.test[test_tensor_spectral__test_hilbert_matches_scipy]()
    suite.test[test_tensor_spectral__test_find_peaks_matches_scipy]()
    suite.test[test_tensor_spectral__test_butter_matches_scipy]()
    suite.test[test_tensor_spectral__test_butter_band_forms_match_scipy]()
    suite.test[test_tensor_spectral__test_cheby1_matches_scipy]()
    suite.test[test_tensor_spectral__test_cheby2_matches_scipy]()
    suite.test[test_tensor_spectral__test_ellip_matches_scipy]()
    suite.test[
        test_tensor_spectral__test_iirfilter_dispatches_on_ftype_and_refuses_an_unknown_one
    ]()
    suite.test[
        test_tensor_spectral__test_the_ripple_and_attenuation_arguments_are_honored
    ]()
    suite.test[test_tensor_spectral__test_freqz_matches_scipy]()
    suite.test[
        test_tensor_spectral__test_butter_feeds_freqz_with_unit_gain_at_dc
    ]()
    suite.test[
        test_tensor_spectral__test_csd_of_a_signal_with_itself_is_its_welch_psd
    ]()
    suite.test[
        test_tensor_spectral__test_csd_is_conjugate_symmetric_in_its_arguments
    ]()
    suite.test[test_tensor_spectral__test_coherence_lies_in_the_unit_interval]()
    suite.test[
        test_tensor_spectral__test_coherence_of_a_signal_with_itself_is_one
    ]()
    suite.test[
        test_tensor_spectral__test_coherence_of_a_scaled_copy_is_also_one
    ]()
    suite.test[test_tensor_spectral__test_istft_inverts_stft]()
    suite.test[
        test_tensor_spectral__test_istft_output_covers_at_least_the_original_length
    ]()
    suite.test[test_tensor_spectral__test_oaconvolve_agrees_with_fftconvolve]()
    suite.test[
        test_tensor_spectral__test_peak_prominences_matches_the_definition
    ]()
    suite.test[
        test_tensor_spectral__test_peak_prominences_uses_the_higher_saddle
    ]()
    suite.test[
        test_tensor_spectral__test_peak_prominences_rejects_an_index_off_the_signal
    ]()
    suite.test[
        test_tensor_spectral__test_decimate_keeps_a_slow_signal_and_shortens_it
    ]()
    suite.test[
        test_tensor_spectral__test_decimate_attenuates_a_signal_above_the_new_nyquist
    ]()
    suite.test[test_tensor_spectral__test_zpk2tf_expands_a_real_root_pair]()
    suite.test[test_tensor_spectral__test_zpk2tf_of_a_conjugate_pair_is_real]()
    suite^.run()
