"""GENERATED by tools/gen_test_aggregates.py -- do not edit.

Aggregates the 3 test files of `tests/fft/` into one compiled
binary, so 3 compiler invocations become one. Run it with
`mojo -I . -I tests/fft` (see tools/run_test_aggregates.sh).

Regenerate with `pixi run tests-gen`; CI fails if this file is out of date
with the tree.
"""

from std.testing import TestSuite
from test_fft import (
    test_fft_matches_a_naive_dft as test_fft__test_fft_matches_a_naive_dft,
)
from test_fft import (
    test_fft_of_a_constant_is_a_single_spike as test_fft__test_fft_of_a_constant_is_a_single_spike,
)
from test_fft import (
    test_fft_of_a_pure_tone_lands_in_two_bins as test_fft__test_fft_of_a_pure_tone_lands_in_two_bins,
)
from test_fft import test_ifft_inverts_fft as test_fft__test_ifft_inverts_fft
from test_fft import test_fft_is_linear as test_fft__test_fft_is_linear
from test_fft import (
    test_parseval_identity_holds as test_fft__test_parseval_identity_holds,
)
from test_fft import (
    test_real_input_spectrum_is_conjugate_symmetric as test_fft__test_real_input_spectrum_is_conjugate_symmetric,
)
from test_fft import (
    test_circular_convolution_matches_the_direct_sum as test_fft__test_circular_convolution_matches_the_direct_sum,
)
from test_fft import (
    test_fft_differentiates_through_dual as test_fft__test_fft_differentiates_through_dual,
)
from test_fft import (
    test_lanes_are_independent as test_fft__test_lanes_are_independent,
)
from test_fft import (
    test_single_point_transform_is_the_identity as test_fft__test_single_point_transform_is_the_identity,
)
from test_fft import (
    test_two_point_transform_is_sum_and_difference as test_fft__test_two_point_transform_is_sum_and_difference,
)
from test_fft import (
    test_rfft_returns_the_non_redundant_half as test_fft__test_rfft_returns_the_non_redundant_half,
)
from test_fft import (
    test_rfft_matches_the_full_transform_on_its_first_half as test_fft__test_rfft_matches_the_full_transform_on_its_first_half,
)
from test_fft import (
    test_rfft_dc_bin_is_the_sum_of_the_samples as test_fft__test_rfft_dc_bin_is_the_sum_of_the_samples,
)
from test_fft import (
    test_irfft_inverts_rfft as test_fft__test_irfft_inverts_rfft,
)
from test_fft import (
    test_rfft_of_a_pure_tone_puts_all_energy_in_one_bin as test_fft__test_rfft_of_a_pure_tone_puts_all_energy_in_one_bin,
)
from test_fft import (
    test_fftfreq_matches_numpys_layout as test_fft__test_fftfreq_matches_numpys_layout,
)
from test_fft import (
    test_rfftfreq_is_all_non_negative as test_fft__test_rfftfreq_is_all_non_negative,
)
from test_fft import (
    test_fftshift_moves_dc_to_the_middle as test_fft__test_fftshift_moves_dc_to_the_middle,
)
from test_fft import (
    test_fftshift_is_its_own_inverse_for_even_n as test_fft__test_fftshift_is_its_own_inverse_for_even_n,
)
from test_fft import (
    test_ifftshift_undoes_fftshift as test_fft__test_ifftshift_undoes_fftshift,
)
from test_fft import (
    test_ifft2_inverts_fft2 as test_fft__test_ifft2_inverts_fft2,
)
from test_fft import (
    test_fft2_of_a_constant_image_is_a_single_spike as test_fft__test_fft2_of_a_constant_image_is_a_single_spike,
)
from test_fft import (
    test_fft2_separates_into_row_then_column_transforms as test_fft__test_fft2_separates_into_row_then_column_transforms,
)
from test_tensor_fft import (
    test_fft_matches_numpy_on_the_ramp as test_tensor_fft__test_fft_matches_numpy_on_the_ramp,
)
from test_tensor_fft import (
    test_ifft_inverts_fft as test_tensor_fft__test_ifft_inverts_fft,
)
from test_tensor_fft import (
    test_fft_of_a_constant_is_a_single_spike as test_tensor_fft__test_fft_of_a_constant_is_a_single_spike,
)
from test_tensor_fft import (
    test_parseval_holds as test_tensor_fft__test_parseval_holds,
)
from test_tensor_fft import (
    test_rfft_is_the_half_spectrum_of_fft as test_tensor_fft__test_rfft_is_the_half_spectrum_of_fft,
)
from test_tensor_fft import (
    test_fftfreq_matches_numpy as test_tensor_fft__test_fftfreq_matches_numpy,
)
from test_tensor_fft import (
    test_fftfreq_scales_by_the_sample_spacing as test_tensor_fft__test_fftfreq_scales_by_the_sample_spacing,
)
from test_tensor_fft import (
    test_rfftfreq_is_non_negative as test_tensor_fft__test_rfftfreq_is_non_negative,
)
from test_tensor_fft import (
    test_the_two_tiers_agree as test_tensor_fft__test_the_two_tiers_agree,
)
from test_tensor_fft import (
    test_irfft_inverts_rfft as test_tensor_fft__test_irfft_inverts_rfft,
)
from test_tensor_fft import (
    test_irfft_of_a_dc_spike_is_constant as test_tensor_fft__test_irfft_of_a_dc_spike_is_constant,
)
from test_tensor_fft import (
    test_fftshift_centres_fftfreq as test_tensor_fft__test_fftshift_centres_fftfreq,
)
from test_tensor_fft import (
    test_fftshift_and_ifftshift_differ_at_odd_n as test_tensor_fft__test_fftshift_and_ifftshift_differ_at_odd_n,
)
from test_tensor_fft import (
    test_fft2_matches_numpy as test_tensor_fft__test_fft2_matches_numpy,
)
from test_tensor_fft import (
    test_ifft2_inverts_fft2_on_a_rectangle as test_tensor_fft__test_ifft2_inverts_fft2_on_a_rectangle,
)
from test_tensor_fft import (
    test_fft2_is_rows_then_columns as test_tensor_fft__test_fft2_is_rows_then_columns,
)
from test_tensor_fft import (
    test_rfft2_is_the_left_half_of_fft2 as test_tensor_fft__test_rfft2_is_the_left_half_of_fft2,
)
from test_tensor_fft import (
    test_fftshift_of_a_2d_spectrum_centres_dc as test_tensor_fft__test_fftshift_of_a_2d_spectrum_centres_dc,
)
from test_tensor_fft import (
    test_the_two_tiers_agree_on_fft2 as test_tensor_fft__test_the_two_tiers_agree_on_fft2,
)
from test_tensor_fft import (
    test_fft_matches_a_naive_dft_at_every_length_to_13 as test_tensor_fft__test_fft_matches_a_naive_dft_at_every_length_to_13,
)
from test_tensor_fft import (
    test_fft_at_a_prime_length_matches_numpy as test_tensor_fft__test_fft_at_a_prime_length_matches_numpy,
)
from test_tensor_fft import (
    test_ifft_inverts_fft_at_an_odd_length as test_tensor_fft__test_ifft_inverts_fft_at_an_odd_length,
)
from test_tensor_fft import (
    test_rfft_and_irfft_round_trip_at_an_odd_length as test_tensor_fft__test_rfft_and_irfft_round_trip_at_an_odd_length,
)
from test_tensor_fft import (
    test_fft2_at_non_power_of_two_extents_matches_numpy as test_tensor_fft__test_fft2_at_non_power_of_two_extents_matches_numpy,
)
from test_tensor_fft import (
    test_bluestein_agrees_with_radix2_at_a_power_of_two as test_tensor_fft__test_bluestein_agrees_with_radix2_at_a_power_of_two,
)
from test_tensor_fft import (
    test_next_fast_len_is_the_next_power_of_two as test_tensor_fft__test_next_fast_len_is_the_next_power_of_two,
)
from test_tensor_fft import (
    test_fft_sweeps_every_power_of_two_to_4096 as test_tensor_fft__test_fft_sweeps_every_power_of_two_to_4096,
)
from test_tensor_fft import (
    test_the_engine_runs_several_lanes_through_the_fused_block as test_tensor_fft__test_the_engine_runs_several_lanes_through_the_fused_block,
)
from test_tensor_fft import (
    test_rfft_and_irfft_round_trip_across_the_fused_block as test_tensor_fft__test_rfft_and_irfft_round_trip_across_the_fused_block,
)
from test_tensor_fft import (
    test_fft2_on_a_rectangle_of_powers_of_two as test_tensor_fft__test_fft2_on_a_rectangle_of_powers_of_two,
)
from test_tensor_trig import (
    test_dct_defaults_to_type_two as test_tensor_trig__test_dct_defaults_to_type_two,
)
from test_tensor_trig import (
    test_dct_types_match_scipy as test_tensor_trig__test_dct_types_match_scipy,
)
from test_tensor_trig import (
    test_dct_ortho_matches_scipy as test_tensor_trig__test_dct_ortho_matches_scipy,
)
from test_tensor_trig import (
    test_dst_types_match_scipy as test_tensor_trig__test_dst_types_match_scipy,
)
from test_tensor_trig import (
    test_dst_ortho_matches_scipy as test_tensor_trig__test_dst_ortho_matches_scipy,
)
from test_tensor_trig import (
    test_odd_length_matches_scipy as test_tensor_trig__test_odd_length_matches_scipy,
)
from test_tensor_trig import (
    test_idct_and_idst_match_scipy as test_tensor_trig__test_idct_and_idst_match_scipy,
)
from test_tensor_trig import (
    test_idct_inverts_dct_for_every_type_and_norm as test_tensor_trig__test_idct_inverts_dct_for_every_type_and_norm,
)
from test_tensor_trig import (
    test_idst_inverts_dst_for_every_type_and_norm as test_tensor_trig__test_idst_inverts_dst_for_every_type_and_norm,
)
from test_tensor_trig import (
    test_forward_norm_is_backward_scaled_by_the_inverse_factor as test_tensor_trig__test_forward_norm_is_backward_scaled_by_the_inverse_factor,
)
from test_tensor_trig import (
    test_dct_of_a_constant_is_a_dc_spike as test_tensor_trig__test_dct_of_a_constant_is_a_dc_spike,
)


def main() raises:
    var suite = TestSuite()
    # tests/fft/test_fft.mojo
    suite.test[test_fft__test_fft_matches_a_naive_dft]()
    suite.test[test_fft__test_fft_of_a_constant_is_a_single_spike]()
    suite.test[test_fft__test_fft_of_a_pure_tone_lands_in_two_bins]()
    suite.test[test_fft__test_ifft_inverts_fft]()
    suite.test[test_fft__test_fft_is_linear]()
    suite.test[test_fft__test_parseval_identity_holds]()
    suite.test[test_fft__test_real_input_spectrum_is_conjugate_symmetric]()
    suite.test[test_fft__test_circular_convolution_matches_the_direct_sum]()
    suite.test[test_fft__test_fft_differentiates_through_dual]()
    suite.test[test_fft__test_lanes_are_independent]()
    suite.test[test_fft__test_single_point_transform_is_the_identity]()
    suite.test[test_fft__test_two_point_transform_is_sum_and_difference]()
    suite.test[test_fft__test_rfft_returns_the_non_redundant_half]()
    suite.test[
        test_fft__test_rfft_matches_the_full_transform_on_its_first_half
    ]()
    suite.test[test_fft__test_rfft_dc_bin_is_the_sum_of_the_samples]()
    suite.test[test_fft__test_irfft_inverts_rfft]()
    suite.test[test_fft__test_rfft_of_a_pure_tone_puts_all_energy_in_one_bin]()
    suite.test[test_fft__test_fftfreq_matches_numpys_layout]()
    suite.test[test_fft__test_rfftfreq_is_all_non_negative]()
    suite.test[test_fft__test_fftshift_moves_dc_to_the_middle]()
    suite.test[test_fft__test_fftshift_is_its_own_inverse_for_even_n]()
    suite.test[test_fft__test_ifftshift_undoes_fftshift]()
    suite.test[test_fft__test_ifft2_inverts_fft2]()
    suite.test[test_fft__test_fft2_of_a_constant_image_is_a_single_spike]()
    suite.test[test_fft__test_fft2_separates_into_row_then_column_transforms]()
    # tests/fft/test_tensor_fft.mojo
    suite.test[test_tensor_fft__test_fft_matches_numpy_on_the_ramp]()
    suite.test[test_tensor_fft__test_ifft_inverts_fft]()
    suite.test[test_tensor_fft__test_fft_of_a_constant_is_a_single_spike]()
    suite.test[test_tensor_fft__test_parseval_holds]()
    suite.test[test_tensor_fft__test_rfft_is_the_half_spectrum_of_fft]()
    suite.test[test_tensor_fft__test_fftfreq_matches_numpy]()
    suite.test[test_tensor_fft__test_fftfreq_scales_by_the_sample_spacing]()
    suite.test[test_tensor_fft__test_rfftfreq_is_non_negative]()
    suite.test[test_tensor_fft__test_the_two_tiers_agree]()
    suite.test[test_tensor_fft__test_irfft_inverts_rfft]()
    suite.test[test_tensor_fft__test_irfft_of_a_dc_spike_is_constant]()
    suite.test[test_tensor_fft__test_fftshift_centres_fftfreq]()
    suite.test[test_tensor_fft__test_fftshift_and_ifftshift_differ_at_odd_n]()
    suite.test[test_tensor_fft__test_fft2_matches_numpy]()
    suite.test[test_tensor_fft__test_ifft2_inverts_fft2_on_a_rectangle]()
    suite.test[test_tensor_fft__test_fft2_is_rows_then_columns]()
    suite.test[test_tensor_fft__test_rfft2_is_the_left_half_of_fft2]()
    suite.test[test_tensor_fft__test_fftshift_of_a_2d_spectrum_centres_dc]()
    suite.test[test_tensor_fft__test_the_two_tiers_agree_on_fft2]()
    suite.test[
        test_tensor_fft__test_fft_matches_a_naive_dft_at_every_length_to_13
    ]()
    suite.test[test_tensor_fft__test_fft_at_a_prime_length_matches_numpy]()
    suite.test[test_tensor_fft__test_ifft_inverts_fft_at_an_odd_length]()
    suite.test[
        test_tensor_fft__test_rfft_and_irfft_round_trip_at_an_odd_length
    ]()
    suite.test[
        test_tensor_fft__test_fft2_at_non_power_of_two_extents_matches_numpy
    ]()
    suite.test[
        test_tensor_fft__test_bluestein_agrees_with_radix2_at_a_power_of_two
    ]()
    suite.test[test_tensor_fft__test_next_fast_len_is_the_next_power_of_two]()
    suite.test[test_tensor_fft__test_fft_sweeps_every_power_of_two_to_4096]()
    suite.test[
        test_tensor_fft__test_the_engine_runs_several_lanes_through_the_fused_block
    ]()
    suite.test[
        test_tensor_fft__test_rfft_and_irfft_round_trip_across_the_fused_block
    ]()
    suite.test[test_tensor_fft__test_fft2_on_a_rectangle_of_powers_of_two]()
    # tests/fft/test_tensor_trig.mojo
    suite.test[test_tensor_trig__test_dct_defaults_to_type_two]()
    suite.test[test_tensor_trig__test_dct_types_match_scipy]()
    suite.test[test_tensor_trig__test_dct_ortho_matches_scipy]()
    suite.test[test_tensor_trig__test_dst_types_match_scipy]()
    suite.test[test_tensor_trig__test_dst_ortho_matches_scipy]()
    suite.test[test_tensor_trig__test_odd_length_matches_scipy]()
    suite.test[test_tensor_trig__test_idct_and_idst_match_scipy]()
    suite.test[
        test_tensor_trig__test_idct_inverts_dct_for_every_type_and_norm
    ]()
    suite.test[
        test_tensor_trig__test_idst_inverts_dst_for_every_type_and_norm
    ]()
    suite.test[
        test_tensor_trig__test_forward_norm_is_backward_scaled_by_the_inverse_factor
    ]()
    suite.test[test_tensor_trig__test_dct_of_a_constant_is_a_dc_spike]()
    suite^.run()
