"""GENERATED by tools/gen_test_aggregates.py -- do not edit.

Aggregates the 1 test files of `tests/_root/` into one compiled
binary, so 1 compiler invocations become one. Run it with
`mojo -I . -I tests/_root` (see tools/run_test_aggregates.sh).

Regenerate with `pixi run tests-gen`; CI fails if this file is out of date
with the tree.
"""

from std.testing import TestSuite
from test_prelude import (
    test_the_builtins_survive_a_star_import as test_prelude__test_the_builtins_survive_a_star_import,
)
from test_prelude import (
    test_creation_and_manipulation_are_reachable as test_prelude__test_creation_and_manipulation_are_reachable,
)
from test_prelude import (
    test_elementwise_and_logic_are_reachable as test_prelude__test_elementwise_and_logic_are_reachable,
)
from test_prelude import (
    test_the_conformers_are_reachable as test_prelude__test_the_conformers_are_reachable,
)
from test_prelude import (
    test_linalg_and_the_bridge_are_reachable as test_prelude__test_linalg_and_the_bridge_are_reachable,
)
from test_prelude import (
    test_stats_and_io_are_reachable as test_prelude__test_stats_and_io_are_reachable,
)
from test_prelude import (
    test_the_rank_and_broadcast_surface_is_reachable as test_prelude__test_the_rank_and_broadcast_surface_is_reachable,
)


def main() raises:
    var suite = TestSuite()
    # tests/test_prelude.mojo
    suite.test[test_prelude__test_the_builtins_survive_a_star_import]()
    suite.test[test_prelude__test_creation_and_manipulation_are_reachable]()
    suite.test[test_prelude__test_elementwise_and_logic_are_reachable]()
    suite.test[test_prelude__test_the_conformers_are_reachable]()
    suite.test[test_prelude__test_linalg_and_the_bridge_are_reachable]()
    suite.test[test_prelude__test_stats_and_io_are_reachable]()
    suite.test[test_prelude__test_the_rank_and_broadcast_surface_is_reachable]()
    suite^.run()
