"""GENERATED by tools/gen_test_aggregates.py -- do not edit.

Aggregates the 2 test files of `tests/io/` into one compiled
binary, so 2 compiler invocations become one. Run it with
`mojo -I . -I tests/io` (see tools/run_test_aggregates.sh).

Regenerate with `pixi run tests-gen`; CI fails if this file is out of date
with the tree.
"""

from std.testing import TestSuite
from test_io import (
    test_save_load_round_trips_a_rank_1_tensor as test_io__test_save_load_round_trips_a_rank_1_tensor,
)
from test_io import (
    test_save_load_round_trips_a_rank_2_tensor as test_io__test_save_load_round_trips_a_rank_2_tensor,
)
from test_io import (
    test_save_load_round_trips_a_rank_3_tensor as test_io__test_save_load_round_trips_a_rank_3_tensor,
)
from test_io import (
    test_load_raises_on_dtype_mismatch as test_io__test_load_raises_on_dtype_mismatch,
)
from test_io import (
    test_load_raises_on_shape_mismatch as test_io__test_load_raises_on_shape_mismatch,
)
from test_io import (
    test_load_raises_on_rank_mismatch as test_io__test_load_raises_on_rank_mismatch,
)
from test_io import (
    test_load_raises_on_bad_magic_bytes as test_io__test_load_raises_on_bad_magic_bytes,
)
from test_io import (
    test_format_matches_a_frozen_small_array_string as test_io__test_format_matches_a_frozen_small_array_string,
)
from test_io import (
    test_format_truncates_arrays_over_threshold as test_io__test_format_truncates_arrays_over_threshold,
)
from test_io import (
    test_print_matches_format_defaults as test_io__test_print_matches_format_defaults,
)
from test_io import (
    test_a_matrix_prints_one_row_per_line as test_io__test_a_matrix_prints_one_row_per_line,
)
from test_io import (
    test_a_rank_three_tensor_separates_its_blocks as test_io__test_a_rank_three_tensor_separates_its_blocks,
)
from test_io import (
    test_truncation_applies_to_every_axis_that_is_long_enough as test_io__test_truncation_applies_to_every_axis_that_is_long_enough,
)
from test_npy import (
    test_numpy_load_reads_a_numpy_written_rank_1_float32_file as test_npy__test_numpy_load_reads_a_numpy_written_rank_1_float32_file,
)
from test_npy import (
    test_numpy_load_reads_a_numpy_written_rank_2_int32_file as test_npy__test_numpy_load_reads_a_numpy_written_rank_2_int32_file,
)
from test_npy import (
    test_numpy_save_output_is_byte_identical_to_numpy_save as test_npy__test_numpy_save_output_is_byte_identical_to_numpy_save,
)
from test_npy import (
    test_numpy_save_writes_numpys_rank_2_header_shape as test_npy__test_numpy_save_writes_numpys_rank_2_header_shape,
)
from test_npy import (
    test_npy_round_trips_through_numax as test_npy__test_npy_round_trips_through_numax,
)
from test_npy import (
    test_numpy_load_raises_on_fortran_order as test_npy__test_numpy_load_raises_on_fortran_order,
)
from test_npy import (
    test_numpy_load_raises_on_big_endian_descr as test_npy__test_numpy_load_raises_on_big_endian_descr,
)
from test_npy import (
    test_numpy_load_raises_on_dtype_mismatch as test_npy__test_numpy_load_raises_on_dtype_mismatch,
)
from test_npy import (
    test_numpy_load_raises_on_shape_mismatch as test_npy__test_numpy_load_raises_on_shape_mismatch,
)
from test_npy import (
    test_numpy_load_raises_on_a_non_npy_file as test_npy__test_numpy_load_raises_on_a_non_npy_file,
)
from test_npy import (
    test_load_dyn_takes_the_shape_from_the_file as test_npy__test_load_dyn_takes_the_shape_from_the_file,
)
from test_npy import (
    test_load_dyn_raises_on_a_rank_the_file_does_not_have as test_npy__test_load_dyn_raises_on_a_rank_the_file_does_not_have,
)


def main() raises:
    var suite = TestSuite()
    # tests/io/test_io.mojo
    suite.test[test_io__test_save_load_round_trips_a_rank_1_tensor]()
    suite.test[test_io__test_save_load_round_trips_a_rank_2_tensor]()
    suite.test[test_io__test_save_load_round_trips_a_rank_3_tensor]()
    suite.test[test_io__test_load_raises_on_dtype_mismatch]()
    suite.test[test_io__test_load_raises_on_shape_mismatch]()
    suite.test[test_io__test_load_raises_on_rank_mismatch]()
    suite.test[test_io__test_load_raises_on_bad_magic_bytes]()
    suite.test[test_io__test_format_matches_a_frozen_small_array_string]()
    suite.test[test_io__test_format_truncates_arrays_over_threshold]()
    suite.test[test_io__test_print_matches_format_defaults]()
    suite.test[test_io__test_a_matrix_prints_one_row_per_line]()
    suite.test[test_io__test_a_rank_three_tensor_separates_its_blocks]()
    suite.test[
        test_io__test_truncation_applies_to_every_axis_that_is_long_enough
    ]()
    # tests/io/test_npy.mojo
    suite.test[
        test_npy__test_numpy_load_reads_a_numpy_written_rank_1_float32_file
    ]()
    suite.test[
        test_npy__test_numpy_load_reads_a_numpy_written_rank_2_int32_file
    ]()
    suite.test[
        test_npy__test_numpy_save_output_is_byte_identical_to_numpy_save
    ]()
    suite.test[test_npy__test_numpy_save_writes_numpys_rank_2_header_shape]()
    suite.test[test_npy__test_npy_round_trips_through_numax]()
    suite.test[test_npy__test_numpy_load_raises_on_fortran_order]()
    suite.test[test_npy__test_numpy_load_raises_on_big_endian_descr]()
    suite.test[test_npy__test_numpy_load_raises_on_dtype_mismatch]()
    suite.test[test_npy__test_numpy_load_raises_on_shape_mismatch]()
    suite.test[test_npy__test_numpy_load_raises_on_a_non_npy_file]()
    suite.test[test_npy__test_load_dyn_takes_the_shape_from_the_file]()
    suite.test[
        test_npy__test_load_dyn_raises_on_a_rank_the_file_does_not_have
    ]()
    suite^.run()
