#!/usr/bin/env python3
"""Generate per-area aggregate test runners.

Why this exists
---------------
Every test file is a standalone Mojo program, and the `tests` task ran one
`mojo -I .` per file -- 87 compiler invocations, each elaborating the whole
`numax` source graph before it runs a single assertion. The cost is
compilation, not the test bodies. Aggregating an area's files into one
binary pays that elaboration once per area instead of once per file.

What it emits
-------------
`tests/_agg/agg_<area>.mojo` per subpackage: aliased imports of every
module-level `def test_*` in that area, then explicit registration on a
`TestSuite`.

Two things are deliberate:

* **Imports are aliased** (`test_x as linalg__test_qr__test_x`). Names
  repeat across files -- several areas have their own `test_basic` -- and
  aliasing means no test has to be renamed to be aggregated. Each file
  keeps its own module namespace.

* **Registration is explicit, never discovery.** Every numax test file ends
  in `TestSuite.discover_tests[__functions_in_module()]().run()`, and that
  is exactly what an aggregate must not do: `__functions_in_module()` finds
  the *aggregate's* functions, of which there are none, so it would print
  "Running 0 tests" and exit 0 -- a green run that executed nothing.
  Explicit `suite.test[fn]()` lines cannot fail that way, and `--check`
  is the drift gate that keeps the generated files honest.

Usage
-----
    python3 tools/gen_test_aggregates.py           # write the aggregates
    python3 tools/gen_test_aggregates.py --check   # fail if out of date
"""

from __future__ import annotations

import glob
import os
import re
import subprocess
import sys

TESTS = "tests"
OUT_DIR = os.path.join(TESTS, "_agg")

# Tests that cannot share a process with their neighbours.
#
# Empty, and that is a finding rather than an oversight. The two candidates
# were checked: the `/tmp` paths in `tests/io/` are distinct per file and
# per test (`numax_test_io` against `numax_test_npy`), and every RNG test
# calls `seed(n)` immediately before each draw it compares, so none of them
# depend on the global generator's incoming state. Add a file here with the
# reason if that ever stops being true; `run_test_aggregates.sh` has a
# matching list that still runs whatever is listed.
EXCLUDE: set[str] = set()

# Matches only `def test_name(`. numax has 1437 test functions and none are
# parameterized, so a `[` after the name would be a new shape worth
# noticing rather than quietly skipping -- see the guard in `discover`.
TEST_DEF = re.compile(r"^def (test_[A-Za-z0-9_]*)\s*\(", re.M)
TEST_DEF_ANY = re.compile(r"^def (test_[A-Za-z0-9_]*)\s*[\(\[]", re.M)

HEADER = '''"""GENERATED by tools/gen_test_aggregates.py -- do not edit.

Aggregates the {n_files} test files of `tests/{area}/` into one compiled
binary, so {n_files} compiler invocations become one. Run it with
`mojo -I . -I tests/{area}` (see tools/run_test_aggregates.sh).

Regenerate with `pixi run tests-gen`; CI fails if this file is out of date
with the tree.
"""

from std.testing import TestSuite
'''


def area_of(path: str) -> str:
    rel = path[len(TESTS) + 1 :]
    return rel.split("/")[0] if "/" in rel else "_root"


def module_of(path: str) -> str:
    """Bare module name, resolved against an area-scoped `-I`.

    Relative to the area directory, so `tests/linalg/test_qr.mojo` is
    `test_qr` under `-I tests/linalg`. Scoping the include per area rather
    than passing `-I tests` keeps a test directory from colliding with a
    top-level directory of the same name.
    """
    rel = path[len(TESTS) + 1 :]
    parts = rel[: -len(".mojo")].split("/")
    return ".".join(parts[1:]) if len(parts) > 1 else parts[0]


def alias(path: str, fn: str) -> str:
    return module_of(path).replace(".", "__") + "__" + fn


def discover() -> dict[str, list[tuple[str, list[str]]]]:
    """area -> [(file, [test fn names])]."""
    areas: dict[str, list[tuple[str, list[str]]]] = {}
    missing: list[str] = []
    for path in sorted(glob.glob(f"{TESTS}/**/*.mojo", recursive=True)):
        if path.startswith(OUT_DIR) or path in EXCLUDE:
            continue
        src = open(path).read()
        names = TEST_DEF.findall(src)
        # A file whose only tests are a shape the emitter cannot import
        # would be silently dropped, which deletes coverage without
        # failing anything. Catch the difference rather than trust it.
        if set(TEST_DEF_ANY.findall(src)) - set(names):
            sys.stderr.write(
                f"ERROR: {path} has a `def test_*[...]` parameterized test.\n"
                "The emitter imports plain functions only. Give it a\n"
                "concrete `def test_<name>() raises:` wrapper.\n"
            )
            raise SystemExit(2)
        if not names:
            missing.append(path)
            continue
        areas.setdefault(area_of(path), []).append((path, names))
    if missing:
        sys.stderr.write(
            "ERROR: these files have no module-level `def test_*` and would\n"
            "be silently excluded. Give each a `def test_<name>() raises:`\n"
            "wrapper, or add it to EXCLUDE with a reason:\n"
            + "".join(f"  {p}\n" for p in missing)
        )
        raise SystemExit(2)
    return areas


def render(area: str, files: list[tuple[str, list[str]]]) -> str:
    out = [HEADER.format(area=area, n_files=len(files))]
    for path, names in files:
        mod = module_of(path)
        for fn in names:
            out.append(f"from {mod} import {fn} as {alias(path, fn)}\n")
    out.append("\n\ndef main() raises:\n    var suite = TestSuite()\n")
    for path, names in files:
        out.append(f"    # {path}\n")
        for fn in names:
            out.append(f"    suite.test[{alias(path, fn)}]()\n")
    out.append("    suite^.run()\n")
    return "".join(out)


def formatted(body: str) -> str:
    """`body` after `mojo format`.

    Write mode formats what it emits, so `--check` has to compare against
    formatted text or it reports every file as stale.
    """
    import tempfile

    with tempfile.TemporaryDirectory() as d:
        tmp = os.path.join(d, "cand.mojo")
        open(tmp, "w").write(body)
        try:
            subprocess.run(["mojo", "format", tmp], capture_output=True, text=True)
        except FileNotFoundError:
            raise SystemExit(
                "ERROR: `mojo` is not on PATH. Run this through\n"
                "`pixi run tests-gen`; the candidate has to be formatted\n"
                "before it can be compared."
            )
        return open(tmp).read()


def main() -> int:
    check = "--check" in sys.argv
    areas = discover()
    os.makedirs(OUT_DIR, exist_ok=True)

    written, total_tests = [], 0
    for area, files in sorted(areas.items()):
        path = os.path.join(OUT_DIR, f"agg_{area}.mojo")
        body = render(area, files)
        total_tests += sum(len(n) for _, n in files)
        if check:
            prev = open(path).read() if os.path.exists(path) else ""
            if prev != formatted(body):
                sys.stderr.write(
                    f"ERROR: {path} is out of date. Run `pixi run tests-gen`.\n"
                )
                return 1
        else:
            open(path, "w").write(body)
        written.append((area, len(files), sum(len(n) for _, n in files)))

    # Drop aggregates for areas that no longer exist.
    keep = {f"agg_{a}.mojo" for a, _, _ in written}
    for stale in sorted(os.listdir(OUT_DIR)) if os.path.isdir(OUT_DIR) else []:
        if stale.endswith(".mojo") and stale not in keep:
            if check:
                sys.stderr.write(f"ERROR: stale aggregate {stale}\n")
                return 1
            os.remove(os.path.join(OUT_DIR, stale))

    verb = "checked" if check else "wrote"
    for area, nf, nt in written:
        print(f"  {verb} agg_{area}.mojo  {nf:>3} files  {nt:>5} tests")
    print(f"  {len(written)} aggregates, {total_tests} tests total")

    if not check:
        fmt = subprocess.run(
            ["mojo", "format", OUT_DIR], capture_output=True, text=True
        )
        if fmt.returncode != 0:
            sys.stderr.write(fmt.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
