#!/usr/bin/env python3
"""Generate per-area aggregate test runners.

Why this exists
---------------
Every test file is a standalone Mojo program, and the `tests` task ran one
`mojo -I .` per file -- 87 compiler invocations, each elaborating the whole
`numax` source graph before it runs a single assertion. The cost is
compilation, not the test bodies. Aggregating an area's files into one
binary pays that elaboration once per area instead of once per file.

What it emits
-------------
`<root>/_agg/agg_<area>.mojo` per subpackage, for each of the two test
roots: aliased imports of every module-level `def test_*` in that area,
then explicit registration on a `TestSuite`. `tests/` is the suite every
machine runs; `tests_gpu/` holds the `gpu=True` comparisons, which only
build where there is an accelerator (`pixi run tests-gpu`), but whose
aggregates are generated and drift-checked here like the rest.

Two things are deliberate:

* **Imports are aliased** (`test_x as linalg__test_qr__test_x`). Names
  repeat across files -- several areas have their own `test_basic` -- and
  aliasing means no test has to be renamed to be aggregated. Each file
  keeps its own module namespace.

* **Registration is explicit, never discovery.** Every numax test file ends
  in `TestSuite.discover_tests[__functions_in_module()]().run()`, and that
  is exactly what an aggregate must not do: `__functions_in_module()` finds
  the *aggregate's* functions, of which there are none, so it would print
  "Running 0 tests" and exit 0 -- a green run that executed nothing.
  Explicit `suite.test[fn]()` lines cannot fail that way, and `--check`
  is the drift gate that keeps the generated files honest.

Usage
-----
    python3 tools/gen_test_aggregates.py           # write the aggregates
    python3 tools/gen_test_aggregates.py --check   # fail if out of date
"""

from __future__ import annotations

import glob
import os
import re
import subprocess
import sys

ROOTS = ("tests", "tests_gpu")

# Tests that cannot share a process with their neighbors.
#
# Empty, and that is a finding rather than an oversight. The two candidates
# were checked: the `/tmp` paths in `tests/io/` are distinct per file and
# per test (`numax_test_io` against `numax_test_npy`), and every RNG test
# calls `seed(n)` immediately before each draw it compares, so none of them
# depend on the global generator's incoming state. Add a file here with the
# reason if that ever stops being true; `run_test_aggregates.sh` has a
# matching list that still runs whatever is listed.
EXCLUDE: set[str] = set()

# Areas too large to compile as one binary on a CI runner, split into
# parts `agg_<area>__<k>.mojo`, each part an explicit group of files;
# a file not listed in any group goes to the last part, so a new test is
# still picked up. Compile memory is roughly additive over an area's
# files, and `tests_gpu/linalg` as one `--target-accelerator sm_80`
# binary peaked at 25.7 GB -- past both CI runners (7 GB macOS, 16 GB
# Linux). Groups are balanced on each file's measured standalone peak
# (GB, sm_80, 2026-09-29): spectral 5.1, solvers 3.5, generalized_eigh
# 2.3, linalg 2.2, multishift 2.0, dynamic_lu 1.6, lu_plu 1.5, ldl 1.4,
# twostage 1.4, banded 1.0, array_kernels 0.9.
SPLIT: dict[str, list[list[str]]] = {
    "tests_gpu/linalg": [
        ["test_spectral_gpu.mojo"],
        ["test_solvers_gpu.mojo", "test_ldl_gpu.mojo"],
        [
            "test_generalized_eigh_gpu.mojo",
            "test_linalg_gpu.mojo",
            "test_array_kernels_gpu.mojo",
        ],
        [
            "test_multishift_gpu.mojo",
            "test_dynamic_lu_gpu.mojo",
            "test_lu_plu_gpu.mojo",
        ],
        ["test_twostage_gpu.mojo", "test_banded_gpu.mojo"],
    ],
}

# Matches only `def test_name(`. numax has 1437 test functions and none are
# parameterized, so a `[` after the name would be a new shape worth
# noticing rather than quietly skipping -- see the guard in `discover`.
TEST_DEF = re.compile(r"^def (test_[A-Za-z0-9_]*)\s*\(", re.M)
TEST_DEF_ANY = re.compile(r"^def (test_[A-Za-z0-9_]*)\s*[\(\[]", re.M)

HEADER = '''"""GENERATED by tools/gen_test_aggregates.py -- do not edit.

Aggregates the {n_files} test files of `{root}/{area}/` into one compiled
binary, so {n_files} compiler invocations become one. Run it with
`mojo -I . -I {root}/{area}` (see tools/run_test_aggregates.sh).

Regenerate with `pixi run tests-gen`; CI fails if this file is out of date
with the tree.
"""

from std.testing import TestSuite
'''


def area_of(root: str, path: str) -> str:
    rel = path[len(root) + 1 :]
    return rel.split("/")[0] if "/" in rel else "_root"


def module_of(root: str, path: str) -> str:
    """Bare module name, resolved against an area-scoped `-I`.

    Relative to the area directory, so `tests/linalg/test_qr.mojo` is
    `test_qr` under `-I tests/linalg`. Scoping the include per area rather
    than passing `-I tests` keeps a test directory from colliding with a
    top-level directory of the same name.
    """
    rel = path[len(root) + 1 :]
    parts = rel[: -len(".mojo")].split("/")
    return ".".join(parts[1:]) if len(parts) > 1 else parts[0]


def alias(root: str, path: str, fn: str) -> str:
    return module_of(root, path).replace(".", "__") + "__" + fn


def discover(root: str) -> dict[str, list[tuple[str, list[str]]]]:
    """area -> [(file, [test fn names])], under `root`."""
    areas: dict[str, list[tuple[str, list[str]]]] = {}
    missing: list[str] = []
    out_dir = os.path.join(root, "_agg")
    for path in sorted(glob.glob(f"{root}/**/*.mojo", recursive=True)):
        if path.startswith(out_dir) or path in EXCLUDE:
            continue
        src = open(path).read()
        names = TEST_DEF.findall(src)
        # A file whose only tests are a shape the emitter cannot import
        # would be silently dropped, which deletes coverage without
        # failing anything. Catch the difference rather than trust it.
        if set(TEST_DEF_ANY.findall(src)) - set(names):
            sys.stderr.write(
                f"ERROR: {path} has a `def test_*[...]` parameterized test.\n"
                "The emitter imports plain functions only. Give it a\n"
                "concrete `def test_<name>() raises:` wrapper.\n"
            )
            raise SystemExit(2)
        if not names:
            missing.append(path)
            continue
        areas.setdefault(area_of(root, path), []).append((path, names))
    if missing:
        sys.stderr.write(
            "ERROR: these files have no module-level `def test_*` and would\n"
            "be silently excluded. Give each a `def test_<name>() raises:`\n"
            "wrapper, or add it to EXCLUDE with a reason:\n"
            + "".join(f"  {p}\n" for p in missing)
        )
        raise SystemExit(2)
    return areas


def render(root: str, area: str, files: list[tuple[str, list[str]]]) -> str:
    out = [HEADER.format(root=root, area=area, n_files=len(files))]
    for path, names in files:
        mod = module_of(root, path)
        for fn in names:
            out.append(f"from {mod} import {fn} as {alias(root, path, fn)}\n")
    out.append("\n\ndef main() raises:\n    var suite = TestSuite()\n")
    for path, names in files:
        out.append(f"    # {path}\n")
        for fn in names:
            out.append(f"    suite.test[{alias(root, path, fn)}]()\n")
    out.append("    suite^.run()\n")
    return "".join(out)


def parts(
    root: str, areas: dict[str, list[tuple[str, list[str]]]]
) -> list[tuple[str, str, list[tuple[str, list[str]]]]]:
    """`(aggregate name, area, files)` for every aggregate: one per area,
    or one per group for an area in `SPLIT` (named `<area>__<k>`; the run
    script strips the suffix to find the area's include directory)."""
    out = []
    for area, files in areas.items():
        groups = SPLIT.get(f"{root}/{area}")
        if groups is None:
            out.append((area, area, files))
            continue
        by_name = {os.path.basename(path): (path, names) for path, names in files}
        placed: set[str] = set()
        chunks: list[list[tuple[str, list[str]]]] = []
        for group in groups:
            chunk = [by_name[f] for f in group if f in by_name]
            placed.update(f for f in group if f in by_name)
            chunks.append(chunk)
        leftover = [by_name[f] for f in sorted(by_name) if f not in placed]
        chunks[-1].extend(leftover)
        for k, chunk in enumerate(chunks, start=1):
            if chunk:
                out.append((f"{area}__{k}", area, sorted(chunk)))
    return out


def formatted(body: str) -> str:
    """`body` after `mojo format`.

    Write mode formats what it emits, so `--check` has to compare against
    formatted text or it reports every file as stale.
    """
    import tempfile

    with tempfile.TemporaryDirectory() as d:
        tmp = os.path.join(d, "cand.mojo")
        open(tmp, "w").write(body)
        try:
            subprocess.run(["mojo", "format", tmp], capture_output=True, text=True)
        except FileNotFoundError:
            raise SystemExit(
                "ERROR: `mojo` is not on PATH. Run this through\n"
                "`pixi run tests-gen`; the candidate has to be formatted\n"
                "before it can be compared."
            )
        return open(tmp).read()


def main() -> int:
    check = "--check" in sys.argv
    for root in ROOTS:
        if os.path.isdir(root) and generate(root, check) != 0:
            return 1
    return 0


def generate(root: str, check: bool) -> int:
    areas = discover(root)
    OUT_DIR = os.path.join(root, "_agg")
    os.makedirs(OUT_DIR, exist_ok=True)

    written, total_tests = [], 0
    for name, area, files in sorted(parts(root, areas)):
        path = os.path.join(OUT_DIR, f"agg_{name}.mojo")
        body = render(root, area, files)
        total_tests += sum(len(n) for _, n in files)
        if check:
            prev = open(path).read() if os.path.exists(path) else ""
            if prev != formatted(body):
                sys.stderr.write(
                    f"ERROR: {path} is out of date. Run `pixi run tests-gen`.\n"
                )
                return 1
        else:
            open(path, "w").write(body)
        written.append((name, len(files), sum(len(n) for _, n in files)))

    # Drop aggregates for areas that no longer exist.
    keep = {f"agg_{a}.mojo" for a, _, _ in written}
    for stale in sorted(os.listdir(OUT_DIR)) if os.path.isdir(OUT_DIR) else []:
        if stale.endswith(".mojo") and stale not in keep:
            if check:
                sys.stderr.write(f"ERROR: stale aggregate {stale}\n")
                return 1
            os.remove(os.path.join(OUT_DIR, stale))

    verb = "checked" if check else "wrote"
    for area, nf, nt in written:
        print(f"  {verb} agg_{area}.mojo  {nf:>3} files  {nt:>5} tests")
    print(f"  {root}: {len(written)} aggregates, {total_tests} tests total")

    if not check:
        fmt = subprocess.run(
            ["mojo", "format", OUT_DIR], capture_output=True, text=True
        )
        if fmt.returncode != 0:
            sys.stderr.write(fmt.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
